### ISSUE TITLE
One-sheet for project

### ISSUE THREAD

**Issue by snooravi** [hackforla/access-the-data#1]
### Dependency
~Waiting for logo #52~ 

### Overview
Write a one-sheet for the Data Literacy Project including milestones for the next 6 months.

### Action Items

- [x] Review 100Automations Project one-sheet
- [x] Review 311-Data Neighborhood Engagement Tool one-sheet
- [x] Produce First Draft of Data Literacy Project project
- [x] Prepare questions for review with Bonnie

### Resources/Instructions

[All project one-sheets](https://github.com/hackforla/product-managment/issues/3)

- [100Automations](https://docs.google.com/document/d/1Bk2uMaSdiZTKu9c-BMXSsC-Gk-ohK_NcmodQRvrgjTU/edit
)

- [311-Data Neighborhood Engagement Tool](https://github.com/hackforla/civic-opportunity/blob/master/Civic_Opportunity_Project_OnePage.pdf
)

- [Data Literacy Project](https://docs.google.com/document/d/1_CxBQ_ku4sanPIWKtPyENJ4E9hQKETQs8IWAOCzgqqk/edit)

### Access the Data One Sheet Drafts
[Previous Draft](https://docs.google.com/document/d/1_CxBQ_ku4sanPIWKtPyENJ4E9hQKETQs8IWAOCzgqqk/) - had mayors office as partner... we are working up to that.
[Current Draft](https://docs.google.com/document/d/1bWWhI0Zuas22sdEEDC6sSuRYZ3gXiBZ8LuyNUmD_s7o/)

**Comment by ExperimentsInHonesty** [comment]
@snooravi I made a few minor wording changes and added a bunch of notes.  Looking forward to the next review.

**Comment by snooravi** [comment]
@ExperimentsInHonesty Thanks for the comments! Went through it this morning--let me know what you think. I still plan to update the logo

**Comment by snooravi** [comment]
@ExperimentsInHonesty The one sheet is updated based on the feedback from today. LMK what you think.

**Comment by ExperimentsInHonesty** [comment]
@snooravi I made a new draft in the same folder
[Access the Data One Sheet - draft 3/18](https://docs.google.com/document/d/1bWWhI0Zuas22sdEEDC6sSuRYZ3gXiBZ8LuyNUmD_s7o) to take out the mayor's office since we don't have a rep from that department yet.

I also turned it into a pdf and put in the folder where we store those: 
https://github.com/hackforla/product-management/tree/master/project-one-sheets

**Comment by lrchang2** [comment]
need to review and review one-page for 6 month update

**Comment by ExperimentsInHonesty** [comment]
@abryant35 Add the link to the current published one sheet (pdf) and google doc.  And add this to next weeks pm meeting
