### ISSUE TITLE
Document the SEIE survey Qualitative Analysis process

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/access-the-data#101]
### Overview
We need to document the SEIE Qualitative Analysis and Presentation process so that we can have info for a case study and be able to replicate the process in the future

### Action Items
- [x] Find and link all relevant documents to this issue
- [x] Create a google doc and start outlining what was done and any useful notes about it.  This is just a draft, we will later make a markdown file for the wiki that is more of a summary document.

### Resources/Instructions
If you need to talk to Bonnie in the next two weeks, send her an email bonnie@hackforla.org with two times that you are available, and she will send back an invite.

Example of another project, where we did usability testing and then documented it
 https://github.com/hackforla/tdm-calculator/wiki/(Pilot-Page)-Usability-Testing 

~[Original Draft from Solee Shin and Justin Lee ](https://docs.google.com/document/d/1xlpyBClq6Py9K023REIijf3RHt7TLpH1zWW6759Oswk/edit#)(file seems to be located in Solee's personal drive)~ depreciated  
[Final Draft from Solee Shin and Justin Lee and Sarah Nooravi](https://docs.google.com/document/d/13TVGgBeNxRKLfq64E1KdJ8RlkZiIFhp_xrj1pw-gmpI/edit)

**Comment by ExperimentsInHonesty** [comment]
@Justlee98 @snooravi @soleeshin - 

@akhaleghi  and I are cleaning out the Data Science Google Drive, and we found this document created by Grace Jones, called [SEIE Themes](https://docs.google.com/document/d/1boyk7P_YdTh7Hyx12eHsIRbH2k27sGpzF-t92S2jObU/edit?usp=sharing)

It looks like people on the team have used it back in September

- Sarah
- Solee
- And Annon


Abe has reached out to Grace to move the file to the new shared drive but she has not responded.  

We went through all the issues that have the word SEIE in them
- https://github.com/hackforla/access-the-data/issues/101
- https://github.com/hackforla/access-the-data/issues/70
- https://github.com/hackforla/data-science/issues/65
- https://github.com/hackforlahttps://github.com/hackforla/product-management/issues/242
- https://github.com/hackforla/governance/issues/63
- https://github.com/hackforla/data-science/issues/26
- https://github.com/hackforla/product-management/issues/3

but we can't figure out what issue might link to it, so that we can replace the link with the copy. 

Can you figure out what issue this document is in and write back in this issue about it to Abe @akhaleghi

**Comment by snooravi** [comment]
[Here](https://docs.google.com/document/d/1xlpyBClq6Py9K023REIijf3RHt7TLpH1zWW6759Oswk/edit#) is the current Draft

**Comment by snooravi** [comment]
Made a copy and added to the drive [here](https://docs.google.com/document/d/13TVGgBeNxRKLfq64E1KdJ8RlkZiIFhp_xrj1pw-gmpI/edit#)

**Comment by snooravi** [comment]
@ExperimentsInHonesty Please take a look at the [final](https://docs.google.com/document/d/13TVGgBeNxRKLfq64E1KdJ8RlkZiIFhp_xrj1pw-gmpI/edit#heading=h.fygqv5wam51l) version and LMK if there's anything else you'd like added/changed.

**Comment by snooravi** [comment]
@ExperimentsInHonesty About the SEIE Theme's document you referred to, it's old work and unnecessary for our final deliverable, but I've made a copy and added it to our shared drive [here](https://docs.google.com/document/d/1qXKyjAhkBVFyKmG7dRxcwHe8T3vGxgxs5FOfGYVe3XA/edit)
