### ISSUE TITLE
311 Data Slides: Map 1 Slide

### ISSUE THREAD

**Issue by MalakH21** [hackforla/access-the-data#109]
### Overview

We need to add content to the 311 workshop slides to inform attendees what the terms: Bulky Items and Illegal Dumping mean so that they can understand the maps and other methods that follow.

### Action Items
- [x] 311 Data Map 1 : Demo an example using the map with the following parameters: 
-  date range: last 6 months
- NC: van nuys
- request type selection: select all request types

### Resources/Instructions
- [311 Data Workshop Outline](https://docs.google.com/document/d/1-WzGxAbqRENZByrrPepChhGxBRAkmNF5YbpTwyd6Oi8/edit)
- [311 Data Slides](https://docs.google.com/presentation/d/1mlYV3ELIGxeoxvKBAjjukZ51uTbl6daB5hcAIp9arDI/edit#slide=id.g10992d975c3_0_190)
- [Guide Template Graphics](https://docs.google.com/presentation/d/1RPo7y_tqNMeJIfl7p6frZW3QQUN1mUKcuB1yb2U7nfA/edit#slide=id.gcd84038bdd_0_0)

**Comment by lrchang2** [comment]
@MalakH21 Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by MalakH21** [comment]
Blockers: 0
Availability: 3 hours (Thursday PM)
ETA: EOW (01/21/2022)
Pictures: n/a - no changes to site - content creation

**Comment by lrchang2** [comment]
@MalakH21 Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by lrchang2** [comment]
@MalakH21 Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by lrchang2** [comment]
@MalakH21 
Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by MalakH21** [comment]
Progress: none to report 
Blockers: none to report 
Availability: 4 hours Saturday
ETA: Feb 23
Pictures: N/A

**Comment by lrchang2** [comment]
@MalakH21 Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by MalakH21** [comment]
completed data map feature slides, all data visualization slides outside of total requests + frequency, awaiting review 
blockers: 0 data for Jan 3- 18  total requests + frequency visualizations in (image attached
<img width="893" alt="Screen Shot 2022-02-21 at 6 09 47 PM" src="https://user-images.githubusercontent.com/40288906/155437424-ef42c662-92fa-470c-b274-25fa093aeae9.png">
<img width="891" alt="Screen Shot 2022-02-21 at 6 10 08 PM" src="https://user-images.githubusercontent.com/40288906/155437436-c8b3b639-06cc-42e8-98f3-54c96a935df9.png">
)

**Comment by MalakH21** [comment]
slides now live here : https://docs.google.com/presentation/d/1mlYV3ELIGxeoxvKBAjjukZ51uTbl6daB5hcAIp9arDI/edit#slide=id.g116292c21fa_1_42

**Comment by MalakH21** [comment]
done 👯  please disregard all the previous comments - the nature of the issue has changed fundamentally

**Comment by lrchang2** [comment]
@MalakH21 if this issue is completed, please close it out

**Comment by lrchang2** [comment]
closing issue since it's done
