### ISSUE TITLE
Role Recruitment: Product Management 

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#110]
### Dependency 
whenever audit in #4 determines the need for more resources 

### Overview
We need to recruit for product manager(s) to help move the project along. 

### Action Items
- [x] Get access to edit open role board by pinging #admin channel in slack
- [ ] Write blurb to put on the open role board based on template: 

```
**Project Name:** Access the Data

**Volunteer Opportunity:** [your opportunity description replaces these brackets]

**Duration:**

**Who to communicate your interest to:**

- Slack channel link: [#access-the-data](https://hackforla.slack.com/archives/C01L2ANCG6M)
- Slack name of person to contact in the channel

**When we meet:** 

[Read more about the project](https://www.hackforla.org/projects/access-the-data)

**Resources:**
```

- [ ] Review blurb 
- [ ] Follow [directions ](https://github.com/hackforla/product-management/projects/8#card-53859442)to put on open role board
- [ ] add project logo to posting (one on H4LA website)

### Resources/Instructions
[product management open role board](https://github.com/hackforla/product-management/projects/8)
[product management open role board for Access the Data](https://github.com/hackforla/product-management/projects/8?card_filter_query=access+the+data)

**Comment by lrchang2** [comment]
[need to recruit for 1-2 PMs](https://github.com/hackforla/access-the-data/issues/4#issuecomment-1010434886)

**Comment by lrchang2** [comment]
**Project Name:** Access the Data

**Volunteer Opportunity:** We are looking for 2 product managers, one to help develop workshops and the other for a website.

The workshops product manager will be in charge of guiding the develop of data literacy workshops and content to teach citizens how to use open source data for public good. You will be working closely with a team of data analysts to develop the workshops. 

The website product manager will be in charge of guiding the develop of a website that will house the workshops and additional educational resources. You will be working closely with a team of UX/UI designers and developers to create the website. 

Both PMs will be responsible for managing the Kanban board, creating and tracking issues, and building and updating the product roadmap. You'll be expected to attend and help run weekly meetings and as well as attend alignment meetings as needed.

**Duration:** open ended

**Who to communicate your interest to:**

- Slack channel link: #access-the-data
- Slack name of person to contact in the channel: Lucy Chang

**When we meet:** 
PM Meeting: Mondays 2-3PM PST
Team Meeting: Wednesdays 5-6PM PST

**Resources:**
[Read more about the project](https://www.hackforla.org/projects/access-the-data)

**Comment by lrchang2** [comment]
edited blurb to be shorter so it would fit the word count. 

posted blurb for[2 product managers](https://github.com/hackforla/product-management/projects/8#card-76483249) on the open board.

**Comment by lrchang2** [comment]
https://user-images.githubusercontent.com/37763229/112223238-e1163500-8be6-11eb-9877-4818ba411759.png

**Comment by Rabia2219** [comment]
#### Note

- We are using a new recruitment process https://github.com/hackforla/access-the-data/issues/304
