### ISSUE TITLE
Role Recruitment: Design

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#111]
### Dependency 
whenever audit in #4 determines the need for more resources 

### Overview
We need to recruit for UX/UI designer to help move the project along. 

### Action Items
- [ ] Get access to edit open role board by pinging #admin channel in slack
- [ ] Write blurb to put on the open role board based on template: 

```
**Project Name:** Access the Data

**Volunteer Opportunity:** [your opportunity description replaces these brackets]

**Duration:**

**Who to communicate your interest to:**

- Slack channel link: [#access-the-data](https://hackforla.slack.com/archives/C01L2ANCG6M)
- Slack name of person to contact in the channel:

**When we meet:** 

[Read more about the project](https://www.hackforla.org/projects/access-the-data)

**Resources:**
```

- [ ] Review blurb 
- [ ] Follow [directions ](https://github.com/hackforla/UI-UX/projects/3#card-53874282)to put on open role board

### Resources/Instructions
[UI-UX design open role board](https://github.com/hackforla/UI-UX/projects/3)
[UI-UX design open roles for Access the Data](https://github.com/hackforla/UI-UX/projects/3?card_filter_query=access)

**Comment by lrchang2** [comment]
took off open roles for UX/UI designer from board

**Comment by Rabia2219** [comment]
#### Note

- We are using a new recruitment process https://github.com/hackforla/access-the-data/issues/304
