### ISSUE TITLE
Role Recruitment: Data Analyst

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#113]
### Dependency 
- whenever audit in #4 determines the need for more resources 

### Overview
We need to recruit for data scientists/analysts to help move the project along. 

### Action Items

- [ ] Write blurb to put on the open role board based on template: 

```
**Project Name:** Access the Data

**Volunteer Opportunity:** [your opportunity description replaces these brackets]

**Duration:**

**Who to communicate your interest to:**

- Slack channel link: [#access-the-data](https://hackforla.slack.com/archives/C01L2ANCG6M)
- Slack name of person to contact in the channel:

**When we meet:** 

[Read more about the project](https://www.hackforla.org/projects/access-the-data)

**Resources:**
```

- [ ] Review blurb 
- [ ] Follow [directions ](https://github.com/hackforla/product-management/projects/8#card-53859442)to put on open role board

### Resources/Instructions
[Data science open role board](https://github.com/hackforla/data-science/projects/2#card-55546893)
[Data science open role board for Access the Data](https://github.com/hackforla/data-science/projects/2?card_filter_query=access#card-55546893)

**Comment by lrchang2** [comment]
project has 1 open role (data analyst) on the board

**Comment by ExperimentsInHonesty** [comment]
# Post from filled column of the Data Science Open Roles board.

<details><summary>copy of code</summary>

```
<img src="https://user-images.githubusercontent.com/37763229/112223238-e1163500-8be6-11eb-9877-4818ba411759.png" />

**Role**: Data (Analyst or Scientist) Familiar with data issues or curiosity to learn

**Project Name**: Access-The-Data

**Volunteer Opportunity**: We are looking for a data professional to help us develop workshops for the LA community. Responsibilities will include: 

- Exploring available city datasets & evaluate the consistency and content of resources that are candidates for inclusion
- Performing analysis (EDA) 
- Working with other H4LA teams to break down their datasets and workflows
- Outlining challenges and pitfalls with data

**Duration**: First workshop to be delivered by January

**Who to communicate your interest to**
- Slack channel link: #access-the-data
- Slack name of person to contact in the channel: Sarah Nabelsi

[Read more about the project](https://github.com/hackforla/access-the-data/)

**Volunteers:**
```
</details> 

<details><summary>Viewable post</summary>

<img src="https://user-images.githubusercontent.com/37763229/112223238-e1163500-8be6-11eb-9877-4818ba411759.png" />

**Role**: Data (Analyst or Scientist) Familiar with data issues or curiosity to learn

**Project Name**: Access-The-Data

**Volunteer Opportunity**: We are looking for a data professional to help us develop workshops for the LA community. Responsibilities will include: 

- Exploring available city datasets & evaluate the consistency and content of resources that are candidates for inclusion
- Performing analysis (EDA) 
- Working with other H4LA teams to break down their datasets and workflows
- Outlining challenges and pitfalls with data

**Duration**: First workshop to be delivered by January

**Who to communicate your interest to**
- Slack channel link: #access-the-data
- Slack name of person to contact in the channel: Sarah Nabelsi

[Read more about the project](https://github.com/hackforla/access-the-data/)

**Volunteers:**
</details>
