### ISSUE TITLE
311-data Workshop Resources Information Architecture 

### ISSUE THREAD

**Issue by snooravi** [hackforla/access-the-data#114]
### Overview
We need to develop an easy to navigate information architecture for the list of resources that the data analysts have provided for the 311-data workshop. 

### Action Items

- [ ] Attend workshops meeting while they work on #115 
    - [ ] Mondays 5PM PST
    - [ ] Wednesdays 5PM PST
- [ ] During meetings represent the personas in #90 and ask questions that guide data analysts in how they organize the resources 
- [ ] Get rapid prototype of resource info arch in wiki from data analyst
- [ ] Translate prototype for website page and flow
- [ ] Usability test information architecture 
- [ ] Edit based on test

### Resources/Instructions
[311 Data Research Resources](https://docs.google.com/document/d/1ETtQ45YuzQIlAsIX3A69KaLx9awsqucBRfqkgzn4hJI/edit#)

**open data stories**
[Bulky Items](https://xtown.la/2021/12/20/bulky-item-requests/)
[Trash can placement](https://empowerla.org/open-data-success-story-macarthur-park-nc-uses-clean-streets-index-to-place-new-trashcans/)

**Comment by lrchang2** [comment]
@hannahsgr Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by hannahsgr** [comment]
**Progress:** Bonnie and I met yesterday to go over 311 Data Research Resources. We went through all the files in the documents and added them to the Wiki. 
**Blockers:** There were two articles that need further clarification form Sarah and Mike. 
**Availability:** 6 hours
**ETA:** Meeting with Bonnie and the Data Analysts on Monday to get clarification on the articles.

**Comment by lrchang2** [comment]
@hannahsgr Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by hannahsgr** [comment]
Progress: Categorized the documents with the help of Mike and Sarah. 
Blockers: Still need to organize documents that belong to Mike (require further clarification). 
Availability: 6 hours
ETA: Meeting on Wednesday when this issue can be discussed further and resolved.

**Comment by hannahsgr** [comment]
Progress: Finalized content groupings with Sarah and Bonnie, will be creating new pages and completing the side navigation bar on GitHub. 
Blockers: Unfamiliarity with GitHub - how to create new pages, etc. - will look up 
Availability: 6 hours 
ETA: By Wednesday

**Comment by lrchang2** [comment]
@hannahsgr thank you for your update. if you need help on adding pages to the github, let me know and i'll show you how.

**Comment by lrchang2** [comment]
@hannahsgr 
Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by hannahsgr** [comment]
Hey Lucy! I'll be doing updates after Monday meetings. 

Progress: New pages/side navigation created 
Blockers: Need broader/website like categories for the side navigation bar
Availability: 6 hours 
ETA: Wednesday

**Comment by hannahsgr** [comment]
Progress: Finalized information architecture, will be working on creating a research/test plan. 
Blockers: None
Availability: 6 hours 
ETA: Wednesday

**Comment by hannahsgr** [comment]
Progress: Met with Steffie to go over the project and divided up the work. She will work on the screener/background questions and I will finalize the task list. 
Blockers: None 
Availability: 6 hours
ETA: I can have the task finalized by end of this week for review for next weeks research meetings.
