### ISSUE TITLE
Create a one pager for finding your NC

### ISSUE THREAD

**Issue by snooravi** [hackforla/access-the-data#116]
### Overview
In order to prevent time during the workshop to be used to teach people how to find their NC, we will aim to create a one pager that we can send as pre-work.

### Action Items

- [x] Create a one pager based on slides 10-11 [here](https://docs.google.com/presentation/d/1ueR5pYLyGvazpV03yvmOZ5rHFt0JCJwJME6rCYHdRy8/edit#slide=id.g1067131bffc_1_22) 
- [x] Review, edit and format for final audience

### Resources/Instructions
[Identify Neighborhood Council and City Council Pre-Work](https://docs.google.com/document/d/1Xv5Ph8abS2vCEIUEKQXO-p1_ze0vhWTlpmlcEtFHV_o/edit)

**Comment by ExperimentsInHonesty** [comment]
update: Malak will have this finished by end of week

**Comment by MalakH21** [comment]
done, can be found [here](https://docs.google.com/document/d/1Xv5Ph8abS2vCEIUEKQXO-p1_ze0vhWTlpmlcEtFHV_o/edit#)
<img width="500" alt="Screen Shot 2022-01-20 at 7 15 47 PM" src="https://user-images.githubusercontent.com/40288906/150448535-acb5c0a9-2bf7-4039-8941-649926034f4a.png">
<img width="475" alt="Screen Shot 2022-01-20 at 7 15 37 PM" src="https://user-images.githubusercontent.com/40288906/150448548-33979d7d-4da6-4cf4-9fbc-fd1ff670b0a2.png">

note: images in document attached

**Comment by ExperimentsInHonesty** [comment]
@MalakH21 We gave the document a little edit.  Can you remake the screen shots and put them in this [slide presentation](https://docs.google.com/presentation/d/1xu_lYuucKkBKD9jWfLDZkEv3PkmIjcFEf0MnjEJdV5c/copy) (just the screenshots) using the annotation method described in the slides without the arrows

We want to just highlight the one thing we want them to pay attention to using the orange outline.  Happy to explain more at the next meeting if you like.

**Comment by MalakH21** [comment]
updated the images to in the one pager to follow the guidelines in the linked slides, 

also added the images in a copy of the linked slides [here](https://docs.google.com/presentation/d/1E2X-XQHVAkRJq6TQ0o_qdp0x0yk7RA48mvrSsOm2n4Q/edit#slide=id.g10fc3d8e5e4_0_11)

**Comment by MalakH21** [comment]
everything is complete

**Comment by snooravi** [comment]
Done --can be found on project board
