### ISSUE TITLE
Design System - Component(s): Header and Footer

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#119]
### Overview
We need to develop library for the header and footer components so it can be passed off and used by the developers. 

### Additional Information

- Footer requires Access the Data logo and Hack for LA logo.
- Make the header reactive, current it is static. 
- The drop down menu (desktop) should have a hover effect. 

### Action Items

- [x] Do industry research on different types of headers and footers and the components that are included in them
- [x] Do an audit of all the UI components for the header and footer of high-fi wireframes
    - [x] mobile version
    - [x] desktop version
- [x] Collect all versions of header and footer and determine if designs need updating and standardizing (based on sizing, style, etc) 
    - [x] bring to design team to make final decisions  
- [x] detail out components in the design system of the figma 
   - [x] class
   - [x] css
   - [x] use
   - [x] context
 - [x] #195

### Resources/Instructions
[figma](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A5)

**Comment by lrchang2** [comment]
@TracyLuu Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by lrchang2** [comment]
@KC243 Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by KC243** [comment]
Progress: Finished action item 1 (Do industry research on different types of headers and footers and the components that are included in them)
Blockers: none
Availability: 4-6
ETA: In 1-2 weeks
Pictures: None 
Reference for Action item 1: https://www.figma.com/file/ogRwU7dOorqIlORIoHsFiQ/Header-and-Footer-Comparison?node-id=0%3A1

**Comment by KC243** [comment]
Progress: Finished action items 2-3
Blockers: need to bring updated designs to the team for feedback and finalizing before I'm able to proceed further
Availability: 4-6
ETA: 1 week after meeting with the team
Pictures:
![Desktop-Updated Header and Footer](https://user-images.githubusercontent.com/101949454/162110839-06e30470-97a4-422a-81d1-e0d9cf92fc48.jpg)
![Mobile- Updated Header and footer](https://user-images.githubusercontent.com/101949454/162110852-d5206689-8f3d-4240-a87e-682917d4d77c.jpg)
![Mobile-Blue Menu Overlay updated](https://user-images.githubusercontent.com/101949454/162110860-96984a61-c00b-41f4-8f17-5912ed6642bf.jpg)

**Comment by KC243** [comment]
Progress: In progress Action item 3 (will make new mockups of the header and footer based on the group feedback)
Blockers: none
Availability: 4-6
ETA: TBD based on group review of new mockups)
Pictures
![Landing 3](https://user-images.githubusercontent.com/101949454/163310470-9d94b2a6-2273-47dd-bc60-053a4c4d2d14.jpg)
![Landing 4](https://user-images.githubusercontent.com/101949454/163310488-d25154c9-3890-4831-97d2-94dd519347ab.jpg)
![Landing Page Mobile-1](https://user-images.githubusercontent.com/101949454/163310498-6339110d-de01-4f93-b6b5-4ae30dabe19d.jpg)
:

**Comment by KC243** [comment]
Progress: Action item 3 changed based on group feedback 
Blockers: none
Availability: 4-6
ETA:  by 4/24th tentatively
Pictures:
![Header 1](https://user-images.githubusercontent.com/101949454/164343056-ab4147ef-10b8-490e-be3f-d9e085a14df4.jpg)
![Header 2](https://user-images.githubusercontent.com/101949454/164343065-6b785295-575a-49a0-aa68-ffd707df2208.jpg)
![Footer](https://user-images.githubusercontent.com/101949454/164343080-e3793cf6-211b-4aa0-bd25-c7ddb7cfa317.jpg)
![Mobile Header](https://user-images.githubusercontent.com/101949454/164343122-e6ec46d6-4e8f-471a-9364-debf86457dcc.jpg)
![Mobile footer](https://user-images.githubusercontent.com/101949454/164343127-3d0b7c6d-436e-46b1-9c08-fd81f7dc1d2a.jpg)

**Comment by KC243** [comment]
Progress: Completed
Blockers: none
Availability: 4-6
ETA: Completed
Pictures:
![Header- updates April 2022](https://user-images.githubusercontent.com/101949454/165405845-f4466405-4186-4331-8138-abe956154ad2.jpg)


![Footer-updated April 2022](https://user-images.githubusercontent.com/101949454/165405856-2e925bce-d004-480e-9e1b-420e24679bc0.jpg)

**Comment by KC243** [comment]
Progress: None (look into header and footer coloring)
Blockers: Lack of time this week
Availability: 4-6
ETA: 1-2 days
Pictures:

**Comment by KC243** [comment]
Progress: Redoing the header and footer based on research teams new IA
Blockers: none
Availability: 4-6
ETA: TBD
Pictures
![Updated Header](https://user-images.githubusercontent.com/101949454/168181049-e4bc7a81-ef31-4e21-8554-4517b501b9ae.jpg)
:

**Comment by KC243** [comment]
Progress: Redoing the header and footer based on online research of footers and headers
Blockers: none
Availability: 4-6
ETA: TBD
Pictures:
![New Header Access the Data](https://user-images.githubusercontent.com/101949454/169170641-a91c8f2d-d452-4150-aac8-b711d19bcb8e.jpg)

![New Header with dropdown Access the Data](https://user-images.githubusercontent.com/101949454/169170646-a76e49d3-05aa-4d4f-bcba-83de7d7b8671.jpg)

**Comment by KC243** [comment]
Progress: Redoing the header and footer based on online research of footers and headers
Blockers: none
Availability: 4-6
ETA: TBD (I'm prototyping out the menus on both desktop and mobile.)
Current progress can be seen here: https://www.figma.com/proto/ogRwU7dOorqIlORIoHsFiQ/Header-and-Footer-Comparison?node-id=186%3A263&scaling=contain&page-id=0%3A1&starting-point-node-id=186%3A263&show-proto-sidebar=1

**Comment by lrchang2** [comment]
@KC243 
Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by KC243** [comment]
Progress: Components changed in mobile version to reflect changes agreed upon by the design team
Blockers: none
Availability: 4-6
ETA: TBD (based on looking at CKAN websites, we will need to add a search bar to the header on both versions)

**Comment by mxajPrice** [comment]
Closing issue per conversation with @KC243 in planning meeting 7 July 2022.

**Comment by lrchang2** [comment]
@KC243 Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by KC243** [comment]
Progress: Currently cleaning up the components page since previously people have created multiple components for the same asset.  Desktop Hi-fi pages have been redone with updated components.  Still need to check spacing.  
Blockers: Time
Availability: 2-4
ETA: TBD

**Comment by bkong** [comment]
@KC243 Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.
