### ISSUE TITLE
Design System - Component(s): Buttons

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#120]
### Dependency 
~#135~ 

### Overview
We need to develop library for the button components so it can be passed off and used by the developers. 

### Action Items

- [x] look at UI component for high-fi wireframes for button
- [x] do research on types of buttons and uses 
    - [x] standalone buttons
    - [x] carousel buttons
- [x] document sites and interfaces researched in figma
- [x] size 
   - [x] mobile
   - [x] desktop 
- [x] state of button
   - [x] focus 
   - [x] hover
   - [x] press/active (mobile) 
   - [ ] disable - if needed 
   - [ ] secondary - if needed 
- [x] create component with 
   - [x] class
   - [x] css
   - [x] use
   - [x] context

### Resources/Instructions
[figma](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A5)
[website competitor](https://docs.google.com/spreadsheets/u/2/d/1_cx15yObwAl3KZYJjDgqjXd7Njw2D05BfcSc1eGZDtU/edit#gid=1172277014)
[Index of Project Files for Website Requirements (see Research category)](https://docs.google.com/document/d/1BSl7gPa7ceHVHpQ2uYFxHGUk-sgUN8WJ4-dUYz1pg50/edit#)

**Comment by lrchang2** [comment]
@Archana-M Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by lrchang2** [comment]
realize there were 2 different button sizes applied to the prototype: bigger carousel button and smaller primary button. 

did a comparison of the bigger vs smaller buttons applied to the prototype. team decided that even though aesthetically the bigger button seemed more proportional to images and headings and the bigger button calls attention to it, we need to do a competitive analysis of button types and sizes to make an educated decision.

**Comment by lrchang2** [comment]
@Archana-M Please add update using this template 

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by Archana-M** [comment]
Progress: Completed the comparative analysis [Figma Link](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2402%3A5648)
Blockers: Discuss the comparative analysis with the team and come to a conclusion about the standard button size. 
Availability: 6 hours
ETA: 02/07

**Comment by lrchang2** [comment]
@Archana-M 
Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by Archana-M** [comment]
Progress: Completed working on buttons [figma](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2158%3A5281)
Would like to suggest that we go with small padding for buttons.

**Comment by lrchang2** [comment]
look at length of button copy (by character count) - does it need a specific call to action?

**Comment by lrchang2** [comment]
@Archana-M Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by Archana-M** [comment]
Progress: Working with Kaylena on Usability Testing
Blockers: No blockers
Availability: 6 hrs

**Comment by lrchang2** [comment]
@Archana-M Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by lrchang2** [comment]
button confirmed during usability testing, closing out issue
