### ISSUE TITLE
Audit Website Design System Development 

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#121]
### Overview
We need to create a roadmap on how we will develop the design system. 

### Action Items

- [ ] read H4LA design system document 
- [ ] conduct audit of reusable visual qualities and elements of current design that include:
   - [ ] color
   - [ ] typography
   - [ ] components
- [ ] after audit, standardize styles of components
- [ ] organize reusable components into categories 
- [ ] create github issues based on categories for designers to develop design system

### Resources/Instructions
[H4LA Design System ](https://docs.google.com/document/d/1zUVnInBcAi3HaoLFoHHjhlmWZvspPxYfg16kAm9nVVY/edit#heading=h.dnwbrbit3wmb)

**Comment by lrchang2** [comment]
from PM+leads meeting, added 
#125 
#96 
#122 
#123 
#124 
#126 

@KaylenaNguyen put down any suggestions you have after reading the document here

**Comment by lrchang2** [comment]
- confirm website copy and carousel sizing (above the fold) before layout/spacing

**Comment by KaylenaNguyen** [comment]
carousel has been updated. 
based on feedback, text and images have been swapped for zig-zag layout, for easier reading.
buttons have been changed to fit the rest of the page. smaller button for users when viewing on their own screens.
Archana and I will go over this on Monday and discuss questions for usability testing.

**Comment by lrchang2** [comment]
@KaylenaNguyen open the carousel issue back up and have you comment these insights in there.
