### ISSUE TITLE
Design System - Component(s): Text Fields

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#123]
### Overview
We need to develop library for the text fields components so it can be passed off and used by the developers. 

### Additional Information

- This component is an atomic component that will be used in the contact us form and waitlist form.
- based on usability testing, need to add text as a placeholder 

### Action Items

- [x] do industry research on how websites are using text fields 
- [x] audit text field being used in the current mobile and desktop high-fi wireframes 
- [x] collect all versions of text field inputs and determine if designs need updating and standardizing (based on sizing, style, etc) 
   - [x] bring to design team to finalize decisions
- [x] make sure versions of the text fields work in states for
   - [x] mobile
   - [x] desktop 
- [x] detail out component's within the figma
   - [x] class
   - [x] css
   - [x] use
   - [x] context

### Resources/Instructions
[figma](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A5)

**Comment by lrchang2** [comment]
@deepamohan22 Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by deepamohan22** [comment]
@lrchang2 
Progress : In progress. Completed first 3 tasks. Redesigned the text fields (desktop version). 
Blockers : No
Availability : 12 hrs
ETA : Two weeks from now.
Image 
<img width="377" alt="Acess the data screen shot" src="https://user-images.githubusercontent.com/102125634/160923499-1d7566fb-6fdc-4490-bb0b-b6103bd825e9.png">

**Comment by deepamohan22** [comment]
@lrchang2 

Progress : In progress. Completed the first 7 Tasks. Redesigned the text fields ( Mobile Version)
Blockers :  Yes, In remaining tasks - I did not understand the meaning of :  ' detail out component's within the figma section
Availability : 6 hrs.
ETA : One week from now
<img width="98" alt="Access data mobile version text fields Screenshot 2022-04-05 154808" src="https://user-images.githubusercontent.com/102125634/161863522-45850087-f97b-4e85-8eef-b2b2aea09d75.png">

**Comment by lrchang2** [comment]
@deepamohan22 what I mean by that is to put your component in the [design system page within the figma](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A5). If you look at the example "forms--input field" that is the template you can use to detail out the component for a developer. 
![image](https://user-images.githubusercontent.com/10827101/162263487-4e7e4259-0801-4fcf-a9b5-4e090da6c0d1.png)

**Comment by deepamohan22** [comment]
@lrchang2

Progress :  Completed all 12  Tasks. Redesigned the text fields ( Desktop & Mobile Versions)
Blockers : No
Availability : 2 more days
<img width="457" alt="Acess the data screen shot final design system" src="https://user-images.githubusercontent.com/102125634/163067769-d40bf699-9d7d-45a6-a45e-3a7874d9c4a9.png">

ETA : 2 more days

**Comment by lrchang2** [comment]
great work @deepamohan22! please bring to the design team to get feedback this week and if there are no improvements suggested to be made, please close out this issue and move onto a new one.

**Comment by deepamohan22** [comment]
@lrchang2 
Thanks Lucy. Sure I will discuss with team.

**Comment by lrchang2** [comment]
reopening issue to add drop down for subject field

**Comment by deepamohan22** [comment]
@lrchang2 ,
Progress : Finished.  Added the dropdown menu to the text field in both Desktop and Mobile versions.
Blockers : No
ETA : One week

**Comment by lrchang2** [comment]
@deepamohan22 thank you for the update. can you link where you put the current version of the dropdown and put screenshots here in an issue comment so i can find and review it?

**Comment by deepamohan22** [comment]
<img width="622" alt="image" src="https://user-images.githubusercontent.com/102125634/178860874-23899016-4530-4fd2-a6be-586af0aeff0b.png">
Mobile version : 
<img width="213" alt="image" src="https://user-images.githubusercontent.com/102125634/178861132-8cd6ef96-f5ab-4bd5-86b3-c1203000502b.png">
Figma Link :
https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=5166%3A21214

**Comment by deepamohan22** [comment]
https://www.figma.com/file/CW0T9tfhQ3WK92nQd7VFMn/My-Projects-Linkedin%2CFrirndly%2CPick-%24-Dine?node-id=1317%3A48756

**Comment by deepamohan22** [comment]
Sure
Thanks @lrchang2
