### ISSUE TITLE
Design System - Component(s): Section Layout, Grid, and Spacing

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#124]
### Overview
We need to develop library for the layout of the pages so it can be passed off and used by the developers. 

### Action Items

- [x] look at high-fi wireframes for current layout
- [x] parts 
   - [x] margins/paddings 
   - [x] header/text divider (line) 
   - [x] image sizing 
- [x] states
   - [x] mobile
   - [x] desktop 
- [x] create component with 
   - [x] class
   - [x] css
   - [x] use
   - [x] context
- [x] create grid system
   - [x] columns
   - [x] gutter
   - [x] margins

### Resources/Instructions
[figma](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A5)

**Comment by lrchang2** [comment]
@ri0nardo Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by ri0nardo** [comment]
Progress: Currently set all the margins and paddings to a set grid system that is consistent throughout each frame. Will need to review the margins and paddings to see if anything needs to be revised. Once the margins and paddings are complete with complete annotations, will proceed to start image sizing. After that will start the components.

Blockers: No blockers yet. Just very time-consuming.


Availability: I'll have around 4 hours of availability.


ETA: Excepting 2-3 weeks still.


Pictures: Compiling photos of sections that are half pixels that need to be revised to be a whole number.

**Comment by ri0nardo** [comment]
Progress: Currently organizing each padding and margin to match the individual color, so anyone (including a developer) can identify the sizing quickly. Also added an arrow depending on the direction of the margin or padding. (This portion is time-consuming). I am making both the mobile and web margins and padding sizes match.

Blockers: No blockers yet. Just very time-consuming. 

Availability: I'll have around 4 hours of availability.

ETA: Excepting 2 weeks still.

Pictures: None at this moment.

**Comment by ri0nardo** [comment]
Progress: Finished the paddings and margins with arrows showing the direction the paddings and margins go per item. I will create a library of colors and sizes used for padding and margins, so anyone reviewing will be able to look at the legend to recognize what size the color represents. Will call out the image sizing max size per area on the notes unless it would be better to label it with the margins and padding. Looking to have a review of the issue next week.

Blockers: No blockers yet. Just very time-consuming.

Availability: I'll have around 4 hours of availability.

ETA: Excepting 1 week still.

Pictures: None at this moment.

**Comment by ri0nardo** [comment]
Progress: Completed the margins, paddings, divider line, image sizing, states, class, use, context, and grid system per section of mobile and desktop. Started writing the CSS for the desktop and mobile. Did not get far. Noting that the components within the margins and paddings are not edited. If the text and images need to be within the margins, will need to clean up the desktop and mobile components for clean handoff. Did not know how to label the hover dots below the carousel, called it hover on the CSS. Hopefully, someone can write the CSS for that. The email form, if it was decided on for final design, the margins and paddings need to be revised. If any other task has been completed since it will need to be revised before handoff.

Blockers: No blockers.

Availability: None

ETA: Possibly another week since I didn't finish the CSS.

Pictures: None.

**Comment by mxajPrice** [comment]
This needs to be approved by @KC243 for closing.

**Comment by pbahle** [comment]
![screencapture-figma-file-nS5IqnutUT2FuPwwJObHaY-Access-the-Data-Main-Figma-2022-07-09-20_21_01](https://user-images.githubusercontent.com/36608233/178128804-feecbe5d-89c6-45fe-8723-3e0ccccc84f4.png)

Checked the spacing and layout against Figma's vertical grid system as well as  the alignment tools
