### ISSUE TITLE
Design System - Design: Graphics/Images

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#126]
### Overview
We need to standardize image use so they don't look stretch and pixelated. 

### Action Items

- [x] get blush plugin on figma 
- [x] check how images are being used 
- [x] do any audit for images within the mobile and desktop high-fi wireframes 
- [x] collect all versions of images and determine if designs are inconsistent (based on sizing, style, etc) and if we need to standardize them 
   - [x] bring to design team to make decisions on standardization 
- [x] make sure versions of the images work in states: for
   - [x] mobile
   - [x] desktop 
- [x] detail out component's within the figma
   - [x] class
   - [x] css
   - [x] use
   - [x] context

### Resources/Instructions
[figma](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A5)

**Comment by deepamohan22** [comment]
@lrchang2 
Progress : Completed 5 tasks.
Blockers : No 
Question : Is this whole tasks only for Workshop page ? 
Availability : 6 hrs.
 ETA       :  1week
