### ISSUE TITLE
Research Plan: Community Activist Persona

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#127]
### Overview
We need to create a research plan for talking to people who give back to their community but do not have a data science background. 

### Action Items

- [x] Familiarize self with targeted persona in #90
- [x] read up on Hack for LA UX/UI research plan issue guide and past Access the Data research work to guide research plan draft development
- [x] create research plan draft (in a Google Doc within our shared drive) 
- [x] review with UX research team and edit draft based on feedback 
- [x] review with PMs and edit draft based on feedback 
- [x] review with organization and edit draft based on feedback 
- [x] add approved research plan example to [research plan issue](https://github.com/hackforla/UI-UX/issues/120) in the Hack for LA UX/UI github 

### Resources/Instructions
[Persona 1 Research Plan](https://docs.google.com/document/d/1yayDQm-WFxm63PKHfuXBRQJSAAyU2f1xFPt3n1dBjpg/edit?usp=sharing)

[guide on how to write a research plan issue](https://github.com/hackforla/UI-UX/issues/120)
[issue with Access the Data website research plan](https://github.com/hackforla/access-the-data/issues/62)
[issue with Access the Data UX Research Protocol](https://github.com/hackforla/access-the-data/issues/75)
[Access the Data - Research Plan document](https://docs.google.com/document/d/1HGCrxVwHT-O72HnyDLpfJ_cphFm_t6xBg2CEfbzfRsE/edit)
[Access the Data Recruitment Ideas FigJam](https://www.figma.com/file/BrCJpzDSx7vmfzObFVopaH/Recruitment?node-id=0%3A1)

[results from last interview](https://drive.google.com/drive/u/2/folders/1aq73jNAAoAcqY1A_D_8UGu5N4LeUKGdX)

**Comment by lrchang2** [comment]
@kimberly-tellez Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by kimberly-tellez** [comment]
@lrchang2 let me know if you want to continue being tagged in all progress updates.

Progress: I'm reviewing all of the content that is related to the ATD research plan & Persona #1. I've created an outline for the research plan but still need to populate the details, including creating new screener survey questions to target community activists.
Blockers: I noticed that the survey that already exists asks potential users about their data habits, so I need to create a screener survey that will be used only as a screener to identify community activists to interview.
Availability: I have 2 hours on Tuesday, 2 hours on Wednesday, and then 2 hours during our meeting times were I will request feedback.
ETA: Feedback will be requested during meeting on 2/9 and/or 2/10, then additional feedback will be requested through slack/email. Once feedback is recieved, all changes should be implemented within the week. I'm aiming to have this done by 2/16 or sooner.
Pictures: N/A

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by lrchang2** [comment]
@kimberly-tellez thank you for your update. you can tag me if you want. I get notifications for any comment in our repo and look at all the issues, so i'll see it anyways. 

when you get a chance, please provide hyperlinks to all the materials that you produce under the "Resources/Instructions" section of the issue

**Comment by lrchang2** [comment]
@kimberly-tellez Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by kimberly-tellez** [comment]
Progress: Research plan has been drafted and feedback recieved, I need to finalize the plan taking into account feedback and create screener survey questions to add to the research plan. I will need feedback on screener survey questions during meeting on 2/17.
Blockers: N/A
Availability: 2 hrs on 2/16, 2 hrs on 2/17 (not including meeting hours), another hour on 2/18 if needed
ETA: This issue should be done this week by 2/18

Resources:
[Persona 1 Research Plan](https://docs.google.com/document/d/1yayDQm-WFxm63PKHfuXBRQJSAAyU2f1xFPt3n1dBjpg/edit?usp=sharing)

**Comment by lrchang2** [comment]
after talking to org, we 
- added a new research question to learn about the tools currently use for story telling and social advocacy and the language used 
- defined the value that Access the Data provides to potential outside organizations/community advocates

next steps are for 
- org needs to add notes to the research plan 
- write up a description of how outside organizations could work with Access the Data vs Hack for LA 
- write up a draft of the outreach language (i.e. email) to LA grassroots organizations

**Comment by lrchang2** [comment]
@kimberly-tellez Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by lrchang2** [comment]
@kimberly-tellez 
Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by lrchang2** [comment]
@kimberly-tellez 
Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by lrchang2** [comment]
@kimberly-tellez 
Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.
