### ISSUE TITLE
Spatial Analysis for Bulky Items 2021

### ISSUE THREAD

**Issue by mcmorgan27** [hackforla/access-the-data#128]
### Overview

Create data story similar to the graffiti removal request type.  Focus on bulky items.

### Action Items

- [x] Build out basic analysis for bulky items
- [x] Create choropleth maps
- [x] Created data for gdrive
- [x] Save results as notebook
- [x] Save png files into the drive with proper titles (time frame & request type & analysis type)
- [x] Update [github](https://github.com/hackforla/access-the-data-workshop-311-analysis)

### Resources/Instructions

Continue analysis with myla311 data sets for 2021.

**Comment by mcmorgan27** [comment]
This is the PM stuff that ....

**Comment by snooravi** [comment]
@mcmorgan27 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by snooravi** [comment]
Hey @mcmorgan27. Please provide update:

Progress
Blockers
Availability
ETA

**Comment by mcmorgan27** [comment]
Progress: Added overview charts on gdrive
Blockers:  None
Availability: Time it takes to update to github
ETA: 02/16/2022

**Comment by mcmorgan27** [comment]
Pushed two notebooks + data.  Will keep issue open until I hear back.

**Comment by mcmorgan27** [comment]
I think the notebooks are ok.  I'm going to close this issue.
