### ISSUE TITLE
Access the Data Logo Perception Study 

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#129]
### Overview
We need to do a usability test on the potential logo to make a decision on which version of the logo to go with. 

### Action Items

- [x] Create png versions of logo with straight lines and rounded lines 
- [x] Create usability test to compare the two types of logos 
- [x] Review test with PMs 
- [x] recruit for participants 
   - [x] ask team members during Wednesday team meeting 
   - [x] send in slack general channel for HfLA 
- [ ] review results and make decision

### Resources/Instructions
[Engage's Logo Usability Study](https://github.com/hackla-engage/start-here/issues/15)

[Access the Data logo usability hub study ](https://app.usabilityhub.com/do/72604272480f/a887)

**Comment by lrchang2** [comment]
@katelyntn please put all your progress with screenshots here. 

you can use the template below: 
Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

**Comment by katelyntn** [comment]
Progress: Set up a usability test on the rounded or non-round logo & iterated the usability test based on Lucy's feedback.
Blockers: No blockers
Availability: 3-4 hrs
ETA: results and decision making should take place next week
Pictures:

**Comment by lrchang2** [comment]
consider if we want to keep the blue background.
![image](https://user-images.githubusercontent.com/10827101/153323121-500a0c87-a746-49b5-87e9-a7784b0db7fd.png)

play around with text colors with white background

**Comment by lrchang2** [comment]
@katelyntn 
Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by katelyntn** [comment]
Progress: Based on discussion with team, we decided to have a logo on the left of the text. Made a change to one of the logo, will need to update usability test then we can send them out
Blockers: no
Availability: 3-5 hrs
ETA: when we get our usability results
Pictures:
<img width="479" alt="Group 251" src="https://user-images.githubusercontent.com/75820160/154591832-00b39156-9c08-4818-a0be-a84fb9f7682f.png">
<img width="479" alt="Group 250" src="https://user-images.githubusercontent.com/75820160/154591836-c7e7fffc-e8e9-4295-aa4a-eb265ae887c0.png">

**Comment by mcmorgan27** [comment]
FWIW the top one resonates with me.

**Comment by lrchang2** [comment]
sent out usability hub study to #access-the-data channel in slack

**Comment by lrchang2** [comment]
@katelyntn Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by lrchang2** [comment]
@katelyntn 
Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by katelyntn** [comment]
Progress: Gathered data from our testing on the logo. Test results https://app.usabilityhub.com/tests/72604272480f/results/b61b1180be0e
Blockers: Time
Availability: 2-3 hrs
ETA: Tomorrow's meeting
Pictures:
