### ISSUE TITLE
311 Data Slides: Request Type Definitions

### ISSUE THREAD

**Issue by Avangarde2225** [hackforla/access-the-data#133]
### Overview
We need to add content to the 311 workshop slides to inform attendees what the terms: Bulky Items and Illegal Dumping mean so that they can understand the maps and other methods that follow. 

### Action Items
  - [x]  Request Type Definitions: in the definitions for Bulky Item and Illegal Dumping and tell people where to find the rest of the definitions

### Resources/Instructions
- [311 Data Workshop Outline](https://docs.google.com/document/d/1-WzGxAbqRENZByrrPepChhGxBRAkmNF5YbpTwyd6Oi8/edit)
- [311 Data Slides](https://docs.google.com/presentation/d/1mlYV3ELIGxeoxvKBAjjukZ51uTbl6daB5hcAIp9arDI/edit#slide=id.g10992d975c3_0_190)
- [Guide Template Graphics](https://docs.google.com/presentation/d/1RPo7y_tqNMeJIfl7p6frZW3QQUN1mUKcuB1yb2U7nfA/edit#slide=id.gcd84038bdd_0_0)

**Comment by Avangarde2225** [comment]
Updated 10th and 11th slides https://docs.google.com/presentation/d/1mlYV3ELIGxeoxvKBAjjukZ51uTbl6daB5hcAIp9arDI/edit#slide=id.g1159c1a4cab_0_1

Only missing part I am currently working on is the plotly map of the NCs.

**Comment by ExperimentsInHonesty** [comment]
@Avangarde2225 please change the following on the side where it currently has a very long url to be the url linked to the text

See the [Data Origin and Request Types](https://docs.google.com/document/d/1-WzGxAbqRENZByrrPepChhGxBRAkmNF5YbpTwyd6Oi8/edit#) one sheet for more request type definitions

**Comment by ExperimentsInHonesty** [comment]
@Avangarde2225 I am separating this issue into two issues.  As soon as you have finished making the change above, you can pick up the other issue #136 136

**Comment by lrchang2** [comment]
@Avangarde2225 
Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by Avangarde2225** [comment]
Progress: This issue has been completed. Please refer to the slide #11 : https://docs.google.com/presentation/d/1mlYV3ELIGxeoxvKBAjjukZ51uTbl6daB5hcAIp9arDI/edit#slide=id.g113bcaff670_2_34
Blockers: My laptop died.

Updated the slide #13 as well. More details can be seen here: https://public.tableau.com/app/profile/serdar.celebi/viz/LACity311ServiceRequestCallsDashboard/Dashboard_1
