### ISSUE TITLE
UX/UI Lead Wiki Update

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#134]
### Overview
We need the UX/UI leads to document and link all resources within the Access the Data wiki so a new person joining the team can have access to whatever they need for their role. 

### Action Items

- [x] Collect all research developed for the project
- [x] Write up all past research done and results from it in the github wiki 
- [x] Link any associated resources to the wiki

### Resources/Instructions
[Prior and Ongoing Research](https://github.com/hackforla/access-the-data/wiki/Prior-and-Ongoing-Research)

**Comment by joanna-pham** [comment]
@lrchang2 Updated Wiki Page labeled [Prior and Ongoing Research](https://github.com/hackforla/access-the-data/wiki/Prior-and-Ongoing-Research) with majority of what was completed.

**Comment by lrchang2** [comment]
@melissamurphy when you get the chance, please review what joanna has provided and add any other notes.

**Comment by lrchang2** [comment]
@melissamurphy Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.
