### ISSUE TITLE
A/B Testing and Usability Testing of Components 

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#135]
### Overview
We need to conduct an A/B testing of certain components of the desktop and mobile version to see if the design needs to be adjusted to be more user friendly. 

### Action Items

- [x] Determine website components that want to be tested 
- [x] Develop questions that need to be tested for each component 
- [x] Develop documentation for testing 
- [x] Review test with team, leads and PMs
- [x] Have team conduct 2 usability tests using script 
- [x] affinity map results during team meeting and determine takeaways

### Resources/Instructions
[wireframes with carousel](https://www.figma.com/proto/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?page-id=2%3A16&node-id=2906%3A8862&viewport=243%2C48%2C0.08&scaling=scale-down-width&starting-point-node-id=2906%3A8862&show-proto-sidebar=1)
[wireframes without Carousel](https://www.figma.com/proto/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?page-id=2%3A16&node-id=2906%3A9462&viewport=243%2C48%2C0.08&scaling=scale-down-width&starting-point-node-id=2906%3A9462&show-proto-sidebar=1)
[observational study template](https://docs.google.com/document/d/1UWzUzARGZuWntjqVDjdebB6fWbtgvwotPFUq7lJvBLs/edit)

[results in affinity map](https://www.figma.com/file/cBlZcrdFEv7xlTS3XUAnCK/Field-Study-Carousel-and-Cards?node-id=0%3A1)

**Comment by lrchang2** [comment]
We have determined that we need to test the carousel and the buttons within the carousel #96 #120

**Comment by lrchang2** [comment]
@Archana-M @KaylenaNguyen moving all your work into this issue, please put an update and any necessary notes within here.

**Comment by Archana-M** [comment]
Here are the questions that we want to discuss with the team for usability testing https://docs.google.com/document/d/1Yve2xkk6EtvPTnXT2yvr4D17_f6S0ZMqhrYqJBOoLvE/edit

**Comment by KaylenaNguyen** [comment]
I've updated the navigation bar. submenu for 311 Data under "workshops"
I've also changed the resources link to the GitHub link that you provided.

**Comment by lrchang2** [comment]
- warning for outside links 
-

**Comment by lrchang2** [comment]
next steps are to work on refining the carousel and cards with the feedback from usability testing

**Comment by lrchang2** [comment]
@Archana-M @KaylenaNguyen can we close out this issue?

**Comment by Archana-M** [comment]
@lrchang2 yes.
cc: @KaylenaNguyen

**Comment by lrchang2** [comment]
apologies for the late response, yes lets make another issue. i will close out this one for now
