### ISSUE TITLE
Ecosystem Maps C&C Analysis

### ISSUE THREAD

**Issue by snooravi** [hackforla/access-the-data#14]
### Overview
We need to determine what visualization is best suited for showing the relationships between organizations that we are partnering with for this project.

### Action Items
Explore google for existing map visuals and see which one aligns best with the data we are trying to show. Do an analysis and make a recommendation.

### Resources/Instructions
See [here](https://docs.google.com/spreadsheets/d/1JKMw4BT-i4gUC73lRXxI5g4yWOxhQ5OOAhG58Ch1LqY/edit#gid=603153564) for data we will be attempting to visualize

**Comment by MalakH21** [comment]
some updates to this task can be found [here](https://docs.google.com/document/d/1m5IQS5UeJYh15c1jzCTaRM5t6R9hGPfDzOYLuW1L8Lg/edit)
