### ISSUE TITLE
Tree Testing Information Architecture 

### ISSUE THREAD

**Issue by hannahsgr** [hackforla/access-the-data#143]
### Overview
Test Access the Data’s top navigation menu to see how easily people can find the information that they’re looking for. Identify any road blocks in the user journey. 

### Action Items
- [x] Finalize user tasks 
- [x] Create the tree test
- [x] Launch the tree test
- [x] Analyze the data 

### Resources/Instructions
https://github.com/hackforla/access-the-data/wiki
[IA Tree Test Research Plan](https://docs.google.com/document/d/1oY6cs4Qp3m4e96cta7417Y5H-wM6U3yadb3TG1Eaqvg/edit)
[Figma Site map](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/?node-id=2%3A7)
[Figma IA](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A9)
[ATD IA Tree Test Research Report](https://docs.google.com/document/d/1KuT9qGVelrBj5ecqJnJkSlS-xRuzOnKhnYAqT77_ctk/edit?usp=sharing)

**Comment by hannahsgr** [comment]
Progress: Created and launched the tree test. Posted the test on various Slack channels. 
Blockers: Getting enough participants to complete the tree test. 
Availability: 6 hours
ETA: Friday

**Comment by hannahsgr** [comment]
Progress: Reviewing statistical models in excel. My past experience is primarily using descriptive statistics. 
Blockers: I'm still unsure how to use quant methods in excel to analyze the tree testing data 
Availability: I'm available on Friday + the weekend to begin analyzing the data 
ETA: Sunday

**Comment by hannahsgr** [comment]
Progress: Made a destination chart outlining how many people selected a given location on the IA per question. I think I can start modifying the IA based on the results. 
Blockers: Need to look up supplementary quant analysis methods  
Availability: Will be available on Friday and the weekend to do additional analysis 
ETA: Sunday

**Comment by lrchang2** [comment]
@hannahsgr please sharing your results with the team to get input as well, i think it would benefit everyone to hear what you're doing and others might have ideas for other quant analysis methods

**Comment by hannahsgr** [comment]
Progress: Ashley asked to join this issue and we are now working together. Ashley created a chart to begin analysis of the destination charting data to identify which tasks need further testing and to ideate changes to the IA. 
Blockers: None
Availability: I have 6 hours mostly on Thursday and Friday to work on this issue. I will begin analysis on Wednesday. 
ETA: Saturday

**Comment by Eevinjennings** [comment]
I will get caught up to speed this Friday. Still learning GitHub and finishing the end of this semester.

**Comment by Eevinjennings** [comment]
@hannahsgr @lrchang2 Please let me know what I should do next! (and also whether this is the right location to say/ask these kinds of things- still figuring this out!

**Comment by ashleyxz** [comment]
Progress: Discussed the findings and recommendations with Hannah. Co-created a report linked in the description. 
Blockers: None

**Comment by hannahsgr** [comment]
Progress: Met with Ashley and identified issues with the IA and ideated solutions. Will be meeting with Ashley and Eevin to review solutions tomorrow. 
Blockers: None
Availability: 6 hours
ETA: Friday
