### ISSUE TITLE
Plan for Planning Week [4-8 April]

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/access-the-data#144]
### Overview
The PMs and Team leads need to 

### Action Items

- [x] Set up a retrospective with team leads week of 28 March
- [x] Outline what needs to be accomplished during planning week
- [x] Set up AtD strategic workshop sessions with team leads for planning week
- [x] Prepare materials and agendas for AtD strategic workshops

**Comment by lrchang2** [comment]
@mxajPrice close out?
