### ISSUE TITLE
Website User Flows and Wireflows

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#145]
### Dependencies

- #191
- #192

### Overview
We need to develop the user flow of the website and align it with the project's user personas and user journey through the website to ensure that the website is designed and organized to support their journey. 

### Action Items
- [x] PHASE 1: #169
- [ ] PHASE 1: Audit and document current high-fi wireframes for sitemap and wireflows 
- [ ] PHASE 1: Define the what, why, how of the users objectives/goals within the website (that end in a call to action) and if they have barriers or require any an additional information to achieve the goal
- [ ] PHASE 1: Develop and diagram user flows within the website based on user goals for each persona
   - [ ] Determine entry points/traffic source to the website that align with user motivations and actions 
   - [ ] Breakdown and diagram user flows into task flows 
- [ ] PHASE 2: Update website's information architecture based on audit 
- [ ] PHASE 2: Align and document wireflows with task flows 
- [ ] PHASE 2: Update wireframe wireflows 

### Resources/Instructions
- #36 
- #90
- #27 
- #45 
- #90
- [Article - Personas, journey maps, sitemaps, and user flows — OH MY!](https://uxdesign.cc/personas-journey-maps-site-maps-and-user-flows-oh-my-e71d044b4bcb)
- [Wiki 1](https://github.com/hackforla/access-the-data/wiki/ATD-Research-Website-User-Flows-and-Wireflows)
- [Wiki 2](https://github.com/hackforla/access-the-data/wiki/ATD-Research-Plan-Assets_Website-User-Flows-and-Wireflows-(issue-145))

**TEMPLATE FOR PROJECT PROGRESS**

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by Eevinjennings** [comment]
@lrchang2 I accidentally converted the first action item into an issue and I'm not sure how to undo it 😅

**Comment by lrchang2** [comment]
@Eevinjennings no worries, ive deleted it

**Comment by Aparna1Gopal** [comment]
**Additional Resources**

https://github.com/hackforla/access-the-data/issues/80

**Comment by Aparna1Gopal** [comment]
- This Issue is distributed into Phases
- Further details provided in the Research Plan.

**Comment by Aparna1Gopal** [comment]
Progress: "What is the current status of your project? What have you completed and what is left to do?"
Was assigned to this issue recently. Currently working on making the connections and collecting resources from UX/UI leads and reviewing work already completed & available in the databases. 

Blockers: "Difficulties or errors encountered."
Newly assigned, so finding my way around and making certain I am managing to review all the resources available 

Availability: "How much time will you have this week to work on this issue?"
This Issue is distributed into Phases
Phase 1 : Familiarize self with project's historical work on personas [Phase 1_Website User Flows and Wireflows] #169
6 hours this week (excluding meetings) 

ETA: "When do you expect this issue to be completed?"
Next UXR meeting (May 17, 2022)

Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by Aparna1Gopal** [comment]
Overview

Phase 1 focusses on familiarizing oneself with the project's historical work on personas

Action Items

  Collect resources from UX/UI leads and review
  Review all databases related to ATD > GitHub, Google Drive, Figma, anything else..
  Collect Best Practices
  Review Best Practices
  Create simple Slide Deck with the primary information

**Comment by Aparna1Gopal** [comment]
Resource Library

Doing more UI (visual) competitive analysis + competitive flows + design recommendations
Previous work competed for ATD
https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=9%3A62

**Comment by Aparna1Gopal** [comment]
**TEMPLATE FOR PROJECT PROGRESS**

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by Aparna1Gopal** [comment]
**RESOURCE LIBRARY - BEST PRACTICES**

**Comment by Aparna1Gopal** [comment]
**REFERENCE MATERIALS - WORK COMPLETED WITHIN ATD**

**Comment by Aparna1Gopal** [comment]
****RESOURCE LIBRARY ---- RESEARCH PLAN**

**Comment by Aparna1Gopal** [comment]
PROJECT PROGRESS

Progress: "What is the current status of your project? What have you completed and what is left to do?"

Completed the following: 
- [ ] Research Plan 
- [ ] Identified resources pertaining to this issue and documented it under RESOURCE LIBRARY 
- [ ] Contacted the internal stakeholders [UX Designers, UX Writers, UX Researchers, Design and Research Leads of ATD] to collate all information and adjacent topics/resources related to this issue
- [ ] Contacted via Slack: Design and Research Leads to collate information 
- [ ] Contacted via video chat: UX Writers and UXR working on adjacent issues 
- [ ] Contacted via short Google Survey: UX Writer and UX Designers
- [ ] Collated all the information 
- [ ] Created and updated Wiki for this issue 

To complete: 
- [ ] Review collected Best Practices
- [ ] Identify appropriate methods to deploy next steps

Blockers: "Difficulties or errors encountered."
Nothing in particular. Just the time constraints and reaching out to the multiple internal stakeholders (UX Writers, Researchers and Designers) working on this issue 

Availability: "How much time will you have this week to work on this issue?"
6 hours 

ETA: "When do you expect this issue to be completed?"
Please refer Research Plan 

Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by Aparna1Gopal** [comment]
Progress: "What is the current status of your project? What have you completed and what is left to do?"

- [ ]   Review collected Best Practices
- [ ]   Identify appropriate methods to deploy next steps
- [ ]   Research Plan (Ongoing)
- [ ]   Create appropriate interview scripts for each method
- [ ]  Contacted UX Writers and Designers on the project. Conducting short internal stakeholder interviews to assess current status of design

Blockers: "Difficulties or errors encountered."
Coordinating times across different teams. Should be meeting with design team this week. 

Availability: "How much time will you have this week to work on this issue?"
6 hours 

ETA: "When do you expect this issue to be completed?"
Please refer Research Plan

Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by Aparna1Gopal** [comment]
**Notes**

**Access the Data Figma Files** 

https://www.figma.com/proto/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=4665%3A19504&scaling=contain&page-id=2%3A16&starting-point-node-id=4665%3A19504&show-proto-sidebar=1

https://www.figma.com/files/project/29582752/Access-The-Data?fuid=1100942504337383164

Figma Prototype
https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A16

https://www.figma.com/proto/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=4328%3A18544&scaling=scale-down&page-id=2%3A14&starting-point-node-id=4328%3A18544

**Comment by Aparna1Gopal** [comment]
Progress: 
Progress on this issue via https://github.com/hackforla/access-the-data/issues/191

**Comment by Aparna1Gopal** [comment]
Progress: "What is the current status of your project? What have you completed and what is left to do?"

Working on the following related Issues: (Resources and progress are interconnected) 
https://github.com/hackforla/access-the-data/issues/191
https://github.com/hackforla/access-the-data/issues/192
Website User Flows and Wireflows #145
Currently set up GitHub issues and relevant resources to start on the Research Plan and proceed. 

Blockers: "Difficulties or errors encountered."
None, as have met with PMs last week to streamline steps related to the product pivot 

Availability: "How much time will you have this week to work on this issue?"
6-10 hours
ETA: "When do you expect this issue to be completed?"
Ongoing
Plan on completing Research Plans for all three above issues this week and create the survey design draft copy for #191

Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by Aparna1Gopal** [comment]
**Notes:** 

- The product (ATD website) is currently undergoing a redesign with the incorporation of CKAN type Data Cataloguing. Design team is updating the information architecture and low-fi/hi-fi wireframes on the website.

- The user personas are also being developed further into a second iteration: the two personas being data expert and data novice (also called community activist) 

- This issue is on hold as the design team updates the information architecture and wireframes of the website.

- It is best to work on this issue once there has been some more progress and detailing with the website redesign and user personas. Hence, unassigning from this issue. 

**_Additionally, it might be a good idea to explore this Issue from the point of view of Service Design. 
Service design has standard benchmarks and templates to explore varied user types and touchpoints to create service design blueprints. This will work out well for the goals of this issue._**

**Comment by mxajPrice** [comment]
This was created for the educational modules, which we are no longer doing.
