### ISSUE TITLE
Review Workshop Slides

### ISSUE THREAD

**Issue by bradyse** [hackforla/access-the-data#148]
### Overview
The purpose of this issue is to conduct a review of the Workshop slides for clarity and educational information, especially for an audience unfamiliar with data. Once the review is complete, data analysts on the project will be asked to provide answers to questions regarding the information presented in the workshop slides.

### Action Items

- [x] Review Workshop slides and provide notes on initial impressions
- [x] Draft a [summary of review](https://docs.google.com/document/d/1fLUCQcMT30MLmvw3nLSVXp9p0iiOF0ZSKftEDaBtSOY/edit?usp=sharing)
- [x] Draft questions for data analysts
- [x] Meet with data analysts on clarifying questions

### Resources/Instructions

- Workshop slides: [v2. Workshop 1: 311Data in Action](https://docs.google.com/presentation/d/1mlYV3ELIGxeoxvKBAjjukZ51uTbl6daB5hcAIp9arDI/edit#slide=id.g10992d975c3_0_190)
- Summary of Review: [v2. Workshop 1 - Slide Review](https://docs.google.com/document/d/1fLUCQcMT30MLmvw3nLSVXp9p0iiOF0ZSKftEDaBtSOY/edit?usp=sharing)

**Comment by bradyse** [comment]
**Progress**: Slide Review document is finished and located here: [https://docs.google.com/document/d/1fLUCQcMT30MLmvw3nLSVXp9p0iiOF0ZSKftEDaBtSOY/edit?usp=sharing](https://docs.google.com/document/d/1fLUCQcMT30MLmvw3nLSVXp9p0iiOF0ZSKftEDaBtSOY/edit?usp=sharing)
**Blockers**: None
**Availability**: I'm available during the evening hours this week.
**ETA**: I plan on meeting with data analysts Monday April 18 during Zoom call to walk through slides with @scho-git and @lrchang2 . Once this meeting is over, this issue will be complete.

**Comment by bradyse** [comment]
**Progress**: Finished meeting with @scho-git and rest of Workshop team about slides. Bonnie updated my [review document ](https://docs.google.com/document/d/1fLUCQcMT30MLmvw3nLSVXp9p0iiOF0ZSKftEDaBtSOY/edit?usp=sharing)with answers to the questions.
**Blockers**: None
**Availability**: I'm available this week for additional issues.
**ETA**: Finished as of 4/18/2022

**Comment by lrchang2** [comment]
thank you for your work on this @bradyse, closing out issue
