### ISSUE TITLE
Evaluating the Content Among Wiki, Website, and Workshop Slides

### ISSUE THREAD

**Issue by steffiekim** [hackforla/access-the-data#149]
### Overview
We need to check whether the information on three different places (Github wiki, website, and workshop slides) is consistent.

### Action Items

- [x] Connect with @katelyntn to check on how website wire flow is going
- [x] Connect with data analysts (@MalakH21 & @scho-git) to check on the slides content 
- [x] Collaborate with @hannahsgr to understand the content on the Github wiki
- [ ] Document an overall info architecture of wiki, website, and workshop

### Resources/Instructions
<< Evaluation Outcome >>
[Evaluation Report](https://docs.google.com/document/d/1QK69gmIsQzzbkptNjwJc_vuOSOPe2Pz7bcJ67QkHddY/edit?usp=sharing)

<< Evaluation Materials >>
[311Data Slide Outline](https://docs.google.com/spreadsheets/d/1k8DvQ0wiiT3YJVliscCXOtXAiHx1yJDhPvjzYHZpOLQ/edit#gid=0)
[Workshop slides](https://docs.google.com/presentation/d/1mlYV3ELIGxeoxvKBAjjukZ51uTbl6daB5hcAIp9arDI/edit#slide=id.p)
[ATD Website - Figma](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A16)
[ATD Wiki](https://github.com/hackforla/access-the-data/wiki)

**Comment by steffiekim** [comment]
- Identified and evaluated content for Github wiki.
- Created [a document](https://docs.google.com/document/d/1QK69gmIsQzzbkptNjwJc_vuOSOPe2Pz7bcJ67QkHddY/edit?usp=sharing) for evaluation

**Comment by lrchang2** [comment]
@steffiekim Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by steffiekim** [comment]
@lrchang2 

Progress: "What is the current status of your project? What have you completed and what is left to do?"
[Things that are done]
- I have completed evaluating the github wiki content.
[Things to do]
- Evaluate website content  
- Evaluate workshop materials content

Blockers: "Difficulties or errors encountered."
-Website flow is not ready for review
-Workshop materials are not ready for review

Availability: "How much time will you have this week to work on this issue?"
-I can devote 2-3 hours for this issue, but I'm not sure when the other two (website and workshop) will be ready for review.

ETA: "When do you expect this issue to be completed?"
- I need to check with the designer and the data analysts. Once their contents are complete, I can finish auditing within a week.

Pictures: "Add any pictures of the visual changes made to the site so far."
-There's no visual change.
