### ISSUE TITLE
Persona 1 Recruitment - Contact Community Leaders

### ISSUE THREAD

**Issue by jjaylo** [hackforla/access-the-data#153]
### Overview
Contact LA Community Leaders to set up and conduct informational interviews

### Action Items
- [x] Contact 5 community leaders from Recruitment List via LinkedIn
- [x] Follow up with 5 community leaders from Recruitment List via email
- [x] Determine informational interview questions
- [x] Get access to Hack for LA email

### Resources/Instructions
[ATD Persona 1 Recruitment Strategy](https://docs.google.com/document/d/1AJtclpyQv8PLpr00IbZFZdXcSCCf4VbdHsh3JR6oEDU/edit) 
[ATD - Community Leaders Contact List](https://docs.google.com/spreadsheets/d/1lE-0M2Fc9Njf71aG9wrlE5gXhyWh_hV1AnXEtKnu558/edit#gid=0)
[ATD Persona 1 Screener Survey Questions](https://docs.google.com/document/d/1PTEBRiPYWQarMyXMwCxGZy_OqW4qu5MSGfqCX7kZSxM/edit?usp=sharing)

**Comment by lrchang2** [comment]
@jjaylo do you still need help with email access?

**Comment by kimberly-tellez** [comment]
Update: 15 people have been contacted via LinkedIn or Email, Joyce will have Informational Meeting tomorrow, 4/20/2022. 
Next steps: I need to finalize the screener survey questions and survey, then I will start sending them out in community activist networks. I will continue doing the Informational Interview outreach, but that is going slow so I am moving forward with a 2 pronged approach of continuing outreach while also sending out the survey to find folks for User Interviews.
[ATD Persona 1 Screener Survey Questions](https://docs.google.com/document/d/1PTEBRiPYWQarMyXMwCxGZy_OqW4qu5MSGfqCX7kZSxM/edit?usp=sharing)

**Comment by jjaylo** [comment]
> @jjaylo do you still need help with email access?

@lrchang2 I apologize for the delayed response. I have gotten access to the email as of this evening.

**Comment by lrchang2** [comment]
issue done
