### ISSUE TITLE
Research Plan: Data Enthusiast Persona

### ISSUE THREAD

**Issue by steffiekim** [hackforla/access-the-data#154]
### Overview
We need to create a research plan for understanding data enthusiasts—people who are interested in learning about data but do not have the knowledge yet

### Action Items

_1) Identifying Persona_
- [x] Familiarize with targeted persona in #90, [User Persona in Mini Presentation](https://docs.google.com/presentation/d/1C8GP1kzx_iimIYVSnfQTZR-8EEuyPP7Td6iTmywZIQk/edit#slide=id.gf6fed8a0bd_0_0) and [wiki page of prior research](https://github.com/hackforla/access-the-data/wiki/Prior-and-Ongoing-Research)
- [x] Define who "Data Enthusiasts" are

_2) Research Plan_
- [x] Read [Guide to Research Plan Documentation](https://docs.google.com/document/d/1ovSBNVkuizZD2EMOE2w522_x-sOAzQBEheMqfPWmQKk/edit#heading=h.c8tc614ce3iu) and [UX/UI research plan issue guide](https://github.com/hackforla/UI-UX/issues/120) 
- [x] Create research plan draft
- [x] Review with @lrchang2 and edit based on feedback
- [x] Review [Persona1 research plan](https://docs.google.com/document/d/1yayDQm-WFxm63PKHfuXBRQJSAAyU2f1xFPt3n1dBjpg/edit) to check there's no overlap

_3) Survey Design_
- [x] Make survey questions
- [ ] Review with @lrchang2 and edit based on feedback
- [x] Draft language for posting on social media
- [ ] Review social media language with UXR team and edit based on feedback
- [ ] Post on social media/online commnuties

_4) Github Wiki_
- [x] Update [ATD Research Plans](https://github.com/hackforla/access-the-data/wiki/ATD-Team-Research-Plans)

_5) Interview Script_
- [ ] Draft interview questions

### Resources/Instructions
**How-To's**
[NN Group's Research Plan Guide](https://www.nngroup.com/articles/pm-research-plan/)
[Book: Surveys That Work](https://rosenfeldmedia.com/books/surveys-that-work/)
[Hack for LA Research Plan Template
](https://github.com/hackforla/UI-UX/issues/120)[UX Survey Guide](https://docs.google.com/document/d/1j94pkoyKP4ysf5fL5yIYeTV8G12o5Uic/edit#heading=h.qoxj8rvjapzr)
[UX Survey Questions 60 Examples](https://surveysparrow.com/blog/user-experience-survey-questions/)

**Previous Research Plans for Reference**
[ATD UX Research Plan](https://docs.google.com/document/d/1KLpwj5sYh8un7kvGeixg5VkSW1mR2OwhybIKbQFjh9Q/edit)
[Persona 1 Research Plan](https://docs.google.com/document/d/1yayDQm-WFxm63PKHfuXBRQJSAAyU2f1xFPt3n1dBjpg/edit)
[Persona 1 Screener Survey](https://docs.google.com/document/d/1PTEBRiPYWQarMyXMwCxGZy_OqW4qu5MSGfqCX7kZSxM/edit)

**Deliverables**
[Redefining Personas](https://docs.google.com/presentation/d/16bvi9JqPdgcwQXplbuo64ZHLfRbV1LonTrXbb9tzIoM/edit?usp=sharing)
[Data Enthusiast Persona Research Plan (Survey)](https://docs.google.com/document/d/1zwl3NNHpMZ5vFY24k4AU463b_HGIbtr-y3fyJ1G7mjM/edit?usp=sharing)
[Data Enthusiast Persona Survey Questionnaire](https://docs.google.com/document/d/1c90PcsDjI3UCYdaGh-aHZQ6KjVrDvy1rGxkcXSMAGLE/edit?usp=sharing)
[Social Media Recruitment Language](https://docs.google.com/document/d/1QYWgl0s3pPKBnwEcTrkGbVXtRyGB4fDvJ3K8gjAHT7A/edit?usp=sharing)

**Comment by steffiekim** [comment]
Worked on the first action item: Familiarize with targeted persona in #90, [User Persona in Mini Presentation](https://docs.google.com/presentation/d/1C8GP1kzx_iimIYVSnfQTZR-8EEuyPP7Td6iTmywZIQk/edit#slide=id.gf6fed8a0bd_0_0) and [wiki page of prior research](https://github.com/hackforla/access-the-data/wiki/Prior-and-Ongoing-Research)

However, I had a difficult time identifying who the "data enthusiasts" are (which is my target user) based on the existing documents. Here are the problems I encountered:

1. Different names for the same persona?
- Is the "Prospective User" on slide #3 in [User Persona in Mini Presentation](https://docs.google.com/presentation/d/1C8GP1kzx_iimIYVSnfQTZR-8EEuyPP7Td6iTmywZIQk/edit#slide=id.gf6fed8a0bd_0_0) the same as the "General User" in #90?

2. Overlapping categories/Uncertain definitions
- In [Prior and Ongoing Research](https://github.com/hackforla/access-the-data/wiki/Prior-and-Ongoing-Research), there are 3 categories in text and 2 categories in the graphical representation. In [User Persona in Mini Presentation](https://docs.google.com/presentation/d/1C8GP1kzx_iimIYVSnfQTZR-8EEuyPP7Td6iTmywZIQk/edit#slide=id.gf6fed8a0bd_0_0), there are 4 categories.
- Some definitions seem to be overlapping

3. Missing persona (Data Expert)
- The [User Persona in Mini Presentation](https://docs.google.com/presentation/d/1C8GP1kzx_iimIYVSnfQTZR-8EEuyPP7Td6iTmywZIQk/edit#slide=id.gf6fed8a0bd_0_0), #90, and [Prior and Ongoing Research](https://github.com/hackforla/access-the-data/wiki/Prior-and-Ongoing-Research) do not list "Data Expert" as a persona, but I know those data experts are one of our target users. What is the definition of data experts?

Based on these problems, the questions are:

1. Personas seem to be redefined. How can we do this?
2. Who exactly are "data enthusiasts" that I need to research?

**Deliverable**
I made a presentation about this problem here: [Redefining Personas](https://docs.google.com/presentation/d/16bvi9JqPdgcwQXplbuo64ZHLfRbV1LonTrXbb9tzIoM/edit?usp=sharing)

**Comment by LouismChan** [comment]
Hi Steffie, Great to join this team.  After looking over the existing slides, it looks like Data Enthusiasts are the community activists and prospective users who are interested in learning about/using data, may or may not be to the point of becoming Data Amateurs themselves.  So we need to find out who they are and what they want to do.  Maybe also need to find out why some community activists are not data enthusiasts - not interested in learning about/using data.

**Comment by steffiekim** [comment]
@LouismChan Thank you for your comment! I agree that it's important to find out why someone would not want to do it as well as why someone would want to do it.

**Comment by steffiekim** [comment]
1. Met with @LouismChan to go over where the current project is going and what this is about.

2. Met with @kimberly-tellez, @joyceeyang , @jjaylo, @Aparna1Gopal and @LouismChan and decided that the current issue will focus more on surveying the "data experience/expert" part while @kimberly-tellez's project focuses more on investigating the "interest in community activism."

Based on the discussion, I updated the slide #4 in [Redefining Personas](https://docs.google.com/presentation/d/16bvi9JqPdgcwQXplbuo64ZHLfRbV1LonTrXbb9tzIoM/edit?usp=sharing):
- We recognized that the current categorization of personas is not the final version. It could change based on further research.
- We agreed upon the fact that data experts/amateurs and community activists can be continuous personas.
- Defined "Data Enthusiasts" as data amateurs, community activists with less knowledge in data, and prospective users who are interested in learning more but don't know where the resources are.

Here is an updated image of the categorization of personas:
![Personas_0421](https://user-images.githubusercontent.com/42043303/164568728-3589f00f-9a3d-4a73-bc1f-a74988d99318.png)

**Comment by LouismChan** [comment]
Very interesting diagram.  Maybe also use it to think dynamically: Data Enthusiasts are people who want to move up by learning more about data?  Maybe moving to the Northeast quadrant?

**Comment by lrchang2** [comment]
@steffiekim agree with Louis, the chart is great. The only thing that I would like to point out is that becoming data literate has a bit more nuisance in our context. Becoming data literate includes: 
1. gaining knowledge about data and analytics 
2. knowing what (open source/public) resources around  data and tools are available
3. knowing how to apply the knowledge and tools in the context of community change

**Comment by LouismChan** [comment]
Seems that a Data Expert/Amateur (Sr. Director, Research & Data Analysis at Advancement Project (CA)) doesn't know much about 311 Data: https://docs.google.com/document/d/1SyqoEeXFAyb3rfMfe3wMRdcVoVMtDgTAzx2ezQT5mKQ/edit

Below is just some background info on 311 data: 
https://www.civisanalytics.com/blog/how-los-angeles-taps-its-311-call-data-to-bring-more-power-to-the-people-and-build-more-trust-with-city-hall/
https://www.wired.com/story/chicago-311-huge-win-for-public-works/
https://www.wired.com/2010/11/ff_311_new_york/

**Comment by steffiekim** [comment]
Created a research plan draft: [Data Enthusiast Persona Research Plan (Survey)](https://docs.google.com/document/d/1zwl3NNHpMZ5vFY24k4AU463b_HGIbtr-y3fyJ1G7mjM/edit?usp=sharing)

**Comment by steffiekim** [comment]
@lrchang2 reviewed [Data Enthusiast Persona Research Plan (Survey)](https://docs.google.com/document/d/1zwl3NNHpMZ5vFY24k4AU463b_HGIbtr-y3fyJ1G7mjM/edit?usp=sharing). I and @LouismChan edited the document based on the feedback. We replied to the comments and resolved the ones that are done. Comments history can be seen in the upper right corner of Google Docs for future references.

**Comment by steffiekim** [comment]
Created [Data Enthusiast Persona Survey Questionnaire](https://docs.google.com/document/d/1c90PcsDjI3UCYdaGh-aHZQ6KjVrDvy1rGxkcXSMAGLE/edit?usp=sharing) and started working on crafting questions

**Comment by steffiekim** [comment]
Complete the first draft of [Data Enthusiast Persona Survey Questionnaire](https://docs.google.com/document/d/1c90PcsDjI3UCYdaGh-aHZQ6KjVrDvy1rGxkcXSMAGLE/edit?usp=sharing)

**Comment by steffiekim** [comment]
1.  Edited [Data Enthusiast Persona Survey Questionnaire](https://docs.google.com/document/d/1c90PcsDjI3UCYdaGh-aHZQ6KjVrDvy1rGxkcXSMAGLE/edit?usp=sharing) based on @lrchang2's feedback. [One more comment left to address]
2. Created [Social Media Recruitment Language](https://docs.google.com/document/d/1QYWgl0s3pPKBnwEcTrkGbVXtRyGB4fDvJ3K8gjAHT7A/edit?usp=sharing)

**Comment by steffiekim** [comment]
Backlogged for now
