### ISSUE TITLE
Template for Internal Presentations

### ISSUE THREAD

**Issue by joycekyang** [hackforla/access-the-data#157]
### Overview
Template for Internal Presentations to use during meetings

### Action Items
[ ] Add a slide for **Highlights**, have replaceable text
[ ] Add a slide for **Highlights**, have replaceable text

### Resources/Instructions
[Template Deck Figma File](https://www.figma.com/file/8qlMlrbDMYFqSfDiWlMwzQ/Internal-Meeting-Template?node-id=0%3A1 
)

**Comment by lrchang2** [comment]
@joycekyang issue needs more information and a role and size tag to be moved to the prioritized backlog. if you are still doing this work, please add more details, thanks!

**Comment by joycekyang** [comment]
Hi Lucy,

How do we close issues? If possible can you close this issue?

Joyce

**Comment by lrchang2** [comment]
closing issue
