### ISSUE TITLE
Informational Interviews

### ISSUE THREAD

**Issue by joycekyang** [hackforla/access-the-data#158]
### Overview
Template used for Informational Interviews (script/notes) with data experts (and data amateurs).

### Action Items
[ ] Attach example script for informational interview
[ ] Attach example notes during informational interview
[ ] Attach timeline (?)
[ ] Next steps: There is a need for an Informational website to show potential partners

### Resources/Instructions
**(1.) Script**
1. Tell me about the Advancement Project and what you specifically do?
2. How does Advancement Project support the projects that you mentioned? 
3. What type of data do you use? 
4. How do you use the data? 
5. Once you have information (e.g., enrollment numbers are dropping), are there any policies that you use to change the data trajectories? 
6. Focus on open source data, and increase data literacy, you work with this network with people in LA and we are trying to reach out to folks in LA, who should we be speaking with? Referrals?  
7. Have you heard of 311 Data as a Hack for LA project? 
8. Thank you for your time, I will follow up with an email. Are you open to taking our screener survey? It is to help us learn from community members like you.

**2.) [Interview Notes]**(https://docs.google.com/document/d/1SyqoEeXFAyb3rfMfe3wMRdcVoVMtDgTAzx2ezQT5mKQ/edit?usp=sharing)

**Comment by joycekyang** [comment]
Hi Lucy,

We have stopped doing informational interviews for the time being.

Joyce

**Comment by lrchang2** [comment]
closing issue
