### ISSUE TITLE
Explore Tableau Public & Floursih

### ISSUE THREAD

**Issue by snooravi** [hackforla/access-the-data#16]
### Overview
- Reviewing existing visualizations in the gallery
- Integration and data solution & maintenance 

### Action Items
List of visualization contenders coming from Tableau Public gallery
Understanding of how data feeds into Tableau Public visuals & how to maintain "freshness" of the data.

### Resources/Instructions
[Tableau Public Gallery](https://public.tableau.com/en-us/gallery/?tab=viz-of-the-day&type=viz-of-the-day)
[Flourish](https://flourish.studio/)

**Comment by dplem** [comment]
First draft of Tableau dashboards: https://public.tableau.com/profile/derekplemons#!/vizhome/LosAngelesDataResourcesDashboard/LinksDashboard?publish=yes

**Comment by snooravi** [comment]
Action: We chose Tableau Public

**Comment by snooravi** [comment]
Reviewed Tableau Public and Florish, landed on usage of Tableau for visualization purposes.
