### ISSUE TITLE
Update Project information

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/access-the-data#162]
### Overview
We need to update and uniform our information and logos about AtD.

### Dependency
[#4566](https://github.com/hackforla/website/issues/4566)

### Action Items

- [x] Update [GitHub mainpage](https://github.com/hackforla/access-the-data)
- [x] Update [onesheet/overview](https://docs.google.com/document/d/1bWWhI0Zuas22sdEEDC6sSuRYZ3gXiBZ8LuyNUmD_s7o/edit?usp=sharing) and upload [here](https://github.com/hackforla/product-management/tree/master/project-one-sheets)
- [x] Archive [onesheet doc](https://docs.google.com/document/d/1bWWhI0Zuas22sdEEDC6sSuRYZ3gXiBZ8LuyNUmD_s7o/edit?usp=sharing) 
- [x] Archive outdated docs on the drive to avoid confusion
- [x] #189
- [x] #190
- [x] [AtD H4LA site](https://www.hackforla.org/projects/access-the-data), make a request for updates [here](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small%2C+size%3A+0.5pt%2C+time+sensitive&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D) with the Websites team
- [x] ...other locations to be listed...

### Resources/Instructions

[Guide to make One Sheet for project](https://github.com/hackforla/guides/issues/40)

**Comment by mxajPrice** [comment]
@lrchang2 will be retiring the onesheet per Slack 27 April.

**Comment by lrchang2** [comment]
one sheet has the archived

**Comment by mxajPrice** [comment]
An issue has been submitted to VRMS:
[Update Project Profile: Access the Data #3153](https://github.com/hackforla/website/issues/3153)
I will check this off when this is completed.

**Comment by mxajPrice** [comment]
Re: GitHub mainpage

A [push request with updates](https://github.com/hackforla/access-the-data/pull/173/files) is awaiting review from @lrchang2.  The calendar already needs to be updated.  I am not sure what we need to do to embed the new logo or the new calendar.

**Comment by mxajPrice** [comment]
[One sheet](https://docs.google.com/document/d/17yzHv1Jx5Vf_QAHtgBZ0slU3no9BXneEB8GJscyKlpE/edit) has been updated.

**Comment by mxajPrice** [comment]
Still waiting on VRMS to update HfLA page.  Need to plan a working session with the leads to clean the wiki.

**Comment by mxajPrice** [comment]
This project is currently dependent on:

- [ ] VRMS updating the [site][https://github.com/hackforla/website/issues/3153]
- [ ] #189 
- [ ] #190

**Comment by mxajPrice** [comment]
Created [#3885](https://github.com/hackforla/website/issues/3885) in Websites repo to remove Mariana from the [AtD HfLA profile page](https://www.hackforla.org/projects/access-the-data) and update the link to our [current one sheet](https://drive.google.com/drive/u/0/folders/1WtJYun_pUzc7lwN_WpGP4zIHz3IkOlvB).

**Comment by lrchang2** [comment]
need to update "values" section to align with the current version of the project. the copy currently still reflects an older version 
![image](https://user-images.githubusercontent.com/10827101/218878948-34e2e341-d48a-4401-905d-e2bfadfe2cb2.png)

**Comment by mxajPrice** [comment]
Website issue [#4566](https://github.com/hackforla/website/issues/4566) was created to update members on HfLA page.

**Comment by mxajPrice** [comment]
Updates complete.
