### ISSUE TITLE
Research Plan: Data Expert Persona 

### ISSUE THREAD

**Issue by LouismChan** [hackforla/access-the-data#163]
### **Overview**
We need to create a research plan for talking to data experts to understand how they would like to use their expertise to give back to their community.

### **Action Items**

- [x]  Familiarize with targeted persona in 
    - [x] #90 
    - [x] [User Persona in Mini Presentation](https://docs.google.com/presentation/d/1C8GP1kzx_iimIYVSnfQTZR-8EEuyPP7Td6iTmywZIQk/edit#slide=id.gf6fed8a0bd_0_0)
    - [x] [wiki page of prior research](https://github.com/hackforla/access-the-data/wiki/Prior-and-Ongoing-Research)
    - [x]  #127 
    - [x] #154
- [x] Read [Guide: How to - Write a Research Plan](https://docs.google.com/document/d/1ovSBNVkuizZD2EMOE2w522_x-sOAzQBEheMqfPWmQKk/edit#heading=h.c8tc614ce3iu) and [Create a Guide/Template: Research Plan#120](https://github.com/hackforla/UI-UX/issues/120)
- [x] Keep up with current recruitment activities: #147, #153, 
- [x] Create research plan draft
- [x] Create user screener survey
- [x] Review with PM (@lrchang2 ) and edit based on feedback
- [x] Review with UX research team (@ExperimentsInHonesty) and edit draft based on feedback
- [x] Send out screener survey
  
### **Resources/Instructions**

- [UX Research Protocol #75](https://github.com/hackforla/access-the-data/issues/75)
- [Access the Data - Research Plan for Website](https://docs.google.com/document/d/1HGCrxVwHT-O72HnyDLpfJ_cphFm_t6xBg2CEfbzfRsE/edit)
- [Persona 1 Research Plan](https://docs.google.com/document/d/1yayDQm-WFxm63PKHfuXBRQJSAAyU2f1xFPt3n1dBjpg/edit)
- [Persona 1 Screener Survey](https://docs.google.com/document/d/1PTEBRiPYWQarMyXMwCxGZy_OqW4qu5MSGfqCX7kZSxM/edit)
- [Data Enthusiast Persona Research Plan (Survey)](https://docs.google.com/document/d/1zwl3NNHpMZ5vFY24k4AU463b_HGIbtr-y3fyJ1G7mjM/edit?usp=sharing)
- [Data Expert Persona Research Plan draft](https://docs.google.com/document/d/1YINoBN6qJoKNi85yjUJDJmhR_4qlcXWyVqnIjqSMzoI/edit) 
- [Data Expert Persona Screener Survey draft](https://docs.google.com/document/d/1qkKsD78xLcQ-iOE2uctssOInJS87HUCetleawxeiB9k/edit) & [Data Expert Screener Survey Form](https://docs.google.com/forms/d/1Y5EVtnXi3lCpklEnU1IMAxl9FyFKGnwmaJTyqcplK1A/edit).
- #176
- #185

**Comment by LouismChan** [comment]
[@Joyce Yang’s user interview](https://docs.google.com/document/d/1SyqoEeXFAyb3rfMfe3wMRdcVoVMtDgTAzx2ezQT5mKQ/edit) is a very useful user/field research piece that helps us understand a possible data expert user better.  He is a Senior Director of Research & Data Analysis who oversees data analysis and social justice research at a Community Activist organization.   But he doesn't know very much about 311 Data.  So he is an example of a possible target data expert user of 311 Data workshops.  It is people like him who, by understanding better how to use 311 data, can help and motivate others to use 311 data to better their community.

Also see this [Civis article](https://www.civisanalytics.com/blog/how-los-angeles-taps-its-311-call-data-to-bring-more-power-to-the-people-and-build-more-trust-with-city-hall/) about current efforts in LA on "expanding its [data literacy program](https://know-your-community-lahub.hub.arcgis.com/pages/data-literacy) by building out models instructing community members on how to make their own data maps, how to filter 311 data in the Open Data Portal, and even how to create their own web apps."

**Comment by LouismChan** [comment]
@Aparna1Gopal @kimberly-tellez @joyceeyang @jjaylo @lrchang2 @steffiekim This [LA Data Platform group](https://datadriventechnologies.org/ladataplatform-usergroup/) and [here](https://www.meetup.com/los-angeles-data-platform/) may be a possible recruitment target.

**Comment by LouismChan** [comment]
Working on this [Research Plan draft.](https://docs.google.com/document/d/1YINoBN6qJoKNi85yjUJDJmhR_4qlcXWyVqnIjqSMzoI/edit)

**Comment by LouismChan** [comment]
@lrchang2 Sent out [Data Expert Screener Survey](https://docs.google.com/forms/d/1Y5EVtnXi3lCpklEnU1IMAxl9FyFKGnwmaJTyqcplK1A/edit) to the Hack For LA slack data science channel and the [LA Data Platform group](https://datadriventechnologies.org/ladataplatform-usergroup/).  Already got back a couple of positive responses.

Gave @joyceeyang a copy of the screener survey to send out.

Contacted @akhaleghi about going on the Thursday evening data science meeting to ask people to fill out survey.

**Comment by lrchang2** [comment]
exciting! great work @LouismChan. look forward to seeing next steps

**Comment by LouismChan** [comment]
Steve Rezhener [@SteveRezhener](https://twitter.com/SteveRezhener) from [LA Data Platform group](https://datadriventechnologies.org/ladataplatform-usergroup/) responded and agreed to do a social media post of the screener survey.
