### ISSUE TITLE
A/B Testing Information Architecture Labels 

### ISSUE THREAD

**Issue by hannahsgr** [hackforla/access-the-data#164]
### Overview
A/B test the labels of the information architecture of the website to identify which labels people would most commonly look under to find information. 

### Action Items

- [x] Create an A/B test survey 
- [x] Administer the survey 
- [x] Analyze the results  
- [x] Update the information architecture 

### Resources/Instructions
https://github.com/hackforla/access-the-data/wiki
[IA Tree Test Research Plan](https://docs.google.com/document/d/1oY6cs4Qp3m4e96cta7417Y5H-wM6U3yadb3TG1Eaqvg/edit)
[Figma Site map](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/?node-id=2%3A7)
[Figma IA](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A9)
[ATD IA Tree Test Research Report](https://docs.google.com/document/d/1KuT9qGVelrBj5ecqJnJkSlS-xRuzOnKhnYAqT77_ctk/edit?usp=sharing)
[ATD Sitemap](https://docs.google.com/spreadsheets/d/1BV3TJ-tr2QPjij0IUXxTShtnHgDhAlkQAKIUELXAmWA/edit#gid=0)
[Tree Test Report](https://docs.google.com/document/d/1KuT9qGVelrBj5ecqJnJkSlS-xRuzOnKhnYAqT77_ctk/edit)

**Comment by hannahsgr** [comment]
Progress: Created and administered survey. I will finalize analysis on Friday. I currently have 14 respondents and the data shows clear trends/"winners."  
Blockers: None
Availability: 6 hours
ETA: Friday

**Comment by lrchang2** [comment]
@hannahsgr are you still doing a/b testing for the info architecture or has this been pivoted to usability testing? if you are still working on this, please provide update, thanks!

**Comment by lrchang2** [comment]
@hannahsgr Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by hannahsgr** [comment]
This issue is complete. I will close.
