### ISSUE TITLE
Usability Test: Wiki's Information Architecture 

### ISSUE THREAD

**Issue by hannahsgr** [hackforla/access-the-data#168]
### Overview
Do a moderated usability tree test on the revised information architecture on a small group of people (4-6) to see how people navigate the site and find information.  The purpose of this usability test is to catch any problems people may encounter before launching another tree test to the HfLA community. 

### Action Items

- [ ] Create a 1-1 usability testing script 
- [ ] Create a tree test 
- [ ] Recruit participants 
- [ ] Run study 
- [ ] Analyze findings 
- [ ] Revise the IA based on findings 

### Resources/Instructions
https://github.com/hackforla/access-the-data/wiki
[IA Tree Test Research Plan](https://docs.google.com/document/d/1oY6cs4Qp3m4e96cta7417Y5H-wM6U3yadb3TG1Eaqvg/edit)
[Figma Site map](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/?node-id=2%3A7)
[Figma IA](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A9)
[ATD IA Tree Test Research Report](https://docs.google.com/document/d/1KuT9qGVelrBj5ecqJnJkSlS-xRuzOnKhnYAqT77_ctk/edit?usp=sharing)
[ATD Sitemap](https://docs.google.com/spreadsheets/d/1BV3TJ-tr2QPjij0IUXxTShtnHgDhAlkQAKIUELXAmWA/edit#gid=0)
[Tree Test Report](https://docs.google.com/document/d/1KuT9qGVelrBj5ecqJnJkSlS-xRuzOnKhnYAqT77_ctk/edit))

**Comment by lrchang2** [comment]
@hannahsgr how is this different from #164 and is it needed?

**Comment by lrchang2** [comment]
@hannahsgr Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by hannahsgr** [comment]
This issue is on hold as the design team updates the information architecture on the website.
