### ISSUE TITLE
Ecosystem Map Requirements Gathering

### ISSUE THREAD

**Issue by snooravi** [hackforla/access-the-data#17]
### Action Items
We need the the following:

- [ ] collection of the ecosystem map ([Data Resources](https://public.tableau.com/app/profile/derekplemons/viz/LosAngelesDataResourcesDashboard/LinksDashboard))
   - [ ] #35
   - [ ] the descriptions of the various organizations that play into the ecosystem 
- [ ] workshop content (see [document ](https://docs.google.com/document/d/1j2kDVi_brwA8vlmIHRR9yrbndWM-Z72A9-sMt_X52g0/edit) #19 #28 
- [ ] short form videos and other instructional videos (some which will be covered in workshop content and other that will be handy links kind of content)
- [ ] design elements (color scheme, font, etc.) #22 

### Resources
[la data sources workbook ](https://docs.google.com/spreadsheets/d/1JKMw4BT-i4gUC73lRXxI5g4yWOxhQ5OOAhG58Ch1LqY/edit#gid=1370034216)
[First draft of Tableau dashboards](https://public.tableau.com/profile/derekplemons#!/vizhome/LosAngelesDataResourcesDashboard/LinksDashboard?publish=yes)

**Comment by snooravi** [comment]
First draft of Tableau dashboards: https://public.tableau.com/profile/derekplemons#!/vizhome/LosAngelesDataResourcesDashboard/LinksDashboard?publish=yes

**Comment by snooravi** [comment]
@sherelyn-saceda @ujunwaa Any update on this issue? Please update this issue with your progress or any blockers before tomorrow's meeting. Thanks!

**Comment by ExperimentsInHonesty** [comment]
find data, where are LA's data sets and where are the sites that use them
read data, which means understanding what data is and the aspects of the world it represents.
work with data, including creating, acquiring, cleaning, and managing it.
analyze data, which involves filtering, sorting, aggregating, comparing, and performing other analytic operations on it.
argue with data, which means using data to support a larger narrative that is intended to communicate some message or story to a particular audience.

**Comment by ExperimentsInHonesty** [comment]
Types of Resources - as dictated by Jeremy and reinterpreted by Bonnie
Find LA data: where are LA's data sets
Sites that visualize LA data: where are the sites that use la data
Reading data: which means understanding what data is and the aspects of the world it represents.
Working with data: including creating, acquiring, cleaning, and managing it.
Analyzing data: which involves filtering, sorting, aggregating, comparing, and performing other analytic operations on it.
Argue with data, which means using data to support a larger narrative that is intended to communicate some message or story to a particular audience.

**Comment by ExperimentsInHonesty** [comment]
Next steps for this issue is having @Jeremy-D @MalakH21 meet to determine suitabily descriptive label titles.  There are current a set in [la data sources workbook ](https://docs.google.com/spreadsheets/d/1JKMw4BT-i4gUC73lRXxI5g4yWOxhQ5OOAhG58Ch1LqY/edit#gid=1370034216) and some brainstorming during the meeting (see the last two comments preceding this note.

[Jeremy's notes](https://github.com/hackforla/access-the-data/issues/17#issuecomment-880307434)
[Bonnie's reinterpretation of Jeremys note](https://github.com/hackforla/access-the-data/issues/17#issuecomment-887841939)

**Comment by abryant35** [comment]
We are consolidating everything from this issue and #20
