### ISSUE TITLE
Data Expert Persona Interview Script

### ISSUE THREAD

**Issue by LouismChan** [hackforla/access-the-data#176]
### Overview

Create a list of interview questions for the Data Expert Persona.

### Action Items

Ask open ended questions (like how questions instead of yes or no questions) to keep conversation going and create opportunities for the person to tell their stories to give critical insights and ideas.
A few tips to keep in mind:
• Don’t try to ask all of these, prioritize based on your research goals.
• For each answer, be sure to ask “why” or “why not” or "how" to dig deeper.

### Resources/Instructions

User Interview Script #58
#163 
[Data Expert Persona Screener Survey draft](https://docs.google.com/document/d/1qkKsD78xLcQ-iOE2uctssOInJS87HUCetleawxeiB9k/edit) & [Data Expert Screener Survey Form](https://docs.google.com/forms/d/1Y5EVtnXi3lCpklEnU1IMAxl9FyFKGnwmaJTyqcplK1A/edit).

[Google Docs: Data Expert Persona Interview Questions](https://docs.google.com/document/d/1x1oVsE6weOIgK1Da9u_SXagvTr8mBcZTwn4fhg551j8/edit)

**Comment by LouismChan** [comment]
Drafted [Google Docs: Data Expert Persona Interview Questions](https://docs.google.com/document/d/1x1oVsE6weOIgK1Da9u_SXagvTr8mBcZTwn4fhg551j8/edit).  Ready to schedule and conduct interviews.  @mmelovega thanks.

**Comment by LouismChan** [comment]
@AubreySchiavone, @joycekyang, and @mmelovega will schedule and conduct interviews.  Thanks.

**Comment by bradyse** [comment]
Progress: @AubreySchiavone is scheduling more interviews.
Blockers: @AubreySchiavone needs to be onboarded to ATD's GitHub so that she can assign herself to the issue. 
Availability: @AubreySchiavone has availability over the next two weeks.
ETA: @lrchang2 needs to add Aubrey to the ATD membership

**Comment by LouismChan** [comment]
@lrchang2 please approve/move this issue to In Progress.  Thanks.

**Comment by mxajPrice** [comment]
Closing this issue per conversation in planning meeting on 7 July.
