### ISSUE TITLE
Onboard Mano Sakayan - UX Research

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/access-the-data#186]
### Overview
Onboard Mano Sakayan as a UX Researcher.

### Action Items
- [x] Slack channel membership
  - [x] #access-the-data
  - [x] #access-the-data-research
- [x] Add to Google calendar invites
   - [x] #141 
- [x] Google Drive
   - [x] Add to drive as Contributor
- [x] Roster
  - [x] Send link
  - [x] Team member adds themselves
- [ ] GitHub
     - [x] Add to team write team
     - [ ] Check their github handle by assigning them to this issue, to see if they have added their name, so that you don't have to memorize their handle
- [ ] Train how to 
   - [ ] Navigate the AtD GitHub and create issues

**Comment by bradyse** [comment]
@lrchang2  @lrchang2  Mano's GitHub handle is @manosak

The first task for Mano is to begin working on the Data Expert Interviews with @AubreySchiavone

**Comment by mxajPrice** [comment]
Hi @mmelovega , will Mano be using Figma?

**Comment by mxajPrice** [comment]
Mano will not be needing access to Figma.

**Comment by lrchang2** [comment]
mano is not on the project anymore, issue closed
