### ISSUE TITLE
Starting website workspace

### ISSUE THREAD

**Issue by nyarly** [hackforla/access-the-data#188]
### Overview

As a starting point, and point of focus for developers, create a first cut CKAN application instance and Dockerfile for hosting.

### Action Items
- [ ] build the existing Dockerfile from https://github.com/okfn/docker-ckan-lacounts
- [x] find a home for the Dockerfile in hackforla
- [ ] first pass clearing out the lacounts branding

**Comment by nyarly** [comment]
@mxajPrice

Blockers here:
- [ ] We need a repo for the accessthedata CKAN extension, as forked from lacounts
- [ ] I'll build the Dockerfile out there, but there's no guide about what makes for acceptable dockerfiles for Hack4LA

This repo could be used for the CKAN extension, but we'd lose the history of the original code, which might be really useful later.

We could be build the Dockerfile to general best practice, but I worry about pushback from ops.

**Comment by mxajPrice** [comment]
@nyarly can you add a size label to this?

**Comment by mxajPrice** [comment]
please update your issue with the following info  if you have not already
- Progress: "What is the current status of your project? What have you completed and what is left to do?"
- Blockers: "Difficulties or errors encountered."
- Availability: "How much time will you have this week to work on this issue?"
- ETA: "When do you expect this issue to be completed?"

**Comment by lrchang2** [comment]
@nyarly 
Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by mxajPrice** [comment]
@nyarly & @gjagnoor -

We ask that anyone working on an issue make regular, weekly updates.  When the PMs see an issue has not had updates for a week, we add the "To Update!" tag.  Here is an updates template you can use:

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by nyarly** [comment]
I'm game for weekly meetings. Let's coordinate this evening as to when works best for us.

My perspective is that we've got a working (90%) version of CKAN, with the LA Counts module working, and upgraded to CKAN 2.9 (which is current.) That's great! I think we'd all be best served by treating this ticket as done and creating new issues with concrete tasks.

Very first thoughts on initial tasks:
* Fix or disable Get Involved. AtD has its own design for this feature, so it may not be worthwhile.
* First steps adapting visual design - color scheme at least.
* Green tests - I know there's a test suite, but I'm unclear how to get them running, or if they're still relevant.

I think those should all be issues themselves, but I'm positive there's work to be done integrating other teams work with the website, and I wouldn't hesitate to prioritize those above these.

**Comment by gjagnoor** [comment]
I can meet Monday's after 5 or Thursdays after 5 PST. Does anytime then work for you? 

Ok sounds good. Given everything you've mentioned I agree we can treat this ticket as done. 

I'm going to have to look again but I think your hunch is right. The tests might be irrelevant now. Especially because we are redesigning "Get Involved" which seems to be the main part of the application. 

I'll start drafting issues for the next phase

**Comment by mxajPrice** [comment]
This is being closer per Judson's approval on Slack on 18 Jan 2023.
