### ISSUE TITLE
Topic list for Workshops

### ISSUE THREAD

**Issue by snooravi** [hackforla/access-the-data#19]
### Overview
**Look through Julien's shared resources and pull out most frequently requested topics (datasets)**
Develop list of topics to bring to Julien for his input on what we should start developing.

### Action Items
Look at Data Liaisons workshops for inspiration and develop 10 topics for first round of workshops

### Resources/Instructions
https://empowerla.org/data/
[drive](https://drive.google.com/drive/u/1/folders/1rNEFJEl7uzali9xB3mnp8Pvb9CI3KES9)

[Proposal for Workshop Improvements](https://docs.google.com/document/d/1j2kDVi_brwA8vlmIHRR9yrbndWM-Z72A9-sMt_X52g0/edit)
[Community Data 101 Workshop Content [Working Draft]](https://docs.google.com/document/d/1zTYQzvlmEHNxEq10hbArYJ3QxP7OTC1J1zAFWiKu6pA/edit?ts=60c3d070#heading=h.maby6z9cy9ag)

**Comment by snooravi** [comment]
1. Intro to Community Data (applications of open source datasets)
2. Deep dive into 311 (data collection, to data tables, to visualization)

**Comment by snooravi** [comment]
@MalakH21 @dplem if you can add to this list before Friday. Thank you

**Comment by dplem** [comment]
1. What Data Visualizations / Dashboards are currently available?
2. What is Data Analysis?
3. How to search LA Open Data Portal
4. What is the Geohub?
5. How to make your own visualizations with Tableau/ Google Colab
6. How to gather raw data

**Comment by snooravi** [comment]
https://docs.google.com/spreadsheets/d/1E-0M2iowTMZ7WAhgC3mnhmS3XJgDM_GRo4ZI-tZqSTU/edit#gid=0

**Comment by MalakH21** [comment]
Update - Using [Voyant](https://voyant-tools.org/?corpus=2b0181973b00abff7bad37e4018115b9&stopList=keywords-cce16a25ac78cbe136862401e24816a7&panels=cirrus,reader,trends,phrases,contexts) to get a preliminary idea of topic areas of interests from the feedback forms provided by Julien   

Next steps - update/change analysis to include bigraphs and update topic list if needed based on findings

**Comment by ExperimentsInHonesty** [comment]
@MalakH21 @snooravi I met with Julien on Friday and moved the conversation forward a little bit, and put notes in the following file, which it seemed like the place that the suggested courses are listed: https://docs.google.com/document/d/1zTYQzvlmEHNxEq10hbArYJ3QxP7OTC1J1zAFWiKu6pA/edit?ts=60c3d070#heading=h.maby6z9cy9ag

**Comment by ExperimentsInHonesty** [comment]
@MalakH21 @snooravi it looks like on May 12 it said the next steps were:
> Next steps - update/change analysis to include bigrams and update topic list if needed based on findings

Did that get done?  

Besides firming up Julien's understanding of what the workshops will be about  and which order... it would be good to get a list of the steps remaining.

**Comment by snooravi** [comment]
**Open Data Portal for Tabular data**
Progress has been made! Last year this time there was about 300 datasets and now there are 2K+ datasets. Examples: List of active businesses, Building & safety permits, Arrest data from 2010 - present, Open bid opportunities.

- **TOPIC 1**: Active Business
- **TOPIC 2**: 311 Data

Zimas for Tabular and Graphical Data

- **TOPIC 3**: Zimas
