### ISSUE TITLE
Design Volunteer Page (Join the ATD Team / Join the Science Community)

### ISSUE THREAD

**Issue by KC243** [hackforla/access-the-data#196]
### Overview
We will need to create a new page to allow users visiting the website to join the ATD team and the Hack for LA Data Science Community of Practice.  

### Action Items

- [x] Create a high fidelity "Join the ATD Team" Page
   - [x]  Create lo-fi prototypes
   - [x] bring lo fi prototypes to team for final decision 
   - [x]  Build out a hi-fi page in figma
- [x] Create a high fidelity "Join the Science Community" Page
   - [x]  Create lo-fi prototypes
   - [x] bring lo fi prototypes to team for final decision 
   - [x]  Build out a hi-fi page in figma
- [x] Review work on drafts of volunteer done (as seen in comments below)  
- [x] Redesign volunteer page to be consistent with rest of the website's design (i.e. images, call to action buttons for each section). Make sure to include: 
    - [x] new header and footer with correct IA 
    - [x] a section for how to volunteer on the ATD team
    - [x] a section (below) the ATD team for Data Science Community of Practice 
- [x] Review designs with team
- [x] Add copy into design from UX writer from #251 

### Resources/Instructions
[Figma](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma) 
[IA](https://docs.google.com/spreadsheets/d/1BV3TJ-tr2QPjij0IUXxTShtnHgDhAlkQAKIUELXAmWA/edit#gid=1126330674)

**Comment by pbahle** [comment]
![20220709_202846](https://user-images.githubusercontent.com/36608233/178128965-8580259d-beb6-4fae-b3d3-e5f16cd63cec.jpg)

Here's a couple sketched prototypes for the join the ATD page.
I included the header and footer from the ATD high fidelity wireframes, as well as making sure we had separate options for both ATD and the science team, plus a relevant section to highlight either a team member's story or the project itself, please drop suggestions for other page elements

**Comment by mxajPrice** [comment]
Please add more context to the difference in joining AtD and HfLA Data Science.

- Access the Data [repository](https://github.com/hackforla/access-the-data)
- Hack for LA Data Science Community of Practice [repository](https://github.com/hackforla/data-science#readme)

**Comment by mxajPrice** [comment]
please update your issue with the following info if you have not already

- Progress: "What is the current status of your project? What have you completed and what is left to do?"
- Blockers: "Difficulties or errors encountered."
- Availability: "How much time will you have this week to work on this issue?"
- ETA: "When do you expect this issue to be completed?"

**Comment by pbahle** [comment]
[](url
![join page 1 (1)](https://user-images.githubusercontent.com/36608233/183745855-5a0941f0-2d9e-4667-ac6b-c7334289d9cc.png)
)
Progress: I've completed high fidelity wireframes of both join ATD and the data science team, with the exception of the copywriting
Blockers: What sort of text will go on the page
Availability: 1-3 hours
ETA: Next week, (assuming UX writing is also under my responsibilities)

**Comment by lrchang2** [comment]
@pbahle is this done? if so, please close this issue

**Comment by bkong** [comment]
@pbahle Can you please update this issue or close it if it's done?

**Comment by mxajPrice** [comment]
To be re-assigned.

**Comment by majkush** [comment]
I am happy to help whoever gets assigned this wireframe with the UX Writing. Please just reach out to me if I can be of help.

**Comment by lrchang2** [comment]
Need to redo pages to reflect "get involved' section on our current about page 
![image](https://user-images.githubusercontent.com/10827101/214438249-9b710113-e848-4f4f-ab65-162b9d6d4c55.png)

**Comment by mxajPrice** [comment]
please update your issue with the following info  if you have not already
- Progress: "What is the current status of your project? What have you completed and what is left to do?"
- Blockers: "Difficulties or errors encountered."
- Availability: "How much time will you have this week to work on this issue?"
- ETA: "When do you expect this issue to be completed?"

**Comment by deepamohan22** [comment]
@mxajPrice @lrchang2  
Progress:  Tried Designing the Volunteer page
Blockers:  
Availability: 6 
<img width="199" alt="Screenshot_20230207_061454" src="https://user-images.githubusercontent.com/102125634/217411827-f0f16fbc-ebd9-45a2-9b67-76d0b6588498.png">
hrs
ETA: 12 hrs

**Comment by deepamohan22** [comment]
<img width="220" alt="Screenshot_20230207_071740" src="https://user-images.githubusercontent.com/102125634/217420082-db79531a-5cbe-4575-921c-b93cbcd1e4ce.png">

**Comment by deepamohan22** [comment]
<img width="141" alt="Screenshot_20230208_104737" src="https://user-images.githubusercontent.com/102125634/217623844-ed7b0be8-0ff5-49cd-ba82-11565d14af49.png">

**Comment by lrchang2** [comment]
notes from 2/8/2023 team meeting 

- team has decided to keep everything on one page 
- get rid of form for "enter your information" to minimize data collection and use existing recruiting flows 
- make 1st section "want to volunteer" more informational and letting people know about the opportunities out there. Aim is to lead people to respective github pages
   - [ATD github](https://github.com/hackforla/access-the-data)
   - [Data Science Community of Practice github](https://github.com/hackforla/data-science)
- make 2nd section "enter your information" more for people who know they want to volunteer (less resistance). Aim is to lead people to the [Hack for LA Join Us page ](https://www.hackforla.org/join) to start contributing asap 

next steps: 

- change sections to reflect notes from above
- work on mobile version

**Comment by deepamohan22** [comment]
@mxajPrice , @lrchang2 
Progress: Added URL of AtD  GitHub and Data science practice of community 
Blockers: I can start  Designing the volunteer page once I get a copy for UX writing New Copy of Volunteer page. 
Availability: 6
<img width="400" alt="Screenshot_20230214_105516" src="https://user-images.githubusercontent.com/102125634/218831049-7c4ca4da-f9bb-4fd9-8d8f-3cadd5a70ec2.png">

**Comment by mxajPrice** [comment]
@lrchang2 and I were thinking this would be a button rather than a link, but perhaps @lesUXW can weigh in on what would look better.

**Comment by lesUXW** [comment]
Hi @lrchang2 and @mxajPrice, I also think a button would be visually better, and also easier for anyone to see it as a CTA.

**Comment by deepamohan22** [comment]
@lrchang2 , @mxajPrice 
Changed from URL to Button
<img width="235" alt="Screenshot_20230215_045807" src="https://user-images.githubusercontent.com/102125634/219230622-c98ad905-4591-41fa-bf83-9591947d437c.png">

**Comment by deepamohan22** [comment]
<img width="275" alt="Screenshot_20230215_051342" src="https://user-images.githubusercontent.com/102125634/219234521-10b595d9-15c9-4e20-a19c-60b9307c1f45.png">

**Comment by lrchang2** [comment]
@deepamohan22 can you make the buttons on the volunteer page match the ones on the home page that is black text instead of white?

**Comment by deepamohan22** [comment]
@mxajPrice @lrchang2 
  **Updated Deskto**p
Changed the Button texts color to Black
<img width="195" alt="Screenshot_20230222_092747" src="https://user-images.githubusercontent.com/102125634/220708254-561cfce0-2d28-4c70-a90d-ea1d0689572d.png">
<img width="45" alt="Screenshot_20230222_092829" src="https://user-images.githubusercontent.com/102125634/220708275-0bf29ef0-4201-4740-a53c-cb4bf1d52801.png">
 and Mobile version Volunteer page

**Comment by deepamohan22** [comment]
Updated texts with Bullet Points
<img width="39" alt="Screenshot_20230222_111108" src="https://user-images.githubusercontent.com/102125634/220799001-3a6456c0-b45a-4725-b5d8-d7fc87e86bad.png">

**Comment by lrchang2** [comment]
note: underlined text in button means it's a link and is not a design choice.

**Comment by deepamohan22** [comment]
@lrchang2 @mxajPrice ,
**Final copy**
<img width="107" alt="Screenshot_20230222_111151" src="https://user-images.githubusercontent.com/102125634/221279442-2b9b2b9c-505b-47e3-9340-cdaa4542578b.png">
<img width="45" alt="Screenshot_20230223_055007" src="https://user-images.githubusercontent.com/102125634/221279474-b97cae51-d3e6-477e-acc9-51f33b66530a.png">
Updated the volunteer  page with updated copy of texts.

**Comment by lrchang2** [comment]
@deepamohan22 this looks great! only ask is that on the Desktop version, for the 2nd section for the community of practice, since we have the space, can you extend the bullet point text to be on one line?
