### ISSUE TITLE
Create Interview Script for Community Activists

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/access-the-data#197]
### Overview
We need to create an interview script for the Community Activist Persona.

### Action Items

- [x] Review past scripts
- [x] Draft script in [the Drive](https://drive.google.com/drive/u/1/folders/1Wr3qoQ56T9WefQ5yTbbSPvHSZt9RMW0k)
- [x] Review with @mmelovega 
- [x] Finalize
- [x] Get final approval from @mmelovega 
- [x] Update in [wiki](https://github.com/hackforla/access-the-data/wiki/Research:-Community-Activist)

### Resources/Instructions
- #58 
- [Data Expert Persona Script](https://docs.google.com/document/d/1x1oVsE6weOIgK1Da9u_SXagvTr8mBcZTwn4fhg551j8/edit)
- [previous Community Activist script](https://docs.google.com/document/d/1zDYKc1m3r5GwK3jHmF6V_vq8GpqX-hmp1mfNk3fCuYc/edit)

**Comment by hannahsgr** [comment]
- Created the community activist [script ](https://docs.google.com/document/d/19T9jE_Fd4nkppnUUchV29mqOjJcg6vBbXmDRCHP1iHg/edit)
- Reviewed script with Mariana and Joyce during the research team meeting. Linked the script in the website research channel for further review by researchers who were unable to attend the meeting.
