### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by snooravi** [hackforla/access-the-data#2]
### Overview
Readme needs an update so that people thinking about joining our project know how to contribute.

### Action Items

- [x] Review the readme resource and figure out what we can include in ours.  Also look at the one for civic opportunity as an example
- [x] Update our readme
- [x] Send to Bonnie for review

### Resources/Instructions
[Hack for LA's default readme](https://github.com/hackforla/.github) 
[civic opportunity readme](https://github.com/hackforla/civic-opportunity)
[hackforla.org website readme](https://github.com/hackforla/website)

**Comment by ExperimentsInHonesty** [comment]
I changed the link to the one sheet to point at the pdf version instead of the previous draft.

Previous Draft
https://docs.google.com/document/d/1_CxBQ_ku4sanPIWKtPyENJ4E9hQKETQs8IWAOCzgqqk/edit
Current Draft
https://docs.google.com/document/d/1bWWhI0Zuas22sdEEDC6sSuRYZ3gXiBZ8LuyNUmD_s7o/edit
