### ISSUE TITLE
Data Expert Persona Synthesis: Affinity Map

### ISSUE THREAD

**Issue by LouismChan** [hackforla/access-the-data#201]
### Overview
We need to present an affinity map to find common trends, pains and gains for the data expert persona, to understand how they would like to use their expertise to give back to their community.

### Action Items
- [x]  Familiarize with targeted persona in 
    - #163 
    - #176 
    - #185
- [x]  Do the [Data Expert Affinity Map](https://www.figma.com/file/K1KJbdWBh4fwse0JzunBVN/Affinity-diagram-(Data-Expert))
- [x]  Present the [Data Expert Affinity Map](https://www.figma.com/file/K1KJbdWBh4fwse0JzunBVN/Affinity-diagram-(Data-Expert))
- [x]  Revise the [Data Expert Affinity Map](https://www.figma.com/file/K1KJbdWBh4fwse0JzunBVN/Affinity-diagram-(Data-Expert))

### Resources/Instructions
[Data Expert Affinity Map](https://www.figma.com/file/K1KJbdWBh4fwse0JzunBVN/Affinity-diagram-(Data-Expert))
[Data Expert Empathy Map](https://www.figma.com/file/f8BlTmLSRx8Ti0ZyGUfI9K/Data-Expert)
[Data Expert Detailed Persona](https://www.figma.com/file/IQCYJ4KyZ0lpJBbwZuPTcn/Data-Expert)

**Comment by mmelovega** [comment]
Thank you Louis.  What is the deadline for this?
