### ISSUE TITLE
Offboard: Eevin, Aubrey, Mano, Tiffany

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/access-the-data#202]
### Overview
We need to offboard the following people:

- Eevin Jennings
- Aubrey Schiavone
- Mano Sakayan
- Tiffany Sie

#### Offboard Action Items
- [x] Remove from Google calendar invite
   - [x] #141 
- [ ] WIKI/Github Project Boards
  - [x] move to new place on team page
  - [x] 1password setup
    - [x] remove from team vaults
       - [x] Access the Data - Data Literacy vault
       - [x] Zoom vault
- [x] Google Drive
   - [x] demote to viewer
- [x] Roster
  - [x] mark as inactive
- [x] GitHub
     - [x] demote member to read only team and remove from write team
- [x] Figma
  - [x] demote to "viewer"
- [x] Social Media Accounts with role assignment
   - [x] Facebook

### Resources/Instructions
- [1password.com](https://1password.com/)
- [Google Drive Link](https://drive.google.com/drive/u/2/folders/0AK-gcCeDY7GYUk9PVA)
- [Access the Data Roster](https://docs.google.com/spreadsheets/d/1b97Np96EimkxicW83pwnYkn7uDd7fCD5H_6F21nOkg4/edit#gid=0)
- [GitHub Team URL](https://github.com/orgs/hackforla/teams?query=access)
   - [base (read)](https://github.com/orgs/hackforla/teams/access-the-data/members)
   - [write](https://github.com/orgs/hackforla/teams/access-the-data-write/members)
   - [maintain](https://github.com/orgs/hackforla/teams/access-the-data-maintain/members)
   - [triage] - none at this time
   - [admin](https://github.com/orgs/hackforla/teams/access-the-data-admin/members)
- Check public and 2FA at [people page](https://github.com/orgs/hackforla/people)
- WIKI team page: https://github.com/hackforla/access-the-data/wiki/Join-the-Access-the-Data-Team
- [Access the Data Figma Team](https://www.figma.com/files/team/966550530967927285/Access-The-Data?fuid=775836858007206739)
- Shortcut for adding a profile to the desktop:  chrome://settings/manageProfile
- Tutorials
  - [Forward emails to team members](https://github.com/hackforla/product-management/wiki/Forward-emails-to-team-members)

---
[org template](https://raw.githubusercontent.com/hackforla/.github/main/.github/ISSUE_TEMPLATE/onboard---offboard--product.md) updated 2022-02-23
[Changelog](https://github.com/hackforla/product-management/wiki/Onboard-Offboard-Changelog)

**Comment by lrchang2** [comment]
slacked #admin channel to take people off of the vaults in 1password. https://hackforla.slack.com/archives/C01Q24YF56J/p1658267315383179

**Comment by lrchang2** [comment]
got response from Karen in slack #admin channel that she took all the people off of 1password vaults
