### ISSUE TITLE
Data Expert Persona Synthesis: Empathy Map

### ISSUE THREAD

**Issue by mmelovega** [hackforla/access-the-data#204]
### Overview
After doing the Affinity Map, we need to create an Empathy Map, to find common trends, pains and gains for the data expert persona, to understand how they would like to use their expertise to give back to their community. 

### Action Items
- [x]  Familiarize with targeted persona in 
    - #163 
    - #176 
    - #185
    - #201
- [x]  Do the [Data Expert Empathy Map](https://www.figma.com/file/f8BlTmLSRx8Ti0ZyGUfI9K/Data-Expert)
- [x]  Present the [Data Expert Empathy Map](https://www.figma.com/file/f8BlTmLSRx8Ti0ZyGUfI9K/Data-Expert)
- [x]  Revise the [Data Expert Empathy Map](https://www.figma.com/file/f8BlTmLSRx8Ti0ZyGUfI9K/Data-Expert)

### Resources/Instructions
[Data Expert Affinity Map](https://www.figma.com/file/K1KJbdWBh4fwse0JzunBVN/Affinity-diagram-(Data-Expert))
[Data Expert Empathy Map](https://www.figma.com/file/f8BlTmLSRx8Ti0ZyGUfI9K/Data-Expert)
[Data Expert Detailed Persona](https://www.figma.com/file/IQCYJ4KyZ0lpJBbwZuPTcn/Data-Expert)

**Comment by lrchang2** [comment]
@LouismChan 
Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by LouismChan** [comment]
@lrchang2 @mmelovega 
Progress: I have made another revision to the Empathy Map.  I am ready to present it tomorrow during demo day.

**Comment by bkong** [comment]
@LouismChan Are you continuing to make revisions to the Empathy Map or is it done? If it's done, can you please close the issue?

**Comment by LouismChan** [comment]
@bkong Okay I will close it.
