### ISSUE TITLE
Data Expert Persona Synthesis: Detailed Persona

### ISSUE THREAD

**Issue by ghost** [hackforla/access-the-data#205]
### Overview
We need to create a Detailed Persona to find common trends, pains and gains for the data expert persona, to understand how they would like to use their expertise to give back to their community.

### Action Items
- [x]  Familiarize with targeted persona in 
    - #163 
    - #176 
    - #185
    - #201 
    - #204
- [x]  Do the [Data Expert Detailed Persona](https://www.figma.com/file/IQCYJ4KyZ0lpJBbwZuPTcn/Data-Expert)
- [x]  Present the [Data Expert Detailed Persona](https://www.figma.com/file/IQCYJ4KyZ0lpJBbwZuPTcn/Data-Expert)
- [x]  Revise the [Data Expert Detailed Persona](https://www.figma.com/file/IQCYJ4KyZ0lpJBbwZuPTcn/Data-Expert)

### Resources/Instructions
[Data Expert Affinity Map](https://www.figma.com/file/K1KJbdWBh4fwse0JzunBVN/Affinity-diagram-(Data-Expert))
[Data Expert Empathy Map](https://www.figma.com/file/f8BlTmLSRx8Ti0ZyGUfI9K/Data-Expert)
[Data Expert Detailed Persona](https://www.figma.com/file/IQCYJ4KyZ0lpJBbwZuPTcn/Data-Expert)

**Comment by LouismChan** [comment]
@lrchang2 The [Data Expert Detailed Persona](https://www.figma.com/file/IQCYJ4KyZ0lpJBbwZuPTcn/Data-Expert) in FigJam has been completed.  Next step is presentation and then revision upon receiving comments and suggestions.

**Comment by lrchang2** [comment]
thanks so much @LouismChan! this is awesome, ill put you on the agenda to present this to the team tomorrow wednesday 10/26 during demo day

**Comment by bkong** [comment]
@LouismChan thanks for presenting the detailed persona on demo day. If this is done, can you please close this?
