### ISSUE TITLE
Update Current HiFi Wireframes and Info Architecture

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/access-the-data#206]
### Overview
To update with Data Catalog.

### Action Items

- [x] update[ info arch - V3.1](https://docs.google.com/spreadsheets/d/1BV3TJ-tr2QPjij0IUXxTShtnHgDhAlkQAKIUELXAmWA/edit#gid=1188394452) with data catalog
- [x] Update the [CURRENT HiFi Wireframe](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A27&t=DTbwx9A0SAY8FTQM-0) with 
   - [x] with newest screens from [high fi wireframes (desktop)](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A16&t=QsZ5sKdpNM2yllWs-0)
   - [x] header [ component](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=1313%3A4075&t=DTbwx9A0SAY8FTQM-0) to reflect V3.1 of the info architecture
   - [x] footer [ component](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=1313%3A4075&t=DTbwx9A0SAY8FTQM-0) to reflect V3.1 of the info architecture

**Comment by lrchang2** [comment]
@deepamohan22 
Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by lrchang2** [comment]
@deepamohan22 AJ and I were discussing how we can indicate different sections on one page in the header and footer IA. So if you see V3.1, there is an added "meet the team" part. we will discuss this in the meeting tomorrow in more detail

**Comment by deepamohan22** [comment]
Progress:4 tasks completed out of 5
Blockers :No
Availability: 6 hrs
ETA:  by this week
Pictures
<img width="288" alt="Screenshot_20230124_033150" src="https://user-images.githubusercontent.com/102125634/214444284-974801a7-1ce9-42ef-93be-5829efd7a45a.png">
<img width="66" alt="Screenshot_20230124_033336" src="https://user-images.githubusercontent.com/102125634/214444498-47081d01-3b1c-4faf-953f-6436947ec62d.png">
<img width="208" alt="Screenshot_20230124_033451" src="https://user-images.githubusercontent.com/102125634/214444646-8daa56d1-613c-4fae-86e3-26664320eed3.png">

**Comment by deepamohan22** [comment]
Progress: All tasks completed
Blockers : No
FOOTER
<img width="435" alt="Screenshot_20230131_063316" src="https://user-images.githubusercontent.com/102125634/215931226-192e2eb0-8db1-460f-842c-813c895875cd.png">

**Comment by deepamohan22** [comment]
<img width="96" alt="Screenshot_20230131_064253" src="https://user-images.githubusercontent.com/102125634/215932437-b28c67a2-f730-4da2-abf8-bd930f766949.png">

**Comment by deepamohan22** [comment]
Added Contact us section in the About page
<img width="126" alt="Screenshot_20230131_064449" src="https://user-images.githubusercontent.com/102125634/215932666-e7c1b610-ffbc-4138-a401-dd9cf90257ab.png">

**Comment by mxajPrice** [comment]
This is complete.
