### ISSUE TITLE
Offboard: Sara Brady and Archana Mudiam

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#209]
### Overview
Need to offboard Sara and Archana

### Action Items
- [x] Remove from Google calendar invite
   - [x] #141 
- [x] WIKI
  - [x] move to new place on team page
  - [x] 1password setup
    - [x] remove from team vaults
       - [x] Access the Data - Data Literacy vault
       - [x] Zoom vault
- [x] Google Drive
   - [x] demote to viewer
- [x] Roster
  - [x] mark as inactive
- [x] GitHub
     - [x] demote member to read only team and remove from write team
- [x] Figma
  - [x] demote to viewer
- [x] Social Media Accounts with role assignment
   - [x] Facebook
- [x] Have exit interview
    - Why brought them to Hack for LA and Access the Data
    - What are their current professional goals, if any
    - Why are they leaving
    - How well did they fit with their team
    - How well did you understand what Hack for LA is, Access the Data is, and what work needed to be done
    - How was overall experience working on Access the Data
    - What suggestions do they have for Hack for LA and Access the Data
    - Any other feedback
    - Where are they headed off to next in their life

### Resources/Instructions
- [1password.com](https://1password.com/)
- [Google Drive Link](https://drive.google.com/drive/u/2/folders/0AK-gcCeDY7GYUk9PVA)
- [Access the Data Roster](https://docs.google.com/spreadsheets/d/1b97Np96EimkxicW83pwnYkn7uDd7fCD5H_6F21nOkg4/edit#gid=0)
- [GitHub Team URL](https://github.com/orgs/hackforla/teams?query=access)
   - [base (read)](https://github.com/orgs/hackforla/teams/access-the-data/members)
   - [write](https://github.com/orgs/hackforla/teams/access-the-data-write/members)
   - [maintain](https://github.com/orgs/hackforla/teams/access-the-data-maintain/members)
   - [triage] - none at this time
   - [admin](https://github.com/orgs/hackforla/teams/access-the-data-admin/members)
- Check public and 2FA at [people page](https://github.com/orgs/hackforla/people)
- WIKI team page: https://github.com/hackforla/access-the-data/wiki/Join-the-Access-the-Data-Team
- [Access the Data Figma Team](https://www.figma.com/files/team/966550530967927285/Access-The-Data?fuid=775836858007206739)
- Shortcut for adding a profile to the desktop:  chrome://settings/manageProfile
- Tutorials
  - [Forward emails to team members](https://github.com/hackforla/product-management/wiki/Forward-emails-to-team-members)

**Comment by lrchang2** [comment]
- Why brought them to Hack for LA and Access the Data
- What are their current professional goals, if any
- Why are they leaving
- How well did they fit with their team
- How well did you understand what Hack for LA is, Access the Data is, and what work needed to be done
- How was overall experience working on Access the Data
- What suggestions do they have for Hack for LA and Access the Data
- Any other feedback
- Where are they headed off to next in their life

**Comment by lrchang2** [comment]
requested individuals to be taken off  the 1password Access the Data - Data Literacy vault in #admin channel

**Comment by mxajPrice** [comment]
Karen removed them from the vault.
<img width="354" alt="Screen Shot 2022-09-22 at 12 32 19" src="https://user-images.githubusercontent.com/98370780/191835078-3d26e560-aeca-44f6-b42a-a414e66335ce.png">

**Comment by mxajPrice** [comment]
All task complete- closing this issue.
