### ISSUE TITLE
Update Project Profile: Access The Data 

### ISSUE THREAD

**Issue by snooravi** [hackforla/access-the-data#21]
### Overview
We need to audit the project card for HackforLA to reflect the team's current project status and information.

### Action Items

- [x] Review the project card on the HackforLA website
- [x] Convert [Google Doc](https://docs.google.com/document/d/1bWWhI0Zuas22sdEEDC6sSuRYZ3gXiBZ8LuyNUmD_s7o/edit) to PDF at https://github.com/hackforla/product-management 
- [x] Open a new ticket on the HackforLA repository to ask for changes
- [ ] Monitor issue until completed

### Resources/Instructions 
Issue at Hackforla.org website team https://github.com/hackforla/website/issues/2177
Https://Hackforla.org 
[PDF of Access the data one sheet](https://github.com/hackforla/product-management/blob/master/project-one-sheets/Access-the-Data-One-Sheet.pdf)

**Comment by abryant35** [comment]
Acceptance testing 

- [ ] Github
- [ ] Slack
- [ ] One Sheet - should be updated to new one sheet 
   - [ ] Convert [Google Doc](https://docs.google.com/document/d/1bWWhI0Zuas22sdEEDC6sSuRYZ3gXiBZ8LuyNUmD_s7o/edit) to PDF at https://github.com/hackforla/product-management
 - [ ]  Looking for- remove UX Lead to build surveys
 - [ ] Partner 
 - [ ] Language 
 - [ ] Tools
 - [ ] Location
 - [ ] Team Members
    - [ ] Alyssa Bryant
    - [ ] slack member ID:
    - [ ] Github handle
    - [ ] Title
    - [ ] Lucy Chang
    - [ ] slack member ID:
    - [ ] Github handle 
    - [ ] Title
    - [ ] Jeremy DeCarvalho
    - [ ] slack member ID:
    - [ ] Github handle 
    - [ ] Title

**Comment by lrchang2** [comment]
add team members to website with name, slack member ID, github handle and title found in [roster] (https://docs.google.com/spreadsheets/u/1/d/1b97Np96EimkxicW83pwnYkn7uDd7fCD5H_6F21nOkg4/edit#gid=0)

- [ ] Uju
- [ ] Assel
- [ ] Alyssa
- [ ] Jeremy
- [ ] Lucy

**Comment by lrchang2** [comment]
**name:** Lucy Chang
 **slack member ID:** U025WJ8CHFC
 **Github handle:** lrchang2
 **Title:** product manager

**Comment by snooravi** [comment]
Sarah Nabelsi
Slack ID: U01J9V1H63F
github: Sarah Nabelsi
Title: Project Manager

**Comment by abryant35** [comment]
Alyssa Bryant
Slack ID :U026DETL43B
Github: abryant35
Title: Product manager

**Comment by Jeremy-D** [comment]
Jeremy DeCarvalho
Slack ID: UFDG06RJQ
GitHub: Jeremy-D
Title: Data Analyst

**Comment by asselabilova** [comment]
name: Assel Abilova
slack member ID: U026G6WV49K
Github handle: asselabilova
Title: UX/UI Designer

**Comment by snooravi** [comment]
next steps: 
- [ ] Convert Google [Doc](https://docs.google.com/document/d/1bWWhI0Zuas22sdEEDC6sSuRYZ3gXiBZ8LuyNUmD_s7o/edit) to PDF at https://github.com/hackforla/product-management

**Comment by MalakH21** [comment]
Name: Malak Hmimy
Slack ID: U01TL5WE7G8
GitHub: MalakH21
Title: Generalist

**Comment by snooravi** [comment]
[Access the Data One Sheet .pdf](https://github.com/hackforla/access-the-data/files/6865915/Access.the.Data.One.Sheet.pdf)

**Comment by ExperimentsInHonesty** [comment]
@abryant35 This is the new url for the access the data one sheet 
https://github.com/hackforla/product-management/blob/master/project-one-sheets/Access-the-Data-One-Sheet.pdf

**Comment by ExperimentsInHonesty** [comment]
@abryant35 Please open the new issue on hackforla website: https://github.com/hackforla/website/issues/new?assignees=&labels=&template=project-profile-card-review-and-update.md&title=Update+Project+Profile%3A+%5BProject+Name%5D and past a link to the new issue so I can check it before we ask them to prioritize.

**Comment by abryant35** [comment]
@ExperimentsInHonesty I have opened the issue for our team. The issue [url](https://github.com/hackforla/website/issues/2007)

**Comment by ExperimentsInHonesty** [comment]
@MalakH21 Can we do another title other than generalist?

**Comment by MalakH21** [comment]
> @MalakH21 Can we do another title other than generalist?

yup, edited the comment

**Comment by ExperimentsInHonesty** [comment]
@abryant35 please update this comment https://github.com/hackforla/website/issues/2007#issuecomment-892183607 with the new title for Malak

**Comment by abryant35** [comment]
> @abryant35 please update this comment [hackforla/website#2007 (comment)](https://github.com/hackforla/website/issues/2007#issuecomment-892183607) with the new title for Malak

I have updated Malak's title

**Comment by abryant35** [comment]
Still waiting for issue to be updated by Hack for LA website team.

**Comment by ExperimentsInHonesty** [comment]
same - but I unassigned the person working on it and put it back into prioritized backlog

**Comment by ExperimentsInHonesty** [comment]
@abryant35 Open a new issue asking them to change the overview link to this pdf url https://github.com/hackforla/product-management/blob/master/project-one-sheets/Access-the-Data-One-Sheet.pdf

**Comment by abryant35** [comment]
I've created a new [issue](https://github.com/hackforla/website/issues/2177) to get the Overview updated to the One Sheet pdf. I do not appear to have authorization to add labels to this issue. This is the [old issue](https://github.com/hackforla/website/issues/2007) that is now closed.

**Comment by abryant35** [comment]
Issue is still pending review
