### ISSUE TITLE
Create LinkedIn Message for Community Activist Interview Recruitment

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#211]
### Overview
We need to create a LinkedIn recruitment message targeted at getting community activists to interview us for the persona. 

### Additional Information
- Consider @ people (with people's permission) on LinkedIn to get it on their feed and increase reach. 
- Make sure that it's clear that the message is for a single project under Hack for LA 

cant find civic related data? data published by government? other sources but by civic issues? 
poll...tell us more about it? 
 

### Action Items
- [x] Design and add social preview for [ATD github](https://github.com/hackforla/access-the-data/settings)
- [x] Create draft of LinkedIn post targeted at Community Activist
   - [ ] Add ATD Github link to post (where social preview is seen)
- [x] Review draft with PMs and Research Lead 
- [x] Edit draft based on feedback
- [ ] Review draft with Bonnie 
- [ ] Edit draft based on feedback
- [ ] Bring to PM meeting with Bonnie to post on Hack for LA's LinkedIn page

### Resources/Instructions
[example LinkedIn Post](https://www.linkedin.com/feed/update/urn:li:activity:6943279514747621377/)

**Comment by lrchang2** [comment]
@joycekyang Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by joycekyang** [comment]
Progress: The message is written, has been reviewed by ux writer and ux research team, all that is left is  review the draft with Bonnie, edit based on feedback, and bring the message to the meeting/post the message.
Blockers: "Difficulties or errors encountered."
Availability: 2 hours this week to work on this issue.
ETA: This issue should be compeleted by the start of next week's meeting.
Pictures: [link to message ](https://docs.google.com/document/d/1acsxeziXBA2dku56XTYj2O_Q1lwBM7ONWc34SGml0f0/edit?usp=sharing)

**Comment by bkong** [comment]
@joycekyang Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by joycekyang** [comment]
Progress: Message is written.
Blockers:  Blocker of waiting on approval from Bonnie and PMs, I believe @lrchang2 mentioned that she will check it with Bonnie last meeting.
Availability: 2 hours
ETA: Once approved by Bonnie, the message can be posted immediately. 
Pictures: N/A
