### ISSUE TITLE
Role Recruitment: Engineer

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/access-the-data#213]
### Overview
We need to recruit for engineering to help move the project along. 

### Action Items

- [x] Create list of required knowledge
- [x] Determine what work needs to be done
- [x] Write blurb to put on the open role board based on template: 

```
**Project Name:** Access the Data

**Volunteer Opportunity:** [your opportunity description replaces these brackets]

**Duration:**

**Who to communicate your interest to:**

- Slack channel link: [#access-the-data](https://hackforla.slack.com/archives/C01L2ANCG6M)
- Slack name of person to contact in the channel:

**When we meet:** 

[Read more about the project](https://www.hackforla.org/projects/access-the-data)

**Resources:**
```

- [x] Review blurb 
- [x] Follow [directions ](https://github.com/hackforla/product-management/projects/8#card-53859442)to put on open role board
- [x] Link and post on [Engineering Slack channel](https://hackforla.slack.com/archives/C01CU709SER) and the [General channel](https://hackforla.slack.com/archives/C04502L0P)
- [x] Interview interested parties and onboard

### Resources/Instructions
[Engineering open role board](https://github.com/hackforla/engineering/projects/2)
Example: [Data science open role board for Access the Data](https://github.com/hackforla/data-science/projects/2?card_filter_query=access#card-55546893)

**Comment by nyarly** [comment]
**Project Name:** Access the Data

**Volunteer Opportunity:**

Access the Data is seeking a Python developer to help us with our mission. Useful experience would include working in Flask or migrations from Python 2 to 3. The project is built on CKAN, so experience there would be useful, but not necessary.

We need to adapt an existing project to provide open data to the LA community, and serve as a template for other municipalities to build out their own open data platform.

We're working from the (defunct) lacounts.org code base, which is an extension to CKAN. CKAN is a data source management platform built on Flask, in Python. The project is currently tackling the migration of the older Python 2 code to Python 3 and CKAN 2.95.

In the extended term, we'll be adapting the original code to the Access the Data visual design principles, and extended the backend as required by the Access the Data mission.

**Duration:**

At least a few weeks; open ended.

**Who to communicate your interest to:**

- Slack channel link: [#access-the-data](https://hackforla.slack.com/archives/C01L2ANCG6M)
- Slack name of person to contact in the channel:
`@judson`

**When we meet:** 

Access the Data currently meets on Wednesdays, at 5pm PT. The engineering team does not yet have any other meeting time, but might schedule a convenient time to collaborate.

[Read more about the project](https://www.hackforla.org/projects/access-the-data)

**Resources:**

The existing code repo is at https://github.com/hackforla/accessthedata-ckan

**Comment by nyarly** [comment]
@mxajPrice or @lrchang2 do you want to review the above?

**Comment by lrchang2** [comment]
@nyarly the text looks good but it seems long. check the word count for a post on the open roles board. you might have to edit accordingly. 

we also have a best practice to put our logo at the top of the post to catch people's eye better. this is the code you would have to put at the top of the note: 
`<img src="https://user-images.githubusercontent.com/10827101/169327862-09c89c93-c002-4436-a6f6-9ded150c3393.jpg" />`

**Comment by nyarly** [comment]
I've updated the text above with that feedback. I'll post it to the engineering repo soon.

**Comment by mxajPrice** [comment]
@nyarly and @mxajPrice will be meeting with [Noor Grewal](https://www.linkedin.com/in/noorgrewal/) about helping on the development team today at 6:30pmPT.

**Comment by mxajPrice** [comment]
@nyarly Should we continue recruiting?

**Comment by mxajPrice** [comment]
We have successfully added Noor to our team.  Closing this issue.
