### ISSUE TITLE
ATD Website UX Writing (Landing Page & About Page)

### ISSUE THREAD

**Issue by majkush** [hackforla/access-the-data#226]
### Overview
The ATD website prototype is in a transition away from data-literacy modules. The UX Writing Resources have been developed to assist in accurate and consistent brand voice. The website prototype text needs to be revisited and updated where needed. 

### Dependency
This is a medium-term project. A related, smaller, priority project is the development of carousel text for the website prototype.
- [Carousel text A/B test Issue #227](https://github.com/hackforla/access-the-data/issues/227)

### Goals for Copy (adapted and modified from previous website copy iteration #87)

1. people who visit the website have a clear understanding of what Access the Data is as a project and who it is our target audience
3. users know what service is provided (catalog of open-access data)
4. people clearly understand the value add of the service provided
5. if interested, how to move forward/participate (1: signup to volunteer, 2: use the catalog)

### Action Items
The current copy text is 5-25-2022 on the current website prototype (see link in resources below). For the 5-25-2022 prototype text, the task is to:

- [x] Confirm goals for this issue with the team
- [x] Create a Google Doc to house all text edits
- [x] Revisit, and if necessary, update Landing page copy
- [x] Revisit, and if necessary, update About page copy
- [x] Revisit, and if necessary, update copy for carousels
- [ ] Develop and execute an A/B test of carousel copy, comparing 5-25-2022 copy with any updated copy (see #227).
- [x] Get feedback from team, stakeholders, and organization
- [x] Edit based on feedback
- [x] Give to designer to add copy to Figma for web and mobile prototypes
- [x] Have a graphic designer create the 3 new images for the "How it Works" section of the About page.
- [x] Approval by PMs and the file "Current Hi Fi Wiremframe..." updated to reflect the changes.

### Resources/Instructions
- [UX Writing Resources](https://github.com/hackforla/access-the-data/wiki/ATD-Website-Overview#ux-writing-resources)
- [Current website prototype for desktop](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A16)
- [The current website architecture is: V 3.1 on this spreadsheet](https://docs.google.com/spreadsheets/d/1BV3TJ-tr2QPjij0IUXxTShtnHgDhAlkQAKIUELXAmWA/edit#gid=1188394452)

### Work in Progress

- [Website Copy - Draft Oct 2022](https://docs.google.com/document/d/1E2uneJMj5Xtrw1icHTy-f_wV4bozPx-OaF8hDqgJ7Ic/edit?usp=sharing)

**Comment by majkush** [comment]
A draft of the website text for the landing page about the about page has been drafted. @lrchang2 requested that I focus on that text for now. Thus, the text is now open for feedback from the team and can be accessed via the link to 'website copy - draft Oct 2022' under the header Work in Progress in the issue.

**Comment by majkush** [comment]
Per 11/2/2022 meeting suggestion from @lrchang2, I will reach out to @deepamohan22 regarding moving the text into an updated version of the high-fidelity desktop and mobile versions in Figma.

**Comment by majkush** [comment]
Importing the website copy into Figma and updating the design was completed on Nov. 8 by  @deepamohan22. They are available on the Hi Fi Wireframe desktop and mobile Figma files, under "Updated Text Nov. 5 2022". The last step is to have the update reviewed by the PMs (@lrchang2, @mxajPrice and/or @bkong) so, if approved, it can be moved into the Figma file "Current Hi Fi Wiremframe..."

**Comment by lrchang2** [comment]
@deepamohan22 thanks for updating the text! this seems like design focused work, can you make a new issue for this? 

we have a few change requests before moving it to the "current hi fi wireframe" page:
- make all normal (non header) text the same font size. "About Us" section on the Home page has a 20pt font while "Get Involved" section on the About page is 17pt. 
- make margins the same for the "about" section on the about page as the other sections - seems like the left margin is much wider than the right margin
- restructure "how it works" section on about page to mimic the blue cards on the home page in spacing for design consistency and placement on page
- make sure you're using components for the header, footer, cards and buttons on this version

**Comment by majkush** [comment]
Writing has been completed and integrated into the Figma files. 
I'm closing this issue as @lrchang2 asked @deepamohan22 to make a new issue to finalize the visual aspect.
