### ISSUE TITLE
Create one-sheet to recruit Python developers

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/access-the-data#230]
### Dependency
- Do we need this? #213 

### Overview
In the 11 October with Bonnie, Lucy, and aj, Bonnie asked that we create a one-sheet of exactly what is needed for our python role that we can use for recruitment.

### Action Items

- [x] Draft the one-sheet
- [ ] finalize with PMs
- [ ] Share with Bonnie

### Additional Resources
[draft of one sheet ](https://docs.google.com/document/d/1XBcjpkacieLdCmXbN9l1dHUjrH5V5GoJ37RrarOz_zM/edit#heading=h.h3n489ip9ddg)

**Comment by lrchang2** [comment]
@nyarly i have consolidated our project one sheet and information from #213, please look over it and provide any edits

**Comment by lrchang2** [comment]
closing issue, dont need to recruit for developers anymore but have a one sheet that we can use for future recruitment
