### ISSUE TITLE
Updating the texts and and adding cards (Landing Page & About Page)

### ISSUE THREAD

**Issue by deepamohan22** [hackforla/access-the-data#235]
**Overview**

 We need to Update the texts and  and add cards in the Hi-Fi  Prototypes (desktop and mobile).

 **Action Items**

  - [x] make all normal (non header) text the same font size. "About Us" section on the Home page has a 20pt font while "Get Involved" section on the About page is 17pt.

 - [x]  make margins the same for the "about" section on the about page as the other sections

- [x]  restructure "how it works" section on about page to mimic the blue cards on the home page in spacing for design consistency and placement on page

- [x] make sure to use components for the header, footer, cards and buttons on this version

 **Resources/Instructions**
https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A16

**Comment by deepamohan22** [comment]
@lrchang2  Hi Lucy,
 I created a new issue and updated the texts and added the blue cards in hi fi wireframes. Please let me know your feedback.
Thanks
<img width="55" alt="Screenshot_20221114_043138" src="https://user-images.githubusercontent.com/102125634/201796838-45c34972-c51d-454a-a41c-42804b6681a7.png">
<img width="190" alt="Screenshot_20221114_043229" src="https://user-images.githubusercontent.com/102125634/201796970-cf84c3ab-c56a-4e05-b703-00bf1fee9b19.png">

**Comment by deepamohan22** [comment]
@lrchang2 
Hi Lucy, One thing I noticed is the "Meet the Team"  in mobile version is also in blue card.  It comes below the 'now added' 3 blue cards. Should I change  its color to the lemon meringue just like  that section in Desktop version?
<img width="54" alt="Screenshot_20221114_050521" src="https://user-images.githubusercontent.com/102125634/201801094-67e3c14b-5439-4838-a2e4-1d8757a78e89.png">

**Comment by lrchang2** [comment]
@deepamohan22 this looks great! thank you for this. and good catch on the "meet the team" section in the mobile. yes i would change it to the same yellow as the desktop version

**Comment by deepamohan22** [comment]
@lrchang2 
Can I close the issue if everything looks fine?
