### ISSUE TITLE
UX Writing for Contact Us Page

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#236]
### Overview
We need to update the text on the contact us page to be more user friendly. 

### Action Items

- [x] Review current text in high fidelity wireframes
- [x] Draft up ideas of how to make page text more user friendly
- [ ] Share ideas and get feedback from PMs and team
- [x] Create version of text based on AtD UX writing guides
- [ ] Review versions of contact us page text with team and get feedback
- [ ] Confirm text 
- [ ] Put in high fidelity wireframe 

### Resources/Instructions
[AtD FIgma](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A16&t=ljQu7HSMMT8KPYC5-0)
[UX writing Guides for AtD](https://github.com/hackforla/access-the-data/wiki/Copy-Guide)

**Comment by bkong** [comment]
@lesUXW Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by lesUXW** [comment]
**Progress:**
- Reviewed current text in high fidelity wireframes
- Drafted up ideas of how to make page text more user friendly
- Contacted Deepa to create version of text based on AtD UX writing guides on both pages of Hi Fi Wireframes (Desktop) and (Mobile). The version is under "Updated text Dec 1, 22."
- Met with Matt on Fri., Dec. 2nd for review and feedback
- Left comments on the Desktop version awaiting review and feedback by PMs and team during Wed., Dec. 7th meeting


**Blockers:**
- N/A


**Availability:** "How much time will you have this week to work on this issue?"
- Currently unemployed, very flexible


**ETA:** "When do you expect this issue to be completed?"
- By the next meeting on Wed., Dec. 14th (after incorporating review and feedback from Dec. 7th meeting)


**Pictures:**
- Below are Desktop and Mobile versions (there's a one-word difference as it's in need of feedback for that part)

![Desktop Dec  1 version](https://user-images.githubusercontent.com/117793784/206289137-9c27be06-0106-42a0-a5fa-d1de6f079c71.png)

![Mobile Dec  1 version](https://user-images.githubusercontent.com/117793784/206289155-41eba846-7107-453d-a59b-a6b8377faec3.png)

**Comment by lesUXW** [comment]
Looked through my notes and realized I had another version. Will ask the team for feedback during Dec. 7th meeting.

**Comment by lesUXW** [comment]
Hi @lrchang2 and @mxajPrice,
I uploaded the latest version of the Contact Us page. There's 2 versions with different navigation and footer text. Please let me know your feedback. Thanks :)

Version 1 - "About, Contact, Get Involved":
![Contact Us UXW Jan  11, 2023 V1 (About, Contact, Get Involved)](https://user-images.githubusercontent.com/117793784/211950003-d611597d-673d-4ce4-b2b6-0d08358c0176.png)

Version 2 - "About Us, Contact Us, Join Us":
![Contact Us UXW Jan  11, 2023 V1 (About Us, Contact Us, Join Us)](https://user-images.githubusercontent.com/117793784/211950285-d36cfb31-dca5-4e05-aa5b-19007b5d29ad.png)

**Comment by mxajPrice** [comment]
Hi @lesUXW, this design does not represent the current information architecture of the site, which is being addressed in #206.  Can you please take a look at the current [information architecture](https://docs.google.com/spreadsheets/d/1BV3TJ-tr2QPjij0IUXxTShtnHgDhAlkQAKIUELXAmWA/edit#gid=1188394452) and let us know if you feel there are any updates needed to the primary and secondary levels?

**Comment by lrchang2** [comment]
@lesUXW 
Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by mxajPrice** [comment]
Complete.
