### ISSUE TITLE
Create Demo Day Presentation Template 

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#241]
### Overview
We need to develop a presentation template for our members to guide them in presenting efficient and clear insights from their work with the team during demo day. 

### Action Items

- [ ] Draft presentation structure to make it 10 minute time limit
- [ ] Put structure into Google Slides presentation for people to copy for their own use 
- [ ] Lay down clearly explanation of the guidelines 

### Resources/Instructions
Notes on objectives for demo days:
- Volunteers practice introducing themselves and talking about what they are working on
- Volunteers practice talking about their work to people without a background in what they do
- The team gets a clear view of where the product currently is

**Comment by mxajPrice** [comment]
There is no longer a need for this.
