### ISSUE TITLE
Website features audit

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/access-the-data#243]
### Dependency 
- #255 

### Overview
We need to go through the website design and list out the implied features that need to be developed.  Once this is done, we need to create issues for each of the features.

### Action Items

- [x] Review [CURRENT Hi fi wireframe](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A27&t=DTbwx9A0SAY8FTQM-0) and list out all of the implied features (ie, a search function, an email forward function for "contact us"
- [ ] Review list with team to make sure everything is covered
- [ ] PMs to create issues for each feature

**Comment by mxajPrice** [comment]
I have started a spreadsheet to start logging features:
https://docs.google.com/spreadsheets/d/1yr5EbdkCGqpW34bTEXlH6gM4n3u9nt9hPlWdzKhdIX8/edit#gid=675655724

**Comment by mxajPrice** [comment]
@lrchang2 and I filled out the spreadsheet but need to ask about a few items at the next Team meeting.

**Comment by lrchang2** [comment]
next step is the confirm home page, which will be done with the team on [March 14 2023](https://github.com/hackforla/access-the-data/issues/63#issuecomment-1468869273)
