### ISSUE TITLE
Quick deploy

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/access-the-data#245]
### Overview
Getting existing version of CKAN up and running where it can be reached via the internet.

### Action Items

Configure and deploy CKAN to AWS ECS

**Comment by lrchang2** [comment]
@nyarly please finish filling out this issue with action items

**Comment by nyarly** [comment]
I'm hoping to get some feedback from @gjagnoor about a missing `.env` file - I can try to track the issue down on my own, but it's a much bigger lift if she can give me pointers.

**Comment by mxajPrice** [comment]
please update your issue with the following info  if you have not already
- Progress: "What is the current status of your project? What have you completed and what is left to do?"
- Blockers: "Difficulties or errors encountered."
- Availability: "How much time will you have this week to work on this issue?"
- ETA: "When do you expect this issue to be completed?"

**Comment by mxajPrice** [comment]
A quick deploy will not be possible, so we are closing this ticket.
