### ISSUE TITLE
New Accent Color for Color Palette

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#248]
### Overview
We need a new color palette because our current color has contrast issues with the text. 

### Action Items
- [x]  Find colors that match current color palette that can be used as a new accent color
- [x]  Check to see that the current text color overlayed has a high enough contrast to be accessible 
- [ ]  Review with team for feedback
- [ ]  Implement new accent color on wireframes

**Comment by deepamohan22** [comment]
@lrchang2 @mxajPrice 
Progress : Working on task 1 
Blockers : No
ETA       : one more week

**Comment by deepamohan22** [comment]
@lrchang2 @mxajPrice 
Completed the first 2 tasks

**Comment by lrchang2** [comment]
based on observation, revisit: 
- background color 
- button color
- text color

**Comment by lrchang2** [comment]
@deepamohan22 Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by deepamohan22** [comment]
@lrchang2 @mxajPrice,
I have three 3 designs to share for today's meeting
Thanks

**Comment by deepamohan22** [comment]
<img width="249" alt="Screenshot 2023-03-29 170912" src="https://user-images.githubusercontent.com/102125634/228695556-fcd45809-bbc1-4b2f-b999-9057912d7ba2.png">
<img width="250" alt="Screenshot 2023-03-29 171119" src="https://user-images.githubusercontent.com/102125634/228695609-aefae4c1-d19c-43db-8f87-18dc2365c049.png">
<img width="249" alt="Screenshot 2023-03-29 171146" src="https://user-images.githubusercontent.com/102125634/228695644-7c11b631-c21c-4e1c-9a9b-bf3a0ddd5792.png">

**Comment by mxajPrice** [comment]
We have decided on light blue!  This issue is complete.
