### ISSUE TITLE
Create Guide for PM work on Wiki

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#249]
### Overview
We need to create a guide for how we run the project as a PM. 

### Action Items
- [ ] Create draft in Drive
   - [ ] Main duties
      - [x] managing work
      - [x] project planning
      - [ ] managing meetings
      - [ ] managing the team
   - [x] team layout
   - [x] tools
   - [x] resources
- [ ] Review draft with other PMs to make sure all content necessary is there
- [ ] Ask UX writer to give comments/clean up
- [ ] Publish to wiki

### Resources/Instructions
[PM Guide Wiki](https://github.com/hackforla/access-the-data/wiki/Product-Project-Management-Guide)
[Website PM Wiki](https://github.com/hackforla/website/wiki/Product-Manager-and-Owner)

**Comment by mxajPrice** [comment]
I am assigning this to myself.  I've started a draft [here](https://docs.google.com/document/d/1wqbmbwcngGTIw30Ikhi5l1JhmErRZ_k5qhe7M08rMdk/edit).

**Comment by mxajPrice** [comment]
I have uploaded what is complete into the wiki and will create a separate issue for what is left to do.
