### ISSUE TITLE
Get Requirements for ADA Compliance

### ISSUE THREAD

**Issue by snooravi** [hackforla/access-the-data#25]
### Overview
We need to have access to WCAG guidance for our website and our courses.  So that we can be in compliance with the city requirements and reach the most people. 

### Action Items

- [ ] Check in with the UI/UX community of practice on the state of their guidance. If it's not completed and the need is immediate start helping the community of practice by doing the following. 
   - [ ] Talk to other teams to see what needs to be done in order for the website to be ADA compliant.
   - [ ] Find team members and/or websites that we have built that are ADA compliant and compile a list of needs for our team.

### Resources/Instructions
[UI/UX community of practice Accessibility Guide](hackforla/UI-UX#16)

**Comment by snooravi** [comment]
UI/UX community of practice is creating templates for this. Ali Kiani will check with Olivia/Bonnie

**Comment by amkiani32** [comment]
@ujunwaa any updates on this?

**Comment by abryant35** [comment]
Here is a link to the UI/UX Accessibility Guide. It is a work in progress. 
https://github.com/hackforla/UI-UX/issues/16
