### ISSUE TITLE
Rewrite and Organize UX Copy Resources 

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#252]
### Overview
We need to provide more information about our ux writing resources to help people understand what we hav.
This is part of epic #273 

### Action Items

- [x] Review wiki page for ux writing
  - [x] Welcome
  - [x] "TOC (Table of Contents)" - A list of what's in the Wiki
  - [x] Brand Voice Tone
    - [x] Deleted "Funny (Example: Medium. Guides for laymen. Conversational tone; straightforward story-telling. Not funny but not too serious; super inviting to beginners; but still professional); Casual; Respectful; Enthusiastic" (2021 version from "Website Copy 11/14/21 Content Frames" Google Doc)
    - [x] Only used Matt's updated Sept. 29, 2022 Brand Voice Tone
  - [x] Brand Voice Chart
    - [x] Example Text
  - [x] Glossary of Terms
    - [x] Language to Use
    - [x] Language to Avoid
  - [x] Nomenclature Audit
    - [x] Findings and Recommendations
    - [x] UX Recruitment Language
    - [x] Hack for LA Page
    - [x] ATD One Sheet
    - [x] GitHub Main Page
    - [x] Website
    - [x] Website Architecture
- [x] Website Copy
  - [x] Decided not to add "Website Copy 11/14/21 Content Frames" Google Doc into Wiki (it was 2 years ago, not as relevant and updated, and contained many workshops materials)
- [x] Review Google Drive contents for additional content to add into the Wiki
  - [x] Decided not to add in "Carousel A/B Testing" Google Slides into Wiki (no longer relevant since not using carousels anymore)
- [x] A section for previous UX Writing research (research will be a link to Aparna's Wiki)
- [x] Custom footer (but it adds it for all wikis, not just this one; would need a decision whether or not to have it)
  - [x] Team decided to keep the footer 
- [x] Add context to current resources that include steps on where to use what resources. (This will be mentioned in the intro to the Wiki.)
- [x] Poll for Access the Data acronym and spaces before and after slashes
  - [x] Result: AtD and no spaces before and after slashes
- [x] Edit intro for UX Research wiki 
- [x] Add "Back to Top" button after each section (can't align it to the right): [Back to Top](#)
- [x] Add section for GitHub Wiki Markdown resources 
- [x] Adding colons into the Writing Guide Voice Chart and asking for feedback about it being used only for Note items
  - [x] Result: Add colons for use under the "Simple" column.
- [x] Add "AtD" and "ATD" to the Glossary of Terms for absolute clarification.
- [x] Add Date Format for this Wiki
- [x] Add memo in intro to update "Version Dates: MM-DD-YYYY by -Name-"

- [x] Guide for writing this Wiki using Markdown --> Share on Slack instead

### Resources/Instructions
[ATD wiki page for ux writing](https://github.com/hackforla/access-the-data/wiki/Copy-Guide)
[Expunge Assist UX writing resources](https://github.com/hackforla/expunge-assist/wiki/Resources)
Reference [Tech Work Experience](https://github.com/hackforla/internship/wiki) Wiki

**Comment by lrchang2** [comment]
@lesUXW 
Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by lesUXW** [comment]
Hi @lrchang2 and @mxajPrice, 

Here's my late update, sorry about this. I'm looking to make the rest of the info similar to how these charts look, and need feedback on whether or not it's likeable:

Access the Data Brand Voice Chart:
![Access the Data Brand Voice Chart](https://user-images.githubusercontent.com/117793784/227071211-bc606e5e-2460-4825-8257-def71ea01a87.png)


UX Glossary so far:
![In Progress Glossary](https://user-images.githubusercontent.com/117793784/227071244-bbaa8db0-acc7-4828-a7bf-5258690d9d1f.png)


(I also joined the meeting just now but it seems it ended early.)
Thanks again!

**Comment by lrchang2** [comment]
thanks @lesUXW ! Definitely show this to the group during this week's meeting and we can give you some feedback

**Comment by lesUXW** [comment]
Progress:

- Adding more info to the new [zeroheight](https://zeroheight.com/8a5e4e33c) platform
- Added a [new page](https://github.com/hackforla/access-the-data/wiki/UX-Writing-Guide-for-ATD) for ATD called "UX Writing Guide for ATD" and it may replace the "Copy" page

Blockers: Less availability this week.

Availability: N/A

ETA: Not sure.

Pictures: N/A

**Comment by mxajPrice** [comment]
aj and Leslie met on 25 April to discuss next steps for this project and getting what is on Zeroheight onto the wiki.  We determined that if there is a common tool (that is free) for style guides that we should try to incorporate that for future UX writers to use.  Leslie is going to poll the UX community via Slack and touch base later.

**Comment by mxajPrice** [comment]
Hi Leslie, please add updates to this issue:

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far.

**Comment by lesUXW** [comment]
Hi @mxajPrice and @Cathyyyyyyyy,

Progress:

- Created a new GitHub Wiki page called ["UX Writing Guide"](https://github.com/hackforla/access-the-data/wiki/UX-Writing-Guide).
- Added the new page to ATD's Team Assets and Tools
- No more Zeroheight or Notion
- Only 1 person responded to the poll. Decided to go with GitHub since the simple code for Markdown may be useful for future UX Writers. Zeroheight or Notion are good platforms for skills in documentation, but seem too much and unnecessary for the simple info we have.

Blockers: N/A
Availability: < 6 hours
ETA: Aiming for the end of next week to have all the current info organized into the one GitHub Wiki page.
Pictures: N/A

**Comment by mxajPrice** [comment]
Hi @lesUXW, please add updates to this issue:

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far.

**Comment by mxajPrice** [comment]
Hey, @lesUXW, the wiki is looking really good!  Can you add a comment here about what you most recently did and what you still have yet to do?

**Comment by lesUXW** [comment]
Hi @mxajPrice, thank you!

Progress: 
- finished inputting all the nomenclature audit into tables in the wiki
- deleted the extra columns to different between the sections, as it was creating unnecessary horizontal scrolling and additional coding
- still combing through different resources to make sure none of them are repeated, because there are a lot of repeated information in the docs

Blockers: N/A

Availability: Min. 6 hours

ETA: N/A

**Comment by mxajPrice** [comment]
Hi @lesUXW , per our conversation last week, can you please list out all of the section of the planned guide so that we can see what is done and what is yet to do?  It's hard to track progress on this without that.

Thanks!

**Comment by lesUXW** [comment]
Hi @mxajPrice, 

Progress:

- Updated task list in this issue.
- Will there be a meeting with Aparna about linking UX Writing research work to her Wiki page?

Blockers: N/A
Availability: N/A
ETA: N/A

Thank you!

**Comment by mxajPrice** [comment]
@lesUXW please give updates to this issue.

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far.

**Comment by lesUXW** [comment]
Hi @mxajPrice, 

Progress: Edited UX Research's Wiki intro
Blockers: N/A
Availability: N/A
ETA: June 28th, 2023

___

For next week, could I do 2 polls for anonymous voting? I'll update the voice charts after the results.

1. ATD vs. AtD
2. Spaces before and after slashes _ / _ (i.e. UX / UI), or no spaces before and after slashes _/_ (i.e. UX/UI)? What do developers think about this, since this could affect coding?

**Comment by lesUXW** [comment]
Hi @mxajPrice,

Progress:
- Added section in intro for "where" to use these resources.
- Added "Back to Top" button after each complete section.
- Added a Research section with a link to Aparna's Research Wiki.
- Added an end section for Markdown tips for this Wiki.
- Added tasks to this Wiki.

**Comment by lesUXW** [comment]
Hi @mxajPrice and @merlinsmagic, this issue is finally complete.

I added the "Website Copy" from Oct. 2022 as a section.

This Wikis should be everything we have for UX Writing.

Thank you again!

**Comment by mxajPrice** [comment]
Thank you so much, Leslie!  Stay in touch! -aj
