### ISSUE TITLE
Reorganize Home Page

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#255]
### Overview
PMs realized that our home page had repetitive information and talked to the team on if we needed to change that. Team decided that we should repurpose some content and align current version with other CKAN websites. 

We want to simply and add a search bar 

### Action Items

- [x] Make space right under header where carousel is into a static section with a search bar
![image](https://user-images.githubusercontent.com/10827101/225640918-cafe9bbd-2634-4d90-b599-5494b9266b73.png)
- [x] Right under the search bar section, replace 3 cards with the "how it works" section from the about page
![image](https://user-images.githubusercontent.com/10827101/225671383-8cb667cc-dc67-4fd7-a75b-d2b69b2f9210.png)
- [x] Delete About section from current home page 

### Resources/Instructions
[Open Swiss Data Website](https://opendata.swiss/en)
[Open Africa Data Website](https://africaopendata.org/)
[ATD Figma](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A27&t=hKumWbTWRfbrbA0r-0 )

**Comment by deepamohan22** [comment]
@lrchang2 , @mxajPrice 
Progress :  Completed the tasks.
Blockers  :  Are we going to keep the carousal in there ?
<img width="245" alt="Screenshot 2023-04-11 125037" src="https://user-images.githubusercontent.com/102125634/231273325-f4379580-2ab7-42f1-b0b3-2613ac16eaaf.png">

**Comment by lrchang2** [comment]
@deepamohan22 No carousel for this version, thanks for clarifying. 
Let's present this during the team meeting tomorrow for final feedback.

**Comment by deepamohan22** [comment]
Sure, Thanks Lucy

**Comment by lrchang2** [comment]
Changes to be made based on the team feedback: 

- Shorten the blue section above so that when you open the website, the next section (white background with words "How It Works") is peaking out above the fold. above the fold 
- Add the words "search datasets..." in the search bar on the home page
