### ISSUE TITLE
ADA Compliance Guide

### ISSUE THREAD

**Issue by ujunwaa** [hackforla/access-the-data#26]
@ujunwaa any updates on this?

_Originally posted by @amkiani32 in https://github.com/hackforla/access-the-data/issues/25#issuecomment-862820680_

Sorry for the delay but I've compiled and referenced the guidelines to follow to keep the website accessible.

https://docs.google.com/document/d/1dFKJlIl5PGXzddXnm7dFCzFTReT8N9-HIq5DDvWlxQ8/edit?usp=sharing

**Comment by abryant35** [comment]
@ujunwaa Thank you for the comprehensive work!
