### ISSUE TITLE
Incorporate designed colors into website

### ISSUE THREAD

**Issue by nyarly** [hackforla/access-the-data#260]
### Overview
As a first step towards making the design live, incorporate the colors for the design into the website code.

**Comment by mxajPrice** [comment]
Code for color palette was updated to [tailwind](https://github.com/hackforla/accessthedata-ckan/blob/main/access-the-data/tailwind.config.js) and javascript.

**Comment by mxajPrice** [comment]
This is complete.

**Comment by nyarly** [comment]
c.f. hackforla/accessthedata-ckan#3
