### ISSUE TITLE
Ask Bonnie about onboarding Tony Delgado

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/access-the-data#261]
### Overview
We have an engineering friend (he and Judson go way back) who would like to help out on Access the Data.  He tried onboarding at the 10 April onboarding but was a little late, missed a direction, and was kicked out for not posting something in the chat.  It looks like there won't be another onboarding until 8 May but Judson could use the help now.

### Questions

- [x] Is there a self-service portal we can use to get him onboarded?
- [ ] OR could I onboard him myself?
- [ ] OR could I get him onto our GitHub and Slack in the meantime to get started before he is onboarded?

**Comment by ExperimentsInHonesty** [comment]
Have him review the [Main onboarding slide deck](https://docs.google.com/presentation/d/1DeVBtptyK6fZTzM4Wo1UX_U0U7H_3YgAz3VOTzMC7ks/)
Have him make sure he has 2FA [HfLA GitHub 2FA](https://docs.google.com/presentation/d/1CVxhSjUbElQx83ZCrWBTBiz7qW7wmydPc99gJLmvejQ/)
Then ill have to turn on the onboarding form.  Currently turned off.  Please let me know by filling out reach Bonnie form again.

**Comment by mxajPrice** [comment]
From Tony on Slack:
OK, here's where things stand:
There's a form that isn't working: [bit.ly/hfla-start-usa](http://bit.ly/hfla-start-usa). I think this is the one you were referring to in the original e-mail. I have added all the information (including the new Slack info) to the AtD roster you had linked to earlier.
My GH account has 2FA, but I do not have an invitation to the project. According to the presentation, I should make a request on a Figma (https://www.figma.com/file/vFt7O5Fa9cctIZPBSuFYxk/Onboarding?node-id=0%3A1), but I suspect this is only useful during the live onboarding.

**Comment by ExperimentsInHonesty** [comment]
@mxajPrice I turned on the form [bit.ly/hfla-start-usa](http://bit.ly/hfla-start-usa) for him.  Tell him to fill it out and that will send him a github invite.  Let me know when he is done so I can turn it off.

**Comment by mxajPrice** [comment]
@ExperimentsInHonesty Tony has gotten the GitHub invite.  You can close the form- thanks! -@mxajprice


From Slack:
TonyDW
Ok. I've accepted the GH invite, so recruiting should be good. I'm still on the road, so I'm going to wait till I get back home to finish any other GH tasks.

**Comment by mxajPrice** [comment]
Tony's onboarding is complete.  Thanks!

**Comment by ExperimentsInHonesty** [comment]
Thanks.  I've closed the form again
