### ISSUE TITLE
Offboard Lucy Chang

### ISSUE THREAD

**Issue by Cathyyyyyyyy** [hackforla/access-the-data#262]
#### Offboard
- [x] Remove from Google calendar invite
- [x] WIKI
  - [x] move to "previous contributors" on team page
- [x] 1password setup
    - [x] Ask admin on Slack to remove from team vaults
       - [x] Access the Data - Data Literacy vault
       - [x] Zoom vault
- [x] Google Drive
   - [x] demote to viewer
- [x] Roster
  - [x] mark as inactive
- [x] GitHub
     - [x] demote member to read only team and remove from [write team](https://github.com/orgs/hackforla/teams/access-the-data-write/members)
- [x] Figma
  - [x] demote to view only
- [x] Remove from Social Media Accounts with role assignment
   - [x] Facebook
- [x] Remove from #access-the-data-leads Slack channel

**Comment by mxajPrice** [comment]
Complete!
