### ISSUE TITLE
Update the Context Chart

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/access-the-data#268]
### Overview
To make it easier to understand where our project is in the great schema, we need to update the previous [context chart](https://github.com/hackforla/access-the-data#project-context) to this [new one](https://user-images.githubusercontent.com/98370780/233212902-b91407e9-ba5e-453d-b5e4-44722a7b0d14.jpg).

### Action Items

- [x] Ask Bonnie if this is something she will want for the organization and if so, what format is preferable
- [x] Recreate this new chart to look professional
- [x] Get Bonnie approval on design

### Resources/Instructions
[HfLA Design Guide](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464-3&t=UjcZ9mr5S2QFavTD-0)
Export in SVG Format, made in Figma
Will need to add a "Programs" box around CEPIA

**Comment by mxajPrice** [comment]
I will be seeing Bonnie in the next [PM CoP meeting](https://github.com/hackforla/product-management/issues/131#issuecomment-1509213977) on Friday, 21 April.  I will ask her then about requirements for the chart if she wants it for Hack for LA.

**Comment by mxajPrice** [comment]
Hi Deepa, we need to make one small addition to the chart.  A box around "Citizen Engagement..." that says "Programs.

Please let us know if you were able to get started on this in Figma:

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far.

**Comment by deepamohan22** [comment]
@mxajPrice, 
Progress: Still working on it
Blockers: No
Availability: 6 hrs.
ETA: Before next Wednesday

**Comment by mxajPrice** [comment]
@deepamohan22 can you please link to the Figma file you are working on here?

**Comment by deepamohan22** [comment]
@mxajPrice 
[https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2-33&t=kKDhpFh8v6RgRAcb-0](url)

**Comment by deepamohan22** [comment]
https://www.figma.com/proto/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?type=design&node-id=6787-40571&scaling=scale-down&page-id=2%3A33

**Comment by mxajPrice** [comment]
Notes from the 17 May team meeting:
   - Clarify that UN is a separate entity
   - Make sure Hack for LA is separate from UN, SDGs, and DPGs
   - Make a space for HfLA Programs, which 'Citizen Engagement...' will fit inside of (because there will be other program areas Bonnie will want to add
   - There should be space for each project to add themself inside of the program areas

**Comment by deepamohan22** [comment]
@mxajPrice 
https://www.figma.com/proto/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?type=design&node-id=6821-34547&scaling=scale-down&page-id=2%3A33

Please let me know your thoughts.

**Comment by mxajPrice** [comment]
Unfortunately, Bonnie was not available on Friday so I was not able to look at it with her.

In the meantime can you please add the following program areas?

- Vote/Representation
- Civic Tech Infrastructure
- Justice
- Social Safety Net
- Workforce Development
- Environment

She may want to rename some of these but we can demonstrate how they fit in for now.  Also, as an example, please add Access the Data to show how a project can demonstrate where they are in our infrastructure.

Thanks!  Feel free to Slack if you have any questions.

**Comment by mxajPrice** [comment]
Hi @deepamohan22, were you able to make progress this week?  

I showed what we have to Bonnie last Friday and she likes it.

Another ask, and I hope this will "balance out" the middle of this chart, but can you list the [Communities of Practice](https://github.com/hackforla/communities-of-practice)?

**Comment by deepamohan22** [comment]
@mxajPrice 
Updated the Context Chart.  
https://www.figma.com/proto/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?type=design&node-id=6821-34547&scaling=scale-down&page-id=2%3A33
Let me know.
Thanks

**Comment by mxajPrice** [comment]
@deepamohan22 will not be available 12-23 June.

**Comment by mxajPrice** [comment]
Hi @deepamohan22, I spoke with Bonnie today.  She says that, for now, we should leave off the "Digital Public Goods" section because that is not in the immediate development horizon.  She also said that it would need to be clear that the projects, not the programs, are aligned with the SDGs.  

Also, from my own perspective, it currently looks like projects are separate from programs instead of being nested within.  It should be clear that Access the Data fits into the Citizen Engagement Program.

I am wondering if, given Bonnie's notes, we should not make two versions of this chart.  One that leaves off the Projects and SDGs, and another one that lists ALL of the current projects and their relationships to the SDGs.  The reason I say this is that the first one would seldom need updating, and the second would need to be updated every time a new project is introduced.  What do you think?

**Comment by merlinsmagic** [comment]
Hi @deepamohan22, 

Can we get an update on this issue when you have a moment?

Progress: “What is the current status of your project? What have you completed and what is left to do?”
Blockers: “Difficulties or errors encountered.”
Availability: “How much time will you have this week to work on this issue?”
ETA: “When do you expect this issue to be completed?”
Pictures: “Add any pictures of the visual changes made to the site so far.

**Comment by deepamohan22** [comment]
@mxajPrice, @merlinsmagic 
Progress: still working 
Blockers : yes
ETA.        : by next Wednesday

**Comment by deepamohan22** [comment]
@mxajPrice , 
Sorry for the late response.
I have doubts regarding the issue. It would be nice to go through the issue in today’s meeting to get a clear  picture.

Thanks

**Comment by deepamohan22** [comment]
https://www.figma.com/proto/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?type=design&node-id=7062-30816&t=MJGTEbKohPgBw44K-0&scaling=scale-down&page-id=2%3A33

**Comment by deepamohan22** [comment]
Updated   context chart design

https://www.figma.com/proto/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?type=design&node-id=7108-30717&t=zUi3if0HGLAcR66M-0&scaling=scale-down&page-id=2%3A33

**Comment by deepamohan22** [comment]
Updated Context chart
https://www.figma.com/proto/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?type=design&node-id=7108-30717&t=cWistggPjTX7rs4o-1&scaling=scale-down&page-id=2%3A33&mode=design

**Comment by mxajPrice** [comment]
I spoke with Bonnie in the PM meeting today and she noted that there are some restrictions on using the UN logo:
https://www.un.org/sustainabledevelopment/news/communications-material/

Also, it was very difficult to read.  Can the text be made larger?

She also said for it to be used by all of HfLA that it needs to reflect the "Hack for LA look and feel" on the website and onboarding slides.  So, when we have updated the UN and SDG logos and made the text readable, I think we will call this 'done' for AtD and make an issue for it in the website repo for it to be updated by a designer there.  They don't have any designers at the moment so I don't want to wait on them to be able to use it for ourselves.

**Comment by deepamohan22** [comment]
@mxajPrice 
I have updated the design by:
Increased the text size
Removed the UN logo

**Comment by deepamohan22** [comment]
https://www.figma.com/proto/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?type=design&node-id=7164-30709&t=Llt3utWmzitjM0sw-0&scaling=scale-down-width&page-id=2%3A33

**Comment by deepamohan22** [comment]
@mxajPrice 
Updated design of Context Chart
https://www.figma.com/proto/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?type=design&node-id=7226-33039&t=ZdhzxIdQcenamlMl-0&scaling=scale-down&page-id=2%3A33

**Comment by mxajPrice** [comment]
Deepa is out until October and we will go forward with what we have. -aj
