### ISSUE TITLE
Identifying the Information Architecture (IA) for the Search Bar feature, using CKAN benchmarking 

### ISSUE THREAD

**Issue by Aparna1Gopal** [hackforla/access-the-data#274]
### Overview
- The Information Architecture (IA) of the 'Search Bar feature' is being built based on the options available across the three benchmarked CKAN websites 
- The 3 benchmarked CKAN websites are as follows: 
   - [opendata.swiss](https://opendata.swiss/en/dataset?q=)
   - [openAfrica](https://africaopendata.org/dataset?q=)
   - [Data.Gov](https://catalog.data.gov/dataset?q=)

### Dependancies
[Usability Testing the Information Architecture (IA) of the Search Bar feature](https://github.com/hackforla/access-the-data/issues/282)

### Action Items
- [x] Review the three benchmarked CKAN Websites
- [x] Identify the options to showcase to the team 
- [x] Create the Workshop board including voting using FigJam/Miro/Google Workspace
- [x] Conduct the Workshop during the Team Meeting [Participatory Action Research] 
- [x] Identify the common themes aligned with the product & team needs
- [x] Debrief with the team & finalize the required product features
- [x] Document the Information Infrastructure using MS Excel or Google Sheets 
- [x] Present the research findings to the team & discuss next steps
- [x] Update [Wiki](https://github.com/hackforla/access-the-data/wiki/Research:-Information-Architecture-(IA)-for-Search-Bar-feature,-using-CKAN-benchmarking)
- [x] Review with PMs & close issue 

### Resources/Instructions

- [Google Drive](https://drive.google.com/drive/u/1/folders/1VJosqzA0PWZZoQmiQZ8KW9YggWkPpj_W)
- [FigJam Collaborative Workspace](https://www.figma.com/file/ZYFMovoeMhFPcYQzR1r7dR/ATD---UXR-Workshop?node-id=0%3A1&t=m33HvpZ9EU7644Kq-1)
- [Development - Features](https://docs.google.com/spreadsheets/d/1yr5EbdkCGqpW34bTEXlH6gM4n3u9nt9hPlWdzKhdIX8/edit#gid=675655724)
- [Prioritization Workshops](https://www.nngroup.com/articles/5-ux-workshops/)
- [Foundational UX Workshop Activities](https://www.nngroup.com/articles/workshop-activities/)
- [The process and benefits of organizing a UX workshop](https://adamfard.com/blog/ux-workshop#:~:text=So%20what%20is%20a%20UX,detailed%20roadmaps%20for%20achieving%20them.)
- [How to Write Compelling User Research Insights in 6 Steps](https://dscout.com/people-nerds/writing-user-insights)
- [Wiki](https://github.com/hackforla/access-the-data/wiki/Research:-Information-Architecture-(IA)-for-Search-Bar-feature,-using-CKAN-benchmarking)

TEMPLATE FOR PROJECT PROGRESS

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by Aparna1Gopal** [comment]
**Notes**

- All search functions on the home/landing page lead to this Information Architecture on the second page. Hence it was vital to identify the tree/IA of the Search Bar feature. 
- As per feedback from developers on the need to start building all the features: 
   - Impact on Issue: [Website features audit](https://github.com/hackforla/access-the-data/issues/243)
   - Relevant google drive [Development - Features](https://drive.google.com/drive/u/1/folders/1FcQlIYpWU7qiBG8aEYrGMH2d3akuaFrI)
   - Relevant google sheets [Development - Features](https://docs.google.com/spreadsheets/d/1yr5EbdkCGqpW34bTEXlH6gM4n3u9nt9hPlWdzKhdIX8/edit#gid=675655724)

- Completed FigJam collaborative workshop during last week's team meeting (on April 26,2023)

**Comment by Aparna1Gopal** [comment]
**Notes - documenting process**

FigJam Workshop – Identifying the Information Architecture of the Search Bar tool/feature on the landing page 

Data Collection process
•	Workshopping the features based on the benchmarked CKAN websites 
•	The input was given by the respective stakeholders on the team, based on the domains they came from (Example: Product & Project Managers, UX Designer, UX Writer, Developers) 

Data Analysis process 
•	Benchmark 5-7 common features 
•	Identify how many times these common features showed up on the FigJam 
•	Identify any outliers (document them & identify the need to incorporate them - example: html feature by developers)
_Vote on that & identify on the following:_
•	Number of features required for the first iteration of the MVP (to ship the product) 
•	What are the features? 
 
Once the above is finalized, the tree can be constructed on a spreadsheet

**Comment by Aparna1Gopal** [comment]
Progress: "What is the current status of your project? What have you completed and what is left to do?"
- Presented Research Findings to team, durning last week's team meeting. 
- Currently updating the Wiki 
Blockers: "Difficulties or errors encountered."
- None 
Availability: "How much time will you have this week to work on this issue?"
2-3 hours 
ETA: "When do you expect this issue to be completed?"
End of this week 
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by Aparna1Gopal** [comment]
**Notes**
- Updated [Wiki](https://github.com/hackforla/access-the-data/wiki/Research:-Information-Architecture-(IA)-for-Search-Bar-feature,-using-CKAN-benchmarking)
- This Issue is complete & can be closed

**Comment by Aparna1Gopal** [comment]
**Notes**
- Updated [Wiki](https://github.com/hackforla/access-the-data/wiki/Research:-Information-Architecture-(IA)-for-Search-Bar-feature,-using-CKAN-benchmarking)
- This Issue is complete & can be closed

**Comment by mxajPrice** [comment]
this is complete.
