### ISSUE TITLE
Create page for Mission Statement, onesheet, and history of AtD

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/access-the-data#277]
### Overview
Part of epic #273 
We need to make a space where people can see the "why" of this project.  

### Action Items

- [x] Mission Statement
- [x] Sustainable Development Goal
- [x] One sheet
- [ ] Project History

### Resources
- [Original One sheet](https://docs.google.com/document/d/1_CxBQ_ku4sanPIWKtPyENJ4E9hQKETQs8IWAOCzgqqk/edit)

**Comment by mxajPrice** [comment]
Started writing history at https://docs.google.com/document/d/1Ay93Xir4HFe9XYnZgWjOjzpwf39H_CAnBU5CBTNEnkU/edit

**Comment by mxajPrice** [comment]
Mission statement:
Access the Data is helping communities find the data they need to participate in local government policy-making.

Vision statement:
Access the Data is a tool that any municipality can adopt to make it easy for their citizens to find, navigate, and understand local government data.

**Comment by mxajPrice** [comment]
[SDG 16](https://sdgs.un.org/goals/goal16)
- Promote peaceful and inclusive societies for sustainable development, provide access to justice for all and build effective, accountable and inclusive institutions at all levels

Target 16.8
- Broaden and strengthen the participation of developing countries in the institutions of global governance

Indicator 16.8.1
- Proportion of members and voting rights of developing countries in international organizations

**Comment by merlinsmagic** [comment]
Confirmed. Still in progress.

**Comment by mxajPrice** [comment]
Draft of history is complete.  Will need to review and polish next.

https://docs.google.com/document/d/1Ay93Xir4HFe9XYnZgWjOjzpwf39H_CAnBU5CBTNEnkU

**Comment by merlinsmagic** [comment]
@mxajPrice what is status of this issue?

Progress: “What is the current status of your project? What have you completed and what is left to do?”
Blockers: “Difficulties or errors encountered.”
Availability: “How much time will you have this week to work on this issue?”
ETA: “When do you expect this issue to be completed?”
Pictures: “Add any pictures of the visual changes made to the site so far.

**Comment by mxajPrice** [comment]
I got some really good feedback from @Aparna1Gopal.  When I wrote the first draft I was envisioning this being mostly read by other PMs at Hack for LA to share experiences.  However, if this is something to be published to our wiki it will need to include an overview and be rewritten in a different voice so that others can add to the document later if needed.

**Comment by mxajPrice** [comment]
New draft has been started [here](https://docs.google.com/document/d/100pcK0wlGrQMy9PPwej7CmfTC2IEFod5S0Y7OcIFcUM/edit).

**Comment by merlinsmagic** [comment]
Hi @mxajPrice,

Do we have any new updates for this issue?

Progress: “What is the current status of your project? What have you completed and what is left to do?”
Blockers: “Difficulties or errors encountered.”
Availability: “How much time will you have this week to work on this issue?”
ETA: “When do you expect this issue to be completed?”
Pictures: “Add any pictures of the visual changes made to the site so far.

**Comment by mxajPrice** [comment]
In 18 October weekly meeting we discussed some things that need to go into documentation:
- That the site is based on CKAN and the CKAN template
- Going in we had design for the site before we knew the entire site-map that CKAN would bring with it, so some pages still need design and design incorporation
- Let the next PM know they will want to develop version 1 with a developer as well as a designer, not just one or the other

**Comment by mxajPrice** [comment]
The wiki has been updated.  There will be sections that discuss the history of the project but there won't be a separate space just for project history.
