### ISSUE TITLE
Update Research wiki

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/access-the-data#279]
### Overview
We need to make our [research wiki page](https://github.com/hackforla/access-the-data/wiki/Research) a space where anyone can find:
- What research has been done at Access the Data
- The methods and tools our researchers are using
-  User testing

The final results of our research should be clearly showcased on the research page, with a link to deeper information on another page or pages.

### Action Items
- [x] Create [landing page](https://github.com/hackforla/access-the-data/wiki/Research) for research
   - Display research that has already been completed, with links to methods/years
   - Methods / Discovery
      - [Benchmarking](https://github.com/hackforla/access-the-data/wiki/Research:-Benchmarking-data-points-%5Bcomparative-analysis-of-CKAN-websites%5D)
      - Personas: [Data Expert](https://github.com/hackforla/access-the-data/wiki/Research:-Data-Expert), [Community Activist](https://github.com/hackforla/access-the-data/wiki/Research:-Community-Activist)
- [x] Research guides links
   - [x] Website tracking
   - [x] User testing (see if the CoP has one already)
- [x] Cross-check all the content & links : including if all pages are named/numbered/ linked correctly
- [x] Review with PM & close issue

### Resources 
HfLA Project research wikis:
- [Internship](https://github.com/hackforla/internship/wiki)
- [Food Oasis user stories](https://github.com/hackforla/food-oasis/wiki/User-Stories)
- [Lucky Parking research and discovery overview](https://github.com/hackforla/lucky-parking/wiki/Research-and-Discovery-Overview)
- [Lucky Parking UX Responsibilities](https://github.com/hackforla/lucky-parking/wiki/UX-Responsibilities)
- [TDM Calc Usability Testing Overview](https://github.com/hackforla/tdm-calculator/wiki/Usability-Testing-Overview)
- [Design Systems research history](https://github.com/hackforla/design-systems/wiki/Background#research-history)

TEMPLATE FOR PROJECT PROGRESS

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by Aparna1Gopal** [comment]
Progress: "What is the current status of your project? What have you completed and what is left to do?"
Setup structure of the [Home Page](https://github.com/hackforla/access-the-data/wiki/Research)
 
Blockers: "Difficulties or errors encountered."
None 

Availability: "How much time will you have this week to work on this issue?"
1-2 hours 

ETA: "When do you expect this issue to be completed?"
4-5 weeks (as working on it one page at a time, based on the requirements of the PM team) 

Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by Aparna1Gopal** [comment]
Progress: "What is the current status of your project? What have you completed and what is left to do?"
- Finalised structure for landing page of the Research Wiki - created the structure & tree
- Created sub-pages to link to the landing/main page 
- 70% of this wiki is complete
Remaining Items:
- [ ] Discuss Introduction section with Team 
- [ ] Provide one line introductions for each of the sub-pages. Example: Research By:Type: Benchmarking --- Definition of benchmarking 
- [ ] Cross-check all the links, if all pages are linked correctly
- [ ] Cross-check all the content. If all the content is housed in its correct location 
- [ ] Review with PM & close issue

Blockers: "Difficulties or errors encountered."

Availability: "How much time will you have this week to work on this issue?"
1-2 hours 

ETA: "When do you expect this issue to be completed?"
2-3 weeks 

Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by Aparna1Gopal** [comment]
Progress: "What is the current status of your project? What have you completed and what is left to do?"
- Reviewed progress with PM during last week's team meeting https://github.com/hackforla/access-the-data/issues/279#issuecomment-1563865443. Identified areas/gaps to improve on. 
- Remaining Items:
  - [ ] Introduction - use content from PM Wiki page & adapt to Research Page 
  - [ ] All UX Definitions - use Nielson Norman & User Interviews as Source for 'Definitions'
  - [ ] Usability Testing Guides Page - Link only the completed guides in Google docs not the Github issues. Give an extra section in the footer linking to the UI/UX CoP Guides Board + other Usability testing Issues 
  - [ ] Cross-check all the links, if all pages are named & linked correctly
  - [ ]  Cross-check all the content. If all the content is housed in its correct location
  - [ ] Review with PM & close issue

Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by Aparna1Gopal** [comment]
Progress: "What is the current status of your project? What have you completed and what is left to do?"
- Reviewed progress with PM during last week's team meeting: https://github.com/hackforla/access-the-data/issues/279#issuecomment-1579986392
- Remaining Items:
  - [x] Introduction - use content from PM Wiki page & adapt to Research Page 
  - [x] All UX Definitions - use Nielson Norman & User Interviews as Source for 'Definitions'
  - [ ] Usability Testing Guides Page - Link only the completed guides in Google docs not the Github issues. Give an extra section in the footer linking to the UI/UX CoP Guides Board + other Usability testing Issues 
  - [x] Consent Forms Guides Page [Add an additional section on the Research Landing Page for Consent Form Templates (moved consent forms from under guides to its own section). It is a replicable template to be used for all PII user research conducted within ATD.]
  - [ ] Cross-check all the links, if all pages are named & linked correctly
  - [ ]  Cross-check all the content. If all the content is housed in its correct location
  - [ ] Review with PM & close issue

Blockers: "Difficulties or errors encountered."
- As requested by PM during team meeting for Usability Testing Guides Page - Link only the completed guides in Google docs not the Github issues- was required. 
- However none of the Guides in progress have a google doc started or completed. 
- Have made some adaptations based on currently available resources: https://github.com/hackforla/access-the-data/wiki/Research-By:-Type:-Usability-Testing-(Moderated-&-Unmoderated)
- Need to discuss next steps at the next team meeting

Availability: "How much time will you have this week to work on this issue?"
1-2 hours

ETA: "When do you expect this issue to be completed?"
End of June 2023

Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by Aparna1Gopal** [comment]
Progress: "What is the current status of your project? What have you completed and what is left to do?"

- Reviewed required in progress items on https://github.com/hackforla/access-the-data/issues/279#issuecomment-1590608429
- Updated the Usability Testing Guides page with external available best practices & guides for usability testing
- Linked the in-house Hack for LA Guides page Kanban board to this wiki page. To give an overview & access to currently in-progress guides 
Remaining Items:
- [ ] Usability Testing Guides Page - Add best practices/guides from available online resources. Give an extra section in the footer linking to the UI/UX CoP Guides Board + other Usability testing Issues
- [ ] Consent Forms Guides Page [Add an additional section on the Research Landing Page for Consent Form Templates (moved consent forms from under guides to its own section). It is a replicable template to be used for all PII user research conducted within ATD.]
- [ ] Cross-check all the links, if all pages are named & linked correctly
- [ ] Cross-check all the content. If all the content is housed in its correct location
- [ ] Review with PM & close issue

Blockers: "Difficulties or errors encountered."

Availability: "How much time will you have this week to work on this issue?"
1-2 hours

ETA: "When do you expect this issue to be completed?"
End of June 2023

Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by Aparna1Gopal** [comment]
- [x] Consent Forms Guides Page [Add an additional section on the Research Landing Page for Consent Form Templates (moved consent forms from under guides to its own section). It is a replicable template to be used for all PII user research conducted within ATD.] : https://github.com/hackforla/access-the-data/wiki/Research-Guides:-Consent-Forms
- [ ] Cross-check all the links, if all pages are named & linked correctly
- [ ] Cross-check all the content. If all the content is housed in its correct location
- [ ] Review with PM & close issue

Blockers: "Difficulties or errors encountered."

Availability: "How much time will you have this week to work on this issue?"
1-2 hours

ETA: "When do you expect this issue to be completed?"
End of June 2023

Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by Aparna1Gopal** [comment]
### Notes

- Based on feedback at last team meeting (https://github.com/hackforla/access-the-data/issues/279#issuecomment-1611590351) & in lieu of consistency, the footer of all the Research Wiki pages were made the same. The Research Overview page in the footer of some of the pages were removed to maintain consistency with the rest (Attached screenshot)

<img width="1426" alt="Screenshot 2023-07-05 at 7 32 24 pm" src="https://github.com/hackforla/access-the-data/assets/86335455/07c90dc7-fea6-455a-96f9-8bd3ab6785ac">

- This issue is complete & can be closed

**Comment by merlinsmagic** [comment]
This issue now complete
