### ISSUE TITLE
Old and Proposed Workshop Content Review

### ISSUE THREAD

**Issue by snooravi** [hackforla/access-the-data#28]
### Overview
We need to review all the previously delivered educational materials so that we can spot any improvements or other changes we would like to make.

### Action Items
- [x] Review Julien's old workshops and proposal and put notes into "Review of Julien Materials" doc
- [x] add comments/thoughts into into the prior years presentation (intro to community data 101)

### Resources/Instructions

[intro to community data 101](https://docs.google.com/presentation/d/1unJzaZJoM7pt7KeVN5byALF4EaQVNgzD-PunyOgBkGM/edit#slide=id.g7c402794b6_0)
[Review of Julien Materials](https://docs.google.com/document/d/1BAT-2WzUz0KOz63RxqZB8EJQwu-81g10s66FB1aB4Ow/edit?usp=sharing)

[Materials provided by Julien - drive folder](https://drive.google.com/drive/u/1/folders/1rNEFJEl7uzali9xB3mnp8Pvb9CI3KES9)
[Sarah's Analysis of 2020s workshops and Proposal for Workshop Improvements to Julien](https://docs.google.com/document/d/1j2kDVi_brwA8vlmIHRR9yrbndWM-Z72A9-sMt_X52g0/edit)
[Access the Data's Community Data workshops content Proposal [Working Draft]](https://docs.google.com/document/d/1zTYQzvlmEHNxEq10hbArYJ3QxP7OTC1J1zAFWiKu6pA/edit#)

[Template for workshop requirements](https://docs.google.com/spreadsheets/d/129lPcOlsn0FkNYFm0wWH0sSWB7TAHb7GUeWPjgWZ9y8/edit#gid=0)

**Comment by Jeremy-D** [comment]
Bonnie left notes on another issue related to this issue https://github.com/hackforla/access-the-data/issues/19#issuecomment-882153473

**Comment by ExperimentsInHonesty** [comment]
@Jeremy-D Sarah Alyssa and I reworded and reworked this issue so that the directive would be clearer.  Can you give us an update on if you understand it, and what your Availability and ETA to completion will be if you do.

**Comment by ExperimentsInHonesty** [comment]
@Jeremy-D Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by Jeremy-D** [comment]
I'm going to call this done based on the meeting Sarah, Malak and I had last week. Next step is to make an outline for the first presentation centered around 311 data.
