### ISSUE TITLE
First Click Testing of Search Bar feature, using CKAN benchmarking

### ISSUE THREAD

**Issue by Aparna1Gopal** [hackforla/access-the-data#282]
### Dependencies
- [x] #274

### Overview

- The Information Architecture (IA) of the 'Search Bar feature' has been built based on CKAN benchmarking & the team's collaborative prioritisation workshops

- The Search Bar features currently prioritised are documented in this [Wiki](https://github.com/hackforla/access-the-data/wiki/Research:-Prioritization-Workshop:-Information-Architecture-(IA)-of-Search-Bar-feature,-using-CKAN-benchmarking)

### Action Items
- [x] Review [Wiki - IA for Search Bar feature](https://github.com/hackforla/access-the-data/wiki/Research:-Prioritization-Workshop:-Information-Architecture-(IA)-of-Search-Bar-feature,-using-CKAN-benchmarking)
- [x] Complete Research Plan 
- [x] Identify resources available across free plan of usability testing tools in the market (Example: Optimal Workshop, Usability Hub, Maze)
- [x] Select Usability tool most appropriate for study from available market options 
- [x] Create Pilot Usability Test 
- [x] Review Research Plan with Team 
- [x] Pilot Test with Team 
- [x] Review & revise based on team feedback 
- [x] Create participant recruitment Slack template message & share with team for feedback
- [x] Recruit research participants
- [x] Close & complete usability testing once required sample size is reached 
- [x] Analyse data from the usability testing
- [x] Identify research findings, insights, actionable recommendations
- [x] Present the research findings to the team & discuss next steps
- [x] Update [Wiki](https://github.com/hackforla/access-the-data/wiki/Research:-First-Click-Testing-of-Search-Bar-feature,-using-CKAN-benchmarking)
- [x] Review with PMs & close issue

### Resources/Instructions
- [Google Drive](https://drive.google.com/drive/u/1/folders/1GQBU9DZz_h4cb8GndLoaj8gMGxN9t2rZ)
- [Wiki](https://github.com/hackforla/access-the-data/wiki/Research:-First-Click-Testing-of-Search-Bar-feature,-using-CKAN-benchmarking) 
- [First Testing Guide](https://www.userinterviews.com/ux-research-field-guide-chapter/first-click-testing) 
- [UX task flows vs. user flows](https://medium.com/erika-harano/ux-task-flows-versus-user-flows-as-demonstrated-by-pancakes-896e78a98026)

TEMPLATE FOR PROJECT PROGRESS

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by Aparna1Gopal** [comment]
Progress: "What is the current status of your project? What have you completed and what is left to do?"
- Started working on the Research Plan 
- Identified the tool to conduct the Tree Testing - Optimal Workshop 

Blockers: "Difficulties or errors encountered."
None 

Availability: "How much time will you have this week to work on this issue?"
3-4 hours 

ETA: "When do you expect this issue to be completed?"
2-3 weeks including participant recruitment, data collection & data analysis 

Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by Aparna1Gopal** [comment]
Progress: "What is the current status of your project? What have you completed and what is left to do?"
Working on the end to end Research Plan
Setting up study: Tree Testing in Optimal Workshop

Blockers: "Difficulties or errors encountered."
Due to free version of usability testing tool, need to work within the constraints (as number of studies/participants/study questions) are limiting. Hence prioritising accordingly. 

Availability: "How much time will you have this week to work on this issue?"
3-4 hours

ETA: "When do you expect this issue to be completed?"
2-3 weeks including participant recruitment, data collection & data analysis

Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by Aparna1Gopal** [comment]
Progress: "What is the current status of your project? What have you completed and what is left to do?"
- Working on the end to end Research Plan
- Setting up study: First click testing in Optimal Workshop
- Pilot Test the study with the team 
- Explore through the previous studies conducted regarding personas & identify the appropriate survey question to track data expert versus data novice's experience with using data.

Blockers: "Difficulties or errors encountered."
Due to free version of usability testing tool, need to work within the constraints (as number of studies/participants/study questions) are limited. Hence prioritising accordingly. 
Due to the free version of usability testing tool & the constraints, the usability testing method needed to be changed from tree testing to first click testing to accomodate the constants, yet yield rich impactful research results & insights. 

Availability: "How much time will you have this week to work on this issue?"
3-4 hours

ETA: "When do you expect this issue to be completed?"
2-3 weeks including participant recruitment, data collection & data analysis

Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by Aparna1Gopal** [comment]
Progress: "What is the current status of your project? What have you completed and what is left to do?"
- Reviewed required in progress items on https://github.com/hackforla/access-the-data/issues/282#issuecomment-1590615662
- Completed Research Plan
- Based on feedback & review at last team meeting, revised the Usability Test. Updated this on the Research Plan & Optimal Workshop (Usability testing tool)
- Completed Slack recruitment message. Need to review this message with Team during meeting, revise & start recruiting research participants. 
- Ask for feedback on recruitment methods & specific channels that can be used for recruitment. Ask for team's help with cross-posting this recruitment message across their known networks to get a diverse pool of research participants. 

Blockers: "Difficulties or errors encountered."
Due to free version of usability testing tool, need to work within the constraints (as number of studies/participants/study questions) are limited. Hence prioritising accordingly.
Due to the free version of usability testing tool & the constraints, the usability testing method needed to be changed from tree testing to first click testing to accomodate the constants, yet yield rich impactful research results & insights.

Availability: "How much time will you have this week to work on this issue?"
3-4 hours

ETA: "When do you expect this issue to be completed?"
2-3 weeks including participant recruitment, data collection & data analysis

Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by Aparna1Gopal** [comment]
### Slack Participant Recruitment Message 

:wave: Hi! We would like your help with some user testing :arrow_down: 
:alarm_clock: This would take only 2-3 minutes of your time. Many thanks! 
:memo: Project: Access the Data, a product of Hack for LA

**Comment by Aparna1Gopal** [comment]
Progress: "What is the current status of your project? What have you completed and what is left to do?"
- Revised the Usability Test, Research Plan & Slack Message based on feedback during team meeting 
- Recruiting research participants via Slack. Currently posted on HfLA's slack channels: UI/UX, PM, Engineering & General. Slack Message: https://github.com/hackforla/access-the-data/issues/282#issuecomment-1611419715
- Will need to iterate based on response rate & number of participants recruited. 
- 

Blockers: "Difficulties or errors encountered."
- Research participant recruitment 

Availability: "How much time will you have this week to work on this issue?"
2-3 hours 

ETA: "When do you expect this issue to be completed?"
2-3 weeks including participant recruitment, data collection & data analysis
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by Aparna1Gopal** [comment]
### Notes 
For Report Writing 

https://openfieldx.com/ux-discovery-activities-user-journey-mapping/#:~:text=Task%20flows%20focus%20on%20steps,real%20decision%20points%20and%20actions.

https://www.simplilearn.com/tutorials/ui-ux-career-resources/user-flows-in-ux#:~:text=There%20are%20three%20types%20of,wire%20flows%2C%20and%20user%20flows.

https://usabilityhub.com/guides/first-click-testing

https://blog.optimalworkshop.com/first-click-testing/

https://www.userinterviews.com/ux-research-field-guide-chapter/first-click-testing

**Comment by Aparna1Gopal** [comment]
Progress: "What is the current status of your project? What have you completed and what is left to do?"
- Completed recruiting participants for the usability testing. Link to test [here](https://izbes7gi.optimalworkshop.com/chalkmark/1fdhmznd)
- Closed test 
- Need to start analysing results 
- Write report & present results 

Blockers: "Difficulties or errors encountered."

Availability: "How much time will you have this week to work on this issue?"
4-5 hours 

ETA: "When do you expect this issue to be completed?"
2-3 weeks 

Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by Aparna1Gopal** [comment]
### Notes

**Resources/Guide to user journey mapping**

https://webflow.com/blog/user-journey

https://careerfoundry.com/en/blog/ux-design/how-to-make-customer-journey-map-with-template/

**Comment by Aparna1Gopal** [comment]
Progress: "What is the current status of your project? What have you completed and what is left to do?"
- Started analysing results
- Collecting resources for project report & deliverables - https://github.com/hackforla/access-the-data/issues/282#issuecomment-1635357486

Blockers: "Difficulties or errors encountered."
None.
Identifying appropriate deliverables & time taken to complete the same

Availability: "How much time will you have this week to work on this issue?"
4-5 hours

ETA: "When do you expect this issue to be completed?"
2 weeks

Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by Aparna1Gopal** [comment]
Progress: "What is the current status of your project? What have you completed and what is left to do?"
- Analysing results, cross-referencing it with the Research Plan
- Collecting resources for project report & deliverables - https://github.com/hackforla/access-the-data/issues/282#issuecomment-1635357486

Blockers: "Difficulties or errors encountered."
None.
Identifying appropriate deliverables & time taken to complete the same

Availability: "How much time will you have this week to work on this issue?"
4-5 hours

ETA: "When do you expect this issue to be completed?"
2 weeks

Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by Aparna1Gopal** [comment]
Progress: "What is the current status of your project? What have you completed and what is left to do?"

Analysing results, cross-referencing it with the Research Plan
Collecting resources for project report & deliverables - https://github.com/hackforla/access-the-data/issues/282#issuecomment-1635357486
Woke simultaneously on the UXR Roadmap for Semester 2, 2023 simultaneously, so time was distributed across these two projects.

Blockers: "Difficulties or errors encountered."
None.
Identifying appropriate deliverables & time taken to complete the same

Availability: "How much time will you have this week to work on this issue?"
4-5 hours

ETA: "When do you expect this issue to be completed?"
2 weeks

Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by merlinsmagic** [comment]
Hi @Aparna1Gopal ,

Do we have any new updates for this issue?

Progress: “What is the current status of your project? What have you completed and what is left to do?”
Blockers: “Difficulties or errors encountered.”
Availability: “How much time will you have this week to work on this issue?”
ETA: “When do you expect this issue to be completed?”
Pictures: “Add any pictures of the visual changes made to the site so far.

**Comment by Aparna1Gopal** [comment]
Progress: “What is the current status of your project? What have you completed and what is left to do?”
- Completing data analysis, identifying clear trends & patterns 
- Started the research report 

Blockers: “Difficulties or errors encountered.”
None

Availability: “How much time will you have this week to work on this issue?”
2-3 hours 

ETA: “When do you expect this issue to be completed?”
2 weeks ( aiming for a research presentation of findings last week of August) 

Pictures: “Add any pictures of the visual changes made to the site so far.
<img width="1139" alt="Screenshot 2023-08-16 at 8 31 08 pm" src="https://github.com/hackforla/access-the-data/assets/86335455/4632b463-d44e-4b61-ae1a-24ccff0a4ce3">
Data Collection-Analysis Snapshot 

<img width="886" alt="Screenshot 2023-08-16 at 8 32 08 pm" src="https://github.com/hackforla/access-the-data/assets/86335455/e8aec7c4-8522-48ed-b41d-c2492d321896">
Draft Research Report notes Snapshot

**Comment by merlinsmagic** [comment]
Hi @Aparna1Gopal do we have new updates for this issue?

Progress: “What is the current status of your project? What have you completed and what is left to do?”
Blockers: “Difficulties or errors encountered.”
Availability: “How much time will you have this week to work on this issue?”
ETA: “When do you expect this issue to be completed?”
Pictures: “Add any pictures of the visual changes made to the site so far.

**Comment by Aparna1Gopal** [comment]
Progress: “What is the current status of your project? What have you completed and what is left to do?”
- Completed data analysis
- Started the research report
- Left to do: Research Presentation to present to team, complete Wiki


Blockers: “Difficulties or errors encountered.”
None

Availability: “How much time will you have this week to work on this issue?”
1 hour (as traveling this upcoming week)

ETA: “When do you expect this issue to be completed?”
2 weeks (aiming for a research presentation of preliminary findings in the second week of September), as traveling in the first week of September

Pictures: “Add any pictures of the visual changes made to the site so far.

**Comment by Aparna1Gopal** [comment]
**Notes**

**Resource to draft the comprehensive Research Report** 

[How to run a quantitative usability test](https://userresearchacademy.substack.com/p/how-to-run-a-quantitative-usability)
And use it to continuously prove your impact

[NIKKI ANDERSON-STANIER](https://substack.com/@userresearchacademy)

**Comment by Aparna1Gopal** [comment]
Progress: “What is the current status of your project? What have you completed and what is left to do?”
- Completed data analysis
Started the research report
- Left to do: Research Presentation to present to team, Research Report, Complete Wiki

Blockers: “Difficulties or errors encountered.”
Traveling, thus time constraints

Availability: “How much time will you have this week to work on this issue?”
3-4 hours

ETA: “When do you expect this issue to be completed?”
1 week (aiming for a research presentation of research findings & next steps for MVP)

Pictures: “Add any pictures of the visual changes made to the site so far.

**Comment by Aparna1Gopal** [comment]
Progress: “What is the current status of your project? What have you completed and what is left to do?”
Completed: Data analysis, Research Presentation to present to team, Research Report
Left to do: Research Report + Wiki + Documentation in the google drive

Blockers: “Difficulties or errors encountered.”
Traveling, thus time constraints

Availability: “How much time will you have this week to work on this issue?”
3-4 hours

ETA: “When do you expect this issue to be completed?”
1-2 weeks 

Pictures: “Add any pictures of the visual changes made to the site so far.

**Comment by Aparna1Gopal** [comment]
Progress: “What is the current status of your project? What have you completed and what is left to do?”
Completed: Research findings presented to team today
Left to do: Started Wiki, Updating all Documentation in the google drive

Blockers: “Difficulties or errors encountered.”
Traveling last week, thus time constraints

Availability: “How much time will you have this week to work on this issue?”
3-4 hours

ETA: “When do you expect this issue to be completed?”
1 week

Pictures: “Add any pictures of the visual changes made to the site so far.

**Comment by mxajPrice** [comment]
Hi @Aparna1Gopal, were you able to work on the wiki this week?

**Comment by Aparna1Gopal** [comment]
Progress: “What is the current status of your project? What have you completed and what is left to do?”
Completed: Data collection, analysis, research findings & next steps presented to the team
Left to do: 
- [ ] Complete Wiki 
- [ ] Updating all relevant documentation in the ATD google drive. Review all documentation. Download documentation from all relevant testing tools that were used to conduct the research. 
- [ ] Review the Wiki with PM & close issue

Blockers: “Difficulties or errors encountered.”
None

Availability: “How much time will you have this week to work on this issue?”
3-4 hours

ETA: “When do you expect this issue to be completed?”
1 week

Pictures: “Add any pictures of the visual changes made to the site so far.

**Comment by Aparna1Gopal** [comment]
Progress: “What is the current status of your project? What have you completed and what is left to do?”
Completed: Data collection, analysis, research findings & next steps presented to the team
Left to do: 
- [ ] Updating all relevant documentation in the ATD google drive. Review all documentation. Download documentation from all relevant testing tools that were used to conduct the research. 
- [ ] Complete Wiki 
- [ ] Review the Wiki with PM & close issue


Blockers: “Difficulties or errors encountered.”
None

Availability: “How much time will you have this week to work on this issue?”
3-4 hours

ETA: “When do you expect this issue to be completed?”
1 week

Pictures: “Add any pictures of the visual changes made to the site so far.

**Comment by mxajPrice** [comment]
Wiki looks good, great job!
