### ISSUE TITLE
Locate original website art

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/access-the-data#291]
### Overview
The graphic files on our Figma are too small a resolution to put onto the website.  We need to find the original files.

### Action Items
- [x] Ask the Website team if those graphics come from their project
- [x] Ask the UX/UI Community of Practice
- [ ] Ask Bonnie if there is a stockpile somewhere

**Comment by mxajPrice** [comment]
No one on the website team has responded.  I will try the UX/UI CoP next.

<img width="786" alt="Screenshot 2023-09-05 at 11 30 04" src="https://github.com/hackforla/access-the-data/assets/98370780/7a68b201-b588-4107-857d-c766ba776a32">

**Comment by mxajPrice** [comment]
<img width="791" alt="Screenshot 2023-09-05 at 11 30 58" src="https://github.com/hackforla/access-the-data/assets/98370780/ede6f606-5352-41e9-bc75-e6220e41db73">

**Comment by mxajPrice** [comment]
It seems UX/UI does not know either.  Will reach out to Bonnie/admin next...

![Screenshot 2023-09-06 at 17 43 20](https://github.com/hackforla/access-the-data/assets/98370780/30a844d1-02bd-4ccc-b3c3-2e12d4b22e82)

**Comment by mxajPrice** [comment]
Bonnie also didn't recognize the art.  I reached out to Lucy and she said it came from a plug-in for Figma that allows you to use art for free.  When I looked in Figma I found the source was [Blush](https://www.figma.com/community/plugin/838959511417581040/Blush), which states that all artwork if free for personal and commercial use but that you need a paid subscription for high-res images.

<img width="823" alt="Screenshot 2023-09-08 at 11 22 40" src="https://github.com/hackforla/access-the-data/assets/98370780/e6769740-e38e-481b-8770-96b8ab644d88">

For the MVP, we will go forward with the low-res solutions and leave a note in the project close-out report that original artwork will need to be created to replace what is there.

**Comment by ExperimentsInHonesty** [comment]
@mxajPrice I don't know where these images came from. They were never on the website or any other project that I am aware of.
