### ISSUE TITLE
Create Ops wiki page

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/access-the-data#294]
### Overview

We need to create an ops wiki page so that new ops engineers have the basic information they need to start contributing to V1.

### Resources/References
- [Lucky Parking Developer contributing guide](https://github.com/hackforla/lucky-parking/wiki/Developer-Contributing-Guide)
- [Lucky Parking DEV Responsibilities](https://github.com/hackforla/lucky-parking/wiki/DEV-Responsibilities)
- [Lucky Parking Review Pull Requests](https://github.com/hackforla/lucky-parking/wiki/DEV-Responsibilities)
- [Food Oasis Developers wiki](https://github.com/hackforla/food-oasis/wiki/Developers)
- [TDM Calculator Software Architecture and Development](https://github.com/hackforla/tdm-calculator/wiki/Software-Architecture-and-Development)
- [Design Systems Developer History](https://github.com/hackforla/design-systems/wiki/Background#developer-history)

**Comment by nyarly** [comment]
Check out https://github.com/hackforla/accessthedata-ckan/wiki/Operations, which is also linked in the main wiki Sidebar
