### ISSUE TITLE
Create project card for Access the Data

### ISSUE THREAD

**Issue by snooravi** [hackforla/access-the-data#3]
### Dependency
This can get closed when the issue has been completed on the Hack for LA website team
https://github.com/hackforla/website/issues/1315

### Overview
Provide collateral for the hackforla.org website

### Action Items
- [x]   Gather items
  - [x]  600 x 400 image
     - [x]  Alt image text
  - [x]  Name of project
  - [x]  A blurb about the project
  - [x]  Links (github, slack channel url, Testing Site, Live Site, etc.)
  - [x]  Any resources for a Getting Started link (a link to a wiki, readme(s) or both)
  - [x] Leadership
     - [x] Name
     - [x] Role
     - [x] Slack Member ID
     - [x] GitHub handle
  - [x]  What you are looking for skills wise #4 
  - [x] Vertical: Citizen Engagement
  - [x] Partners
  - [x] Technologies
  - [x] Location
  - [x]  Status: Active
- [ ]   Add project card 

### Resources/Instructions
See project cards on the hackforla.org website

**Comment by ExperimentsInHonesty** [comment]
600 x 400 image
 Alt image text
 Name of project
 A blurb about the project: 
 Links (github, slack channel url, Testing Site, Live Site, etc.)
 Any resources for a Getting Started link (a link to a wiki, readme(s) or both)
 Leadership
 Name
 Role
 Slack Member ID
 GitHub handle
 What you are looking for skills wise #4
 Vertical: Citizen Engagement
 Partners
 Technologies
 Location
 Status: Active

**Comment by ExperimentsInHonesty** [comment]
Note: the hero image comes from here, we will need to provide credit if we continue to use the image https://thenounproject.com/term/dashboard/1035313/

**Comment by qiqicodes** [comment]
repo ID: 330800079

Identification ID is found here:
https://api.github.com/repos/hackforla/access-the-data

Next time, can we have the repo ID provided in the issue? Also the wiki link to how to get the repo ID?
