### ISSUE TITLE
Assel, Lucy, Alyssa need access to Figma Account

### ISSUE THREAD

**Issue by asselabilova** [hackforla/access-the-data#30]
@asselabilova abilovadesign@gmail.com 
@abryant35 bryanta574@gmail.com
@lrchang2 lrchang2@illinois.edu

**Comment by ExperimentsInHonesty** [comment]
@ExperimentsInHonesty Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by ExperimentsInHonesty** [comment]
Still need to add Lucy and Alyssa

**Comment by ExperimentsInHonesty** [comment]
At the next team meeting each person on this issue needs to claim a designer number, update the title in 1password vault  for the account
Example: 
from: designer56 Figma login - unassigned
to: designer56 Figma login - Bonnie

**Comment by lrchang2** [comment]
Alyssa and Lucy have both chosen designer accounts. closing out issue
