### ISSUE TITLE
Get Recommendation from Bonnie for AJ

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/access-the-data#303]
### Overview
AJ could use a LinkedIn recommendation to help with xyr job search.  

### Action Items
- [ ] Bonnie review AJ's draft and make adjustments if desired
- [ ] AJ review and approve Bonnie's recommendation
- [ ] Bonnie submit recommendation on [AJ's LinkedIn](https://www.linkedin.com/in/mxajprice/)

### AJ's Draft recommendation

I had the pleasure of working with AJ at Hack for LA where xe wore many hats.  As a product manager, AJ was able to organize and execute the requirements of our Access the Data product.  Through continuous exploration and user interviewing, AJ was able to identify opportunities and build a product roadmap.

As a technical project manager, AJ worked with a team of designers, researchers, and engineers to make sure we were hitting our targets and staying on schedule, making adjustments and communicating changes wherever there were issues.  Xyr stellar documentation and communication made it easy to understand where we were at on our progress and what shifts needed to be made to ensure we were heading towards our desired outcomes.

In addition to xyr work on Access the Data, AJ also revamped and led our Engineering Community of Practice (CoP).  AJ automated many of the processes needed for leading the Engineering CoP and built in a cadence for communication and leadership.  AJ also built a mentorship program and worked with a team of junior engineers to build other programming for the community that included a speaker series, networking events, and community lightning talks.  AJ used community survey data to pave a path for continuous exploration and improvement not only for our Engineering CoP, but for our other CoPs as well.  AJ’s contributions will continue to have an effect long past xyr tenure at Hack for LA.

**Comment by kcoronel** [comment]
hey @mxajPrice, transcribing what Bonnie asked me to write here from our Admin Weekly Meetings. 

1. Can you please use this [Letter of Recommendation](https://docs.google.com/document/d/1O99jhN6oFiKv9ZtjmTDEbzxvcDa9_MNe3yBTasslP2g/template/preview) template and add it to this issue. 
2. Utilizing the template- can you tell Bonnie what it is that you would like communicated in this recommendation. It may be things that are not clearly articulated in your LinkedIn, or things that should be highlighted from a recommender, or even things to re-emphasize from your about section.

**Comment by ExperimentsInHonesty** [comment]
@mxajPrice the draft is great.  What it's lacking is anything that says what it's like to work with you.  What are the soft skills that you would like me to highlight in this doc.

Example: Empathic leader

**Comment by mxajPrice** [comment]
Empathetic leader would be great. I would also like an emphasis on my adaptability and versatility in working with technical teams as well as non-technical stakeholders.

**Comment by mxajPrice** [comment]
@bonniewolfe checking in to see if you have had any time for this.  Thanks.

**Comment by mxajPrice** [comment]
Hi @ExperimentsInHonesty, checking in to see if you are still able to submit this recommendation.

**Comment by mxajPrice** [comment]
I want to take this off my list of things to track so I am going to close this as not planned.
