### ISSUE TITLE
Summarize Data Resources

### ISSUE THREAD

**Issue by Jeremy-D** [hackforla/access-the-data#31]
### Overview
In order to design a data literacy curriculum or data literacy website we need to have a fairly in depth understanding of the available data resources. Writing a brief summary of each data resource with a note about how it can contribute to either the workshops or the website. 

### Action Items

- [x] Update schema in data resources file
- [x] Summarize all of the links in the provided resources file.
- [x] Review summaries with project lead
- [x] Release dependency on issue #17 
- [x] Watch through session 3 on [EmpowerLa](https://data-liaison-neighborhood-councils-lahub.hub.arcgis.com/pages/session-3) 

### Resources/Instructions
[Data Resources] (https://docs.google.com/spreadsheets/d/1JKMw4BT-i4gUC73lRXxI5g4yWOxhQ5OOAhG58Ch1LqY/edit#gid=431474547)

**Comment by ExperimentsInHonesty** [comment]
https://github.com/hackforla/access-the-data/issues/17#issuecomment-887844403

**Comment by ExperimentsInHonesty** [comment]
@Jeremy-D @MalakH21 Please provide update on how ya'll are doing on the sorting out the labels to sort the various resources
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by snooravi** [comment]
@Jeremy-D can we add these: https://www.lamayor.org/Homelessness-Data-and-Dashboards

**Comment by ExperimentsInHonesty** [comment]
@Jeremy-D @MalakH21 Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA
