### ISSUE TITLE
Suggest Resources for the First Workshop

### ISSUE THREAD

**Issue by Jeremy-D** [hackforla/access-the-data#32]
### Dependency
#47 

### Overview
In order to run a succesful workshop we will need to have a variety of resources that people can use. After gathering context and summarizing the data resources, the analyst team will be able to make suggestions on which resources might be most beneficial for the first workshop. 

### Action Items
- [x] Provide curriculum developer with a list of resources and rational for why it might be useful.

### Resources/Instructions
[Data Resource Summaries](https://docs.google.com/spreadsheets/d/1JKMw4BT-i4gUC73lRXxI5g4yWOxhQ5OOAhG58Ch1LqY/edit#gid=431474547)

**Comment by snooravi** [comment]
@Jeremy-D Please provide update:

Progress
Blockers
Availability
ETA

**Comment by ExperimentsInHonesty** [comment]
Hi @Jeremy-D I was checking our the document you provided above.  It looks like its some articles about 311 data analysis.  Please also provide a list of all the 311 data resources available, which I think you already have via the data sources workshop, but it would be good to have all in this issue so that we can keep the information in one place.

Please provide update on when you think you will a summary of each data source/ and the value of each of these research documents.
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by Jeremy-D** [comment]
HI @ExperimentsInHonesty and @snooravi I added the 311 data resources to the in [workshop plan ](https://docs.google.com/document/d/1W1WLLVAN8izVGgm5CsUwEZ43xc_2upMeXR3Q8l9GNd4/edit#) that's in progress. That should cover the first point of this ticket.

The point of including the [Articles and Resources](https://docs.google.com/document/d/1ETtQ45YuzQIlAsIX3A69KaLx9awsqucBRfqkgzn4hJI/edit) document is to get more context about how 311 data is used so that we will be able to create some useful examples with the data sources that we have access to. I should have at least one useful example for next week's meeting. 

I won't be able to make it to the meeting tonight so let me know if there are any questions.

**Comment by snooravi** [comment]
@Jeremy-D happy to do that. do you mind clarifying what that second point was referring to tho? is the the how-to videos for the pre-work or the activities during the sessions? i think we worked through at least one example in the workshop outline, right? [311 Data Workshop Outline](https://docs.google.com/document/d/1W1WLLVAN8izVGgm5CsUwEZ43xc_2upMeXR3Q8l9GNd4/edit#heading=h.ulbyr8p783iz)

**Comment by Jeremy-D** [comment]
@snooravi What I was thinking was examples using data from the open data portal, but actually we did cover this with the examples we have in the [how to guide](https://docs.google.com/document/d/1c4HsQkk24zRFg_lrca5BCI88o8gNYbCiyD_mkjZE5Tg/edit) that you and Malak put together. When I wrote that previous comment I wasn't sure how we were going to go about making the examples, but the how to guide looks great!
