### ISSUE TITLE
WEEKLY Clean up labels for all issues 

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#33]
### Dependency
4/26/22

### Overview
Need to organize issues on board to have the right associating labels so we can manage velocity, capacity, delivery, and recruitment. 

### Action Items

- [x] Make the label for "size: missing"
- [x] Make a label for "dependency missing" and add it to any issue in the icebox that does not have a dependency
- [x] make search filter to check for issues that do not have have a label for size, role, and feature
- [ ] Go through the issues and check to see that there is no open issues without the following type of labels:
- [all issues that have size missing or size assigned](https://github.com/hackforla/access-the-data/issues?q=is%3Aissue+is%3Aopen+-label%3A%22size%3A+missing%22+-label%3A%22size%3A+1+pt%22+-label%3A%22size%3A+2+pts%22+-label%3A%22size%3A+3+pts%22+-label%3A%22size%3A+5+pts%22+-label%3A%22size%3A+8+pts%22+-label%3A%22size%3A+13%2B+pts%22+)
- [all issues that have role missing or role assigned](https://github.com/hackforla/access-the-data/issues?q=is%3Aopen+is%3Aissue+-label%3A%22role%3A+data+analyst%22+-label%3A%22role%3A+product+management%22+-label%3A%22role%3A+project+management%22+-label%3A%22role%3A+UX%2FUI%22+-label%3A%22role%3A+research%22+-label%3A%22role%3A+design%22+-label%3A%22role%3A+content%22+-label%3A%22role%3A+org%22+-label%3A%22role%3A+missing%22++-label%3A%22role%3A+ux+writing%22++-label%3A%22role%3A+engineering%22+)
- [all issues that have feature missing or feature assigned](https://github.com/hackforla/access-the-data/issues?q=is%3Aopen+is%3Aissue+-label%3A%22feature%3A+missing%22+-label%3A%22feature%3A+ADA%2FWCAG+Compliance%22+-label%3A%22feature%3A+administrative%22+-label%3A%22feature%3A+design+system%22+-label%3A%22feature%3A+Ecosystem+Map%22+-label%3A%22feature%3A+website%22+-label%3A%22feature%3A+workshops%22+-label%3A%22feature%3A+content%22+-label%3A%22feature%3A+expert+interview%22+-label%3A%22feature%3A+github+-+wiki+maintenance%22+-label%3A%22feature%3A+org+review%22+-label%3A%22feature%3A+personas%22+-label%3A%22feature%3A+PM+review%22+-label%3A%22feature%3A+product+requirements%22+-label%3A%22feature%3A+storyboarding%22+-label%3A%22feature%3A+usability+testing%22+-label%3A%22feature%3A+user+research%22+-label%3A%22feature%3A+user+stories%22+-label%3A%22feature%3A+wireframes%22+-label%3A%22feature%3A+1password%22+-label%3A%22p-feature%3A+contact%22+-label%3A%22p-feature%3A+get+involved%22+-label%3A%22p-feature%3A+landing+page%22+-label%3A%22p-feature%3A+mailing+list%22+-label%3A%22p-feature%3A+navigation%22+-label%3A%22p-feature%3A+sponsors+page%22+-label%3A%22feature%3A+process+documentation%22+-label%3A%27feature%3A+recruitment%22+label%3A%22feature%3A+recruitment%22)
- [ ] Go through the issues and check to see that there is a label for the following types of labels:
- [all issues that are missing size](https://github.com/hackforla/access-the-data/issues?q=is%3Aissue+is%3Aopen+label%3A%22size%3A+missing%22)
- [all issues that are missing role](https://github.com/hackforla/access-the-data/issues?q=is%3Aopen+is%3Aissue+label%3A%22role%3A+missing%22)
- [all issues that are missing feature](https://github.com/hackforla/access-the-data/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+missing%22)
- [ ] Go through the issues and check to see that there is a label for the following types of labels:
- [all issues with no project](https://github.com/hackforla/access-the-data/issues?q=is%3Aissue+is%3Aopen+no%3Aproject)
- [all issues with no milestone](https://github.com/hackforla/access-the-data/issues?q=is%3Aopen+is%3Aissue+no%3Amilestone+label%3A%22milestone%3A+missing%22)
- [ ] Perform weekly label check using this template
```
Go through the issues and check to see if X is missing or assigned
size:
role:
feature:
 Go through the issues and check to see that there is a label missing:
size:
role:
feature:
Check to see if there are any issues not yet on the project
no project:
no milestone:
```

### Resources 
https://github.com/hackforla/access-the-data/issues
https://github.com/hackforla/access-the-data/labels

**Comment by lrchang2** [comment]
[all issues that are missing size](https://github.com/hackforla/access-the-data/issues?q=is%3Aissue+is%3Aopen+label%3A%22size%3A+missing%22)

**Comment by lrchang2** [comment]
set up size labels using Fibonacci 
1,2,3,5,8,13 
1 point = 6 hours 
2 points = 12 hours
3 points = 18 hours
5 points = 30 hours
8 points = 48 hours
13 points = 78 hours

Have assignees tell us availability and eta of issue delivery and see if it aligns with the points

**Comment by ExperimentsInHonesty** [comment]
This issue will get reassigned and reviewed every week

**Comment by abryant35** [comment]
Issues have been updated to have correct labels.

**Comment by lrchang2** [comment]
Go through the issues and check to see that there is a label for the following types of labels:
all issues that have size missing or size assigned
all issues that have feature missing or feature assigned
all issues that have role missing or role assigned
 Go through the issues and check to see that there is a label for the following types of labels:
all issues that are missing size
all issues that are missing role
all issues that are missing feature
all issues with no project

**Comment by ExperimentsInHonesty** [comment]
there is only one issue missing labels.  It looks like an issue from Sarah that she has not finished. I moved it to the New Issue approval column and added the missing label labels.

**Comment by lrchang2** [comment]
Go through the issues and check to see if X is missing or assigned

size: 1/9
role: 1/7
feature: 1/3
Go through the issues and check to see that there is a label missing:

size: 1/0
role: 1/0
feature: 1/0
Check to see if there are any issues not yet on the project

no project: 1/0

**Comment by ExperimentsInHonesty** [comment]
size missing: 2
role missing: 1 (a new issue made by sarah that has nothing in it)

**Comment by lrchang2** [comment]
no size: 2/9
no role: 0/3
no feature: 0/7

size missing: 2/0
role missing: 1/0
feature missing: 0/0
no project: 0/0
no milestone: 3

**Comment by lrchang2** [comment]
Go through the issues and check to see if X is missing or assigned
size: 0/9
role: 0/3
feature: 0/7

Go through the issues and check to see that there is a label missing:
size: 1/1  (a new issue made by sarah that has nothing in it)
role: 1/0  (a new issue made by sarah that has nothing in it)
feature: 0/0

Check to see if there are any issues not yet on the project
no project: 0/0

**Comment by lrchang2** [comment]
Go through the issues and check to see if X is missing or assigned
size: 0/9
role: 0/3
feature: 0/7

Go through the issues and check to see that there is a label missing:
size: 1/1  (a new issue made by sarah that has nothing in it)
role: 1/0  (a new issue made by sarah that has nothing in it)
feature: 0/0

Check to see if there are any issues not yet on the project
no project: 0/0
no milestone: 1/0  (a new issue made by sarah that has nothing in it)

**Comment by lrchang2** [comment]
for all issues with label "role: UX/UI" replace with either "role: research" or "role: design" so we can delete label. 

- [all issues with the "role: UX/UI"](https://github.com/hackforla/access-the-data/labels/role%3A%20UX%2FUI)

"role: UX/UI": 9/19 - relabeled all open issues

**Comment by lrchang2** [comment]
Go through the issues and check to see if X is missing or assigned
size: 0/0
role: 0/0
feature: 0/0

Go through the issues and check to see that there is a label missing:
size: 1/0  (a new issue made by sarah that has nothing in it)
role: 1/0  (a new issue made by sarah that has nothing in it)
feature: 0/0

Check to see if there are any issues not yet on the project
no project: 0/0
no milestone: 1/0  (a new issue made by sarah that has nothing in it)

**Comment by lrchang2** [comment]
Go through the issues and check to see if X is missing or assigned
size: 0/0 
role: 0/0 
feature: 5/0 - fixed; "feature: recruitment" added 

Go through the issues and check to see that there is a label missing:
size: 1/0  (a new issue made by sarah that has nothing in it)
role: 1/0  (a new issue made by sarah that has nothing in it)
feature: 0/0

Check to see if there are any issues not yet on the project
no project: 0/0
no milestone: 1/0  (a new issue made by sarah that has nothing in it)

**Comment by lrchang2** [comment]
during PM meeting, fixed an issue that was assigned to sarah. need to ask UX research team about size for issue

**Comment by mxajPrice** [comment]
Go through the issues and check to see if X is missing or assigned
size:
role:
feature:
 Go through the issues and check to see that there is a label missing:
size:
role:
feature:
Check to see if there are any issues not yet on the project
no project:
no milestone:

**Comment by lrchang2** [comment]
Go through the issues and check to see if X is missing or assigned
size: 0/0
role: 0/0
feature: 0/0
 Go through the issues and check to see that there is a label missing:
size: 1/0
role: 0/0
feature: 0/0
Check to see if there are any issues not yet on the project
no project: 0/0
no milestone: 0/0

**Comment by lrchang2** [comment]
Go through the issues and check to see if X is missing or assigned
size: 0/0
role: 0/0
feature: 0/0
 Go through the issues and check to see that there is a label missing:
size: 1/0
role: 0/0
feature: 0/0
Check to see if there are any issues not yet on the project
no project: 0/0
no milestone: 0/0

**Comment by lrchang2** [comment]
Go through the issues and check to see if X is missing or assigned
size: 0/0
role: 0/0
feature: 0/0
 Go through the issues and check to see that there is a label missing:
size: 1/0
role: 0/0
feature: 0/0
Check to see if there are any issues not yet on the project
no project: 0/0
no milestone: 0/0

**Comment by lrchang2** [comment]
Go through the issues and check to see if X is missing or assigned
size: 0/0
role: 0/0
feature: 0/0
 Go through the issues and check to see that there is a label missing:
size: 1/0
role: 0/0
feature: 0/0
Check to see if there are any issues not yet on the project
no project: 0/0
no milestone: 0/0

**Comment by lrchang2** [comment]
Go through the issues and check to see if X is missing or assigned
size: 0/0
role: 0/0
feature: 0/0
 Go through the issues and check to see that there is a label missing:
size: 1/0
role: 0/0
feature: 0/0
Check to see if there are any issues not yet on the project
no project: 0/0
no milestone: 0/0

**Comment by lrchang2** [comment]
Go through the issues and check to see if X is missing or assigned
size: 0/0
role: 0/0
feature: 0/0
 Go through the issues and check to see that there is a label missing:
size: 1/0
role: 0/0
feature: 0/0
Check to see if there are any issues not yet on the project
no project: 0/0
no milestone: 0/0

**Comment by lrchang2** [comment]
Go through the issues and check to see if X is missing or assigned
size: 0/0
role: 0/0
feature: 0/0
 Go through the issues and check to see that there is a label missing:
size: 0/0
role: 0/0
feature: 0/0
Check to see if there are any issues not yet on the project
no project: 0/0
no milestone: 0/0

**Comment by mxajPrice** [comment]
2022.7.11 - all In Progress issues have appropriate labels.

**Comment by mxajPrice** [comment]
We don't need to keep this task as a separate issue, it is now included in the PM weekly agenda.
