### ISSUE TITLE
Develop Brand Guide for All Content Creation

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#39]
### Dependencies 
~#52~ 
~#53~ 
~#54~

### Overview
We need a branding guide to make the Access the Data brand understandable and replicable. 

### Action Items
All elements of the branding guide needs to be ADA compliant #26 . 

- [x] Redesign current Access the Data Logo #52 
   - [x] Logo study of organizations that work with data literacy 
- [x] Color palette #53 
- [x] Typography #54
   - [x] Typography hierarchy fonts needed for ADA compliance
- [ ] Illustrations / Photography*
- [ ] Iconography*
- [ ] Voice and tone - for language and emotion

*secondary needs 
### Resources/Instructions
[Web Content Accessibility Guidelines](https://www.w3.org/TR/WCAG20/)

Depreciated assets
~All work for branding guide is condensed in the [current draft of guide](https://docs.google.com/presentation/d/1Fuc_OrS5Jb2ocpDkJJ3bFwdLfYjkUBpwiVKQ1tpePok/edit#slide=id.p). Guide also contains Content Template Guide #22 and Front-End Style Guide #40~

[Figma](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A8) where the Design System is being created:

**Comment by ExperimentsInHonesty** [comment]
people assigned want clarity on Personas #27 before they proceed.

**Comment by mxajPrice** [comment]
We have the baseline of what we need for now.
