### ISSUE TITLE
Role Identification

### ISSUE THREAD

**Issue by snooravi** [hackforla/access-the-data#4]
### Dependency
When we need more people

### Overview
We need to build a team for the Data Literacy Project site.

### Action Items
- [ ] Review the roles document
- [x] Identify initial list
- [ ] Add requirements to current needs doc

#### Template
```
### Audit Week of 2022-01-08
- [ ] Sufficient number of Issues in prioritized backlog for each role (that match the most important milestones)

#### Product
- [ ] No. of issues: 
   - [ ] [link to issues](https://github.com/hackforla/access-the-data/projects/1?card_filter_query=label%3A%22role%3A+product+management%22)
- [ ] Total No. of points ____ story points: 
- [ ] How many resources do we currently have?
- [ ] Do math on what you need
   - [ ] __  points / 2 resources =  ___ weeks. 
   - [ ] __ points / 3 resources = ___ weeks. 
- [ ] Links to role posting issues

#### Design
- [ ] No. of issues: 
   - [ ] [link to issues](https://github.com/hackforla/access-the-data/projects/1?card_filter_query=label%3A%22role%3A+design%22)
- [ ] Total No. of points ____ story points: 
- [ ] How many resources do we currently have?
- [ ] Do math on what you need
   - [ ] __  points / 2 resources =  ___ weeks. 
   - [ ] __ points / 3 resources = ___ weeks. 
- [ ] Links to role posting issues

### Research 
- [ ] No. of issues: __ (Ice Box)
   - [ ] [link to issues](https://github.com/hackforla/access-the-data/projects/1?card_filter_query=label%3A%22role%3A+research%22
)
- [ ] Total No. of points ____ story points: 
- [ ] How many resources do we currently have?
- [ ] Do math on what you need
   - [ ] __  points / 2 resources =  ___ weeks. 
   - [ ] __ points / 3 resources = ___ weeks. 
- [ ] Links to role posting issues
   - [ ] 

#### Engineering 
- [ ] No. of issues: 
  - [ ] [link to issues]
- [ ] Total No. of points ____ story points: 
- [ ] How many resources do we currently have?
- [ ] Do math on what you need
   - [ ] __  points / 2 resources =  ___ weeks. 
   - [ ] __ points / 3 resources = ___ weeks. 
- [ ] Links to role posting issues
   - [ ]

#### Data Analyst
- [ ] No. of issues:  
   - [ ] [link to issues](https://github.com/hackforla/access-the-data/projects/1?card_filter_query=label%3A%22role%3A+data+analyst%22)
- [ ] Total No. of points ____ story points: 
- [ ] How many resources do we currently have?
- [ ] Do math on what you need
   - [ ] __  points / 2 resources =  ___ weeks. 
   - [ ] __ points / 3 resources = ___ weeks. 
- [ ] Links to role posting issues
   - [ ] 

```

### Resources/Instructions
OLD ~[General Role Definitions](https://docs.google.com/document/d/1X6d6-Sm_QDQPobiRfqachCSajAOpqRLVUsdCnczhhts/edit#heading=h.7brglf3y33hh
)~
[Current list of roles](https://github.com/hackforla/civic-opportunity/tree/master/roles-1)

[Project Recruiting Current Needs Sample - 100Automations](https://docs.google.com/spreadsheets/d/1xnrwTL4kCFhecLQmXwFWVPyWjgc3DC6aQYWq8ZF_QDI/edit#gid=0
)
[Role posting](https://github.com/hackforla/data-science/projects/2#card-55546893)

**Comment by snooravi** [comment]
Need: 
- PM
- DS (research and data crunching)
- UX lead (for survey building)
- any one interested in educational materials

**Comment by snooravi** [comment]
Created note on DS board for a Data Analyst

**Comment by snooravi** [comment]
Created note on UI/UX board for UX Researcher for [Competitive Analysis](https://github.com/hackforla/access-the-data/issues/8#issue-815158676)

**Comment by ExperimentsInHonesty** [comment]
@abryant35 please add UI/UX designer opportunity to the open roles board https://github.com/hackforla/UI-UX/projects/3

**Comment by abryant35** [comment]
@ExperimentsInHonesty Can you add me to the open roles boards?

**Comment by snooravi** [comment]
updated to look for 2 UI/UX and UI Designer

**Comment by lrchang2** [comment]
need: 

- [ ] 2 PM (workshop and website) 
- [ ] data analyst
- [ ] content writers 
- [ ] developers

**Comment by lrchang2** [comment]
### Audit Week of 2022-01-08
- [ ] Sufficient number of Issues in prioritized backlog for each role (that match the most important milestones)

#### Product
- [ ] No. of issues: 
   - [ ] [link to issues](https://github.com/hackforla/access-the-data/projects/1?card_filter_query=label%3A%22role%3A+product+management%22)
- [ ] Total No. of points ____ story points: 
- [ ] How many resources do we currently have?
- [ ] Do math on what you need
   - [ ] __  points / 2 resources =  ___ weeks. 
   - [ ] __ points / 3 resources = ___ weeks. 
- [ ] Links to role posting issues

#### Design
- [ ] No. of issues: 
   - [ ] [link to issues](https://github.com/hackforla/access-the-data/projects/1?card_filter_query=label%3A%22role%3A+design%22)
- [ ] Total No. of points ____ story points: 
- [ ] How many resources do we currently have?
- [ ] Do math on what you need
   - [ ] __  points / 2 resources =  ___ weeks. 
   - [ ] __ points / 3 resources = ___ weeks. 
- [ ] Links to role posting issues

### Research 
- [ ] No. of issues: __ (Ice Box)
   - [ ] [link to issues](https://github.com/hackforla/access-the-data/projects/1?card_filter_query=label%3A%22role%3A+research%22
)
- [ ] Total No. of points ____ story points: 
- [ ] How many resources do we currently have?
- [ ] Do math on what you need
   - [ ] __  points / 2 resources =  ___ weeks. 
   - [ ] __ points / 3 resources = ___ weeks. 
- [ ] Links to role posting issues
   - [ ] 

#### Engineering 
- [ ] No. of issues: 
  - [ ] [link to issues]
- [ ] Total No. of points ____ story points: 
- [ ] How many resources do we currently have?
- [ ] Do math on what you need
   - [ ] __  points / 2 resources =  ___ weeks. 
   - [ ] __ points / 3 resources = ___ weeks. 
- [ ] Links to role posting issues
   - [ ]

#### Data Analyst
- [ ] No. of issues:  
   - [ ] [link to issues](https://github.com/hackforla/access-the-data/projects/1?card_filter_query=label%3A%22role%3A+data+analyst%22)
- [ ] Total No. of points ____ story points: 
- [ ] How many resources do we currently have?
- [ ] Do math on what you need
   - [ ] __  points / 2 resources =  ___ weeks. 
   - [ ] __ points / 3 resources = ___ weeks. 
- [ ] Links to role posting issues
   - [ ]

**Comment by ExperimentsInHonesty** [comment]
### To do Items

- [ ] Product  
   - [ ] Recruit new resource
- [ ] Research
   - [ ]  Recruit new resource
   - [ ]  Make new issues for resource

**Comment by mxajPrice** [comment]
@lrchang2 can we close this?
