### ISSUE TITLE
High Fidelity Website Wireframes

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#41]
### Dependencies 
~#37~ 
~#102~
 

### Overview
We need to develop and test high fidelity wireframe prototypes of the website to help validate the design of the website and be able to pass on design to developers to use as their guideline for website development.

high fi = color, real content

### Action Items

- [ ] mobile version
   - [x] Develop low/mid-fi website wireframes #37 
   - [x] Build out high-fi wireframes 
   - [ ] Color correct high fidelity panels to correspond with changed header and footer
   - [ ] Do iterative user testing of high-fi wireframes to confirm usability and structure of website
- [ ] desktop version
   - [x] Develop low/mid-fi website wireframes #37 
   - [ ] Build out high-fi wireframes 
   - [ ] Color correct high fidelity panels to correspond with changed header and footer
   - [ ] Do iterative user testing of high-fi wireframes to confirm usability and structure of website
- [ ] define user flow and calls to action for all pages by section and components of wireframes 
- [ ] Perform a competitive audit of sites using CKAN to identify elements that will need to be incorporated into the new iteration of the high fidelity prototypes.  

### Resources/Instructions

- [Low-Fidelity vs. High-Fidelity Prototyping article from Adobe XD](https://xd.adobe.com/ideas/process/prototyping/low-fi-and-hi-fi-prototyping/)
- [figma with high fidelity mobile](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A14)

**Comment by lrchang2** [comment]
@miguel-hugo 
Please add update using this template 

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

**Comment by lrchang2** [comment]
@miguel-hugo Please add update using this template 

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by lrchang2** [comment]
add suggested edits to all versions 

- [Hack for LA logo](https://github.com/hackforla/access-the-data/issues/37#issuecomment-988313743)
- [update city of LA logo to colored one](https://github.com/hackforla/access-the-data/issues/37#issuecomment-988318057)

**Comment by miguel-hugo** [comment]
Progress: Finished applying current design and creating components to mobile wireframes. Need to finish carousel on landing page, update components, and build user flow documentation.
Blockers: Need finished copy to update text
Availability: Around 3-5 hours
ETA: Depends on the status of the copy, but most likely within 2 weeks

**Comment by lrchang2** [comment]
new website that needs to be applied to wireframes can be found [here](https://github.com/hackforla/access-the-data/issues/87#issuecomment-999108082).

**Comment by miguel-hugo** [comment]
Progress: Finished updating final copy of text, finished carousel for mobile hi-fi, and updating layout, interactions, and components. *Under "Updated Version: December 2021" in Hi-Fi Wireframes: Mobile"*
Blockers: Need feedback on look to determine if finished.
Availability: Around 3-5 hours
ETA: Depends on feedback provided, but should not be too much.

**Comment by lrchang2** [comment]
finished high fi wireframes

**Comment by lrchang2** [comment]
reopening to update wireframe colors

**Comment by deepamohan22** [comment]
@lrchang2 @KaylenaNguyen 
Progress : Fixed the spacing and alignment issues on Hi fi wireframes (Desktop ). 
Blockers : No
ETA        : 6 weeks.

**Comment by deepamohan22** [comment]
@lrchang2 

I have completed the tasks( fixed the spacing and alignment issues on Hi Fi Desktop) assigned to me by Keylena. I think Kevin  forgot to remove me from here. I got another issue to work on from Yesterday's meeting.

**Comment by lrchang2** [comment]
great, closing issue

**Comment by mxajPrice** [comment]
Copy of this version of the mobile site design:
![image](https://github.com/hackforla/access-the-data/assets/98370780/d00f52d0-cc95-4449-a05d-18ed195d10f6)
