### ISSUE TITLE
FAQs Sheet for Access the Data

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#42]
### Dependency
Living document that will have questions and answers added to them as they come.

### Overview
We need to create and document questions and answers about the Access the Data project so the team can be on the same page and common questions can be externally shared. This document would also aid in the onboarding of new volunteers for the project. 

### Action Items

- [x] Crowdsource questions from all current volunteers for Access the Data and write them down in a document 
- [x] PMs and Bonnie go through questions and write down answers for them 

### Resources/Instructions
Use this [FAQs document](https://docs.google.com/document/d/1eCXRhByy4qMJGd3PvWFbYFPJpEP1YcvR8rg7GRPzfCs/edit) to write down all your questions

**Comment by ElizabethWarninger** [comment]
I've added to the Questions/Review because I added [questions 12 & 13.](https://docs.google.com/document/d/1eCXRhByy4qMJGd3PvWFbYFPJpEP1YcvR8rg7GRPzfCs/edit?usp=sharing) Thanks!
