### ISSUE TITLE
User Stories for Website

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#45]
### Dependency
~#27~
~#58~

### Overview
We need to build out user stories for the website as an extension of the persona that was defined by the stakeholder to help guide the design of the brand and website. 

### Additional Details
Julien, the stakeholder for Access the Data, has defined the persona for the workshops and website as someone with low data literacy but an interest in learning how to work with data, an interest in public data sources, and wants to be part of the data driven decision making that local government uses. 

### Action Items

- [x] Define the user's potential goals and motivations 
- [x] Define actions users would take to achieve goals 
   - [ ] user + action + benefit  = "As a _____ user, I want to ______ so that I can _____."

### Resources/Instructions
- https://github.com/hackforla/access-the-data/issues/27
- [Copy of Introduction to Community Data - Pacoima, Satisfaction Survey (Responses)](https://docs.google.com/spreadsheets/d/163Zmmy7HxrpVbqOrj54L4yds5dWB5XiGXuPN7l__dTU/edit#gid=1717551687)
- [Copy of  Introduction to Community Data, Satisfaction Survey (Responses)](https://docs.google.com/spreadsheets/d/1w7M_KcPleFTwtAGFFRnfPz2l4MKS07vzgU8lABGiDcg/edit#gid=236422110)
- [Figma Jam file ](https://www.figma.com/file/nqls7mJsNB4w03wSfiVGLQ/Goals-and-Motivations-for-User-Map?node-id=0%3A1)that includes:
  - Motivations
  - Goals
  - User Stories

**Comment by ElizabethWarninger** [comment]
WIP - Starting to define/visualize the **Goals & Motivations**. These will be used to create the **actions** for the user stories. 
[Link to Figma Jam file](https://www.figma.com/file/nqls7mJsNB4w03wSfiVGLQ/Goals-and-Motivations-for-User-Map?node-id=0%3A1)

**Comment by lrchang2** [comment]
@ElizabethWarninger 
Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by ElizabethWarninger** [comment]
Hello!
Progress: Today I will be adding citations/back research to where I pulled the motivations & goals. I will also review the Interview with Julien about the audiences/user.
Blockers: Time until now. Also, I do not have access to the files from #27 - User Personas. Specifically, I would like access to 3 "Resources/Instructions" including the interview with Julien. 
ETA: By the EOD today
Picture: No pictures to show

**Comment by ExperimentsInHonesty** [comment]
@ElizabethWarninger Thank you for your work on this issue.  We are marking this complete.
