### ISSUE TITLE
Create 311 Data Manual / How-to Guide

### ISSUE THREAD

**Issue by snooravi** [hackforla/access-the-data#46]
### Dependencies 
 #47 #48 #49 #50 #51

### Overview
We want to build a how-to guide to help supplement the workshops that we are developing around 311. The how-to guide will be added to the website and be leveraged during the workshops as supporting content. 

### Action Items
The How-to guide should include:
- [x] #47
- [x] #48
- [x] #49
- [x] #50
- [x] #51

### Resources/Instructions
[311 Data Workshop Outline](https://docs.google.com/document/d/1W1WLLVAN8izVGgm5CsUwEZ43xc_2upMeXR3Q8l9GNd4/edit)

**Comment by MalakH21** [comment]
completed how to use: feature 1 (map) - please provide feedback w/ comments

**Comment by MalakH21** [comment]
updated : how to use: feature 1 (map) #48   +  use case 3 #50 [here](https://docs.google.com/document/d/1c4HsQkk24zRFg_lrca5BCI88o8gNYbCiyD_mkjZE5Tg/edit?usp=sharing)

note: overall doc formatting still wip

**Comment by MalakH21** [comment]
updated #51 [here](https://docs.google.com/document/d/1c4HsQkk24zRFg_lrca5BCI88o8gNYbCiyD_mkjZE5Tg/edit#)

**Comment by MalakH21** [comment]
10/18
- content done see [here](https://docs.google.com/document/d/1c4HsQkk24zRFg_lrca5BCI88o8gNYbCiyD_mkjZE5Tg/edit#), still, need to (1) format w/ arrows + (2) format appendix with reference definition of NC vs CC
- completion eta: 10/19

**Comment by snooravi** [comment]
This issue is complete and we will move into phase 2: minor tweaks, formatting, etc
