### ISSUE TITLE
Background on how to use (Overview & Motivation)

### ISSUE THREAD

**Issue by snooravi** [hackforla/access-the-data#47]
### Overview

In order to communicate effectively about the project we need to build an understanding of the context of 311 data especially in the context of the city of LA

### Action Items

- [x]  Summarize 311 data articles and research papers
- [x]  Compile a list of main points from the articles as well as other points that may not have been covered by the articles
- [x] Collaborate with workshops team (and others if they are interested) to refine the list of main points that makes a compelling story for new comers to the 311 workshop 
- [x]  Turn that list of main points into a set of slides and/or a write up 

### Resources/Instructions
[Research/Articles](https://docs.google.com/document/d/1ETtQ45YuzQIlAsIX3A69KaLx9awsqucBRfqkgzn4hJI/edit)
A version of the 311 data overview will be moved to the [Workshop Outline](https://docs.google.com/document/d/1ETtQ45YuzQIlAsIX3A69KaLx9awsqucBRfqkgzn4hJI/edit)

**Comment by snooravi** [comment]
Resources page [here](https://docs.google.com/document/d/1ETtQ45YuzQIlAsIX3A69KaLx9awsqucBRfqkgzn4hJI/edit)
Completed overview/motivation for 311 lives [here](https://docs.google.com/document/d/1W1WLLVAN8izVGgm5CsUwEZ43xc_2upMeXR3Q8l9GNd4/edit#)

**Comment by abryant35** [comment]
I moved this issue into the questions and review for the following reasons
1. Because it does not have any details in it and the title is not clear
2. IT has two links (resources for 311 workshop and details about 311-data.org)

**Comment by snooravi** [comment]
Final version found [here](https://docs.google.com/document/d/1W1WLLVAN8izVGgm5CsUwEZ43xc_2upMeXR3Q8l9GNd4/edit#)
