### ISSUE TITLE
How to Use: Feature 1 (Map)

### ISSUE THREAD

**Issue by snooravi** [hackforla/access-the-data#48]
### Overview
Participants in the 311 workshop(s) should be able to navigate the Maps feature of 311 to utilize its visualization and information to take action(s) or influence change in their communities
### Action Items

Create a detailed guide with description steps and accompanying screenshots explaining how to use the Map feature on [311](https://www.311-data.org/data )

### Resources/Instructions

[311 Data How-to Guide](https://docs.google.com/document/d/1c4HsQkk24zRFg_lrca5BCI88o8gNYbCiyD_mkjZE5Tg/edit?usp=sharing)

**Comment by abryant35** [comment]
Please describe in a user story what this issue is about 
As an ____ I need to do ____ for _____ reason

**Comment by MalakH21** [comment]
updated the comment, added requested information describing the issue

**Comment by snooravi** [comment]
Just needs reformatting, otherwise looks good! [here](https://docs.google.com/document/d/1c4HsQkk24zRFg_lrca5BCI88o8gNYbCiyD_mkjZE5Tg/edit#heading=h.ojyvhfpt0k21)
