### ISSUE TITLE
Notify VRMS of DLP Team Meeting Times

### ISSUE THREAD

**Issue by snooravi** [hackforla/access-the-data#5]
### Dependency
Project card to be added to website

### Overview
Need to decide on meeting times and VRMS needs to know details of DLP weekly team meetings

### Action Items
Notify VRMS of weekly team meetings once project card issue completed 

### Resources/Instructions

[Project Card Issue](#2 )

**Comment by ExperimentsInHonesty** [comment]
Tuesdays at 2pm PST, duration 1 hour

**Comment by snooravi** [comment]
Meeting time for Access the Data: Tuesday at 7pm
