### ISSUE TITLE
Design System - Style Guide: Color Palette 

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#53]
### Overview
As part of the Branding Guide, we need to choose a color palette for Access the Data to reflect our brand's personality in all products/resources created. 

### Additional Information 
Brand Personality: Simple, Trustworthy, Empowering, and Friendly

### Action Items
Color palette is required to have a certain level of color contrast to be ADA compliant #26. Use [color contrast checker](https://webaim.org/resources/contrastchecker/) to ensure that. 

- [x] Industry research from #8 and evaluate competitor colors 
   - [x] Consider how to differentiate Access the Data from its "competitors"
- [x] Identify target market and message to target market found in #27 and #45 and how color can convey it
- [x] Determine use cases for colors 
   - [x] #52 
   - [x] Templates 
      - [x] #56 
- [x] Draft up color schemes 
- [x] Check if contrast levels are high enough to be ADA compliant with [color contrast checker](https://webaim.org/resources/contrastchecker/)
- [x] Get feedback from team and refine color schemes with feedback 
- [x] Finalize color scheme 

### Color System
- [ ] do any audit for colors used on the mobile and desktop high-fi wireframes 
- [ ] collect all colors and HEX codes and compare it to current color system and determine if there are any colors used missing in the color system
- [ ] Color System includes 
   - [ ] Primary Colors that represent the brand identity 
   - [ ] Secondary Colors that highlight, compliment and/or contrast the primary colors 
   - [ ] Extended Colors are lighter and darker shades of the main primary and secondary colors
   - [ ] Neutral Colors that are used for background and borders 
   - [ ] Semantic/Functional Colors that communicate purpose (i.e. state; red=error, green=success or usage; background color, text color, label color etc) 
- [ ] check contrast and accessibility of color pairings in wireframes (use able plugin in Figma) 
- [ ] makes sure all design system colors are in the Figma Styles 

### Resources/Instructions
[Web Content Accessibility Guidelines](https://www.w3.org/TR/WCAG20/)
[color contrast checker](https://webaim.org/resources/contrastchecker/)

All work for branding guide is condensed in the [current draft of guide](https://docs.google.com/presentation/d/1Fuc_OrS5Jb2ocpDkJJ3bFwdLfYjkUBpwiVKQ1tpePok/edit#slide=id.p). Guide also contains Content Template Guide #22 and Front-End Style Guide #40

[figma file with color palette](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A5)
[figma styles in design systems](https://docs.google.com/document/d/1sWJbnxOZ5Pu4_YyKQGjkk4Jjo0bWAZIxelZeoIDaVR8/edit#heading=h.rdwy37w2ghtx)

**Comment by lrchang2** [comment]
@henrywang7 Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by henrywang7** [comment]
Progress: Made 4 first drafts of possible color schemes
Blockers: Would like to look at any wireframes/layouts if any have been made so far so I can get an idea of how the UI looks, and so I can better show how colors will be used
Availability: ~5 hours
ETA: Early next week
Pictures: ![Access the Data Color Schemes](https://user-images.githubusercontent.com/46332993/132600543-9d72e0f1-12eb-4c1d-9235-174c877964a9.png)

**Comment by PazauMoua** [comment]
Progress: Still working on it - Looking at Henry's colors
Blockers: None at the moment
Availability: Will have update with accessibility and color palette posted by Monday 10/04 9pm
ETA: Monday 10/04 9pm
Pictures:

**Comment by PazauMoua** [comment]
Progress: Need to vote at meeting on options
Blockers:  
Availability: 
ETA: 
Pictures
![COLOR PALETTE OPT 1 BOLD](https://user-images.githubusercontent.com/90879134/136127090-aa7a0821-9209-4663-946b-957c0e84c0d8.jpg)
![COLOR PALETTE OPT 2 BRIGHT](https://user-im
![NEUTRAL](https://user-images.githubusercontent.com/90879134/136127111-d39558a6-9053-467e-b440-2f141838dcb3.jpg)
ages.githubusercontent.com/90879134/136127098-dc126bb4-0216-487b-810f-1c87c2713210.jpg)

:

**Comment by melissamurphy** [comment]
@abryant35 Suggest having this issue follow Storyboarding in the meeting. Storyboards will be presented today and will serve to 'Identify target market and message to target market' [mentioned as a step in this issue] if discussed directly before the Color Palette review.

**Comment by lrchang2** [comment]
![Choices](https://user-images.githubusercontent.com/10827101/140435969-b135b388-1517-4818-8474-370ebb3cb712.jpg)

**Comment by ExperimentsInHonesty** [comment]
@PazauMoua Above is the pallet and the font selected for the project.  Please indicate this in figma by moving all the non selected to another page called Branding and Logo - Archived 2021-11-03, and move it to the Archived section at the bottom of the list of figma pages

**Comment by lrchang2** [comment]
closing issue, color palette confirmed and in design system figma

**Comment by lrchang2** [comment]
reopening to update design system
