### ISSUE TITLE
Design System - Style Guide: Typography

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#54]
### Overview
As part of the Branding Guide, we need to choose a font for Access the Data to reflect our brand's personality in all products/resources created. 

### Additional Information 
Brand Personality: Simple, Trustworthy, Empowering, and Friendly

### Action Items
Typography is required to be ADA compliant #26. 

- [x] text type
    - [x] headings: h1, h2, h3 
    - [x] paragraph text
    - [x] caption text

### Type Scale
- [x] do any audit for fonts used used on the mobile and desktop high-fi wireframes 
- [x] check to see if typeface is a special font that requires download for developers to use 
- [x] collect all fonts and compare it to current fonts in the design system and determine if there are any fonts used missing in the color system
- [x] Typography includes 
   - [x] Typeface(s)
   - [x] Font size (base font size = 16px, font sizes should be multiples of 2/4/8/16)
   - [x] Line height
   - [x] Styling (bold, italicized, etc)
   - [x] Hierarchy level/category (Heading 1, 2, 3.., Body 1, 2, 3.. etc.) (6 heading sizes max) 
   - [x] Sometimes typescales also include where the font sizes will be used, sizes at different responsive breakpoints, etc
- [x] check contrast and accessibility of color pairings in wireframes (use able plugin in Figma) 
- [x] makes sure all design system colors are in the Figma Styles 
- [ ] Update Call to action button colors to adhere to color contrast standards

### Resources/Instructions
[Web Content Accessibility Guidelines](https://www.w3.org/TR/WCAG20/)
All work for branding guide is condensed in the [current draft of guide](https://docs.google.com/presentation/d/1Fuc_OrS5Jb2ocpDkJJ3bFwdLfYjkUBpwiVKQ1tpePok/edit#slide=id.p). Guide also contains Content Template Guide #22 and Front-End Style Guide #40

[typography with design system in figma file](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A5)

**Comment by PazauMoua** [comment]
Progress: Typography selected - Group approval?
Pictures: See [Google Doc ](https://docs.google.com/document/d/1N1Eo3nCERoPhMnKvKCkRFVXHBg2xt_AorQO1GZ6JWJ0/edit?usp=sharing)for Typography choices

**Comment by abryant35** [comment]
@PazauMoua The team will vote on their favorite option at the next team meeting on Wednesday

**Comment by PazauMoua** [comment]
Progress: working on type combos/pairings
Blockers: NA
Availability: Working on this today through weekend
ETA: Tuesday 10/19 9pm
Pictures:

**Comment by ExperimentsInHonesty** [comment]
@PazauMoua please update your issue with the following info  if you have not already
- Progress: "What is the current status of your project? What have you completed and what is left to do?"
- Blockers: "Difficulties or errors encountered."
- Availability: "How much time will you have this week to work on this issue?"
- ETA: "When do you expect this issue to be completed?"

If you need help:
1. Be sure to  annotate your issue with details on what you need and move it to the Questions/Review column so we can add it to the meeting agenda.  
2. Additionally feel free to reach out in the #access-the-data slack channel asking for help.

**Comment by lrchang2** [comment]
sora was the final font chosen

**Comment by lrchang2** [comment]
reopening to update design system

**Comment by tsiedesign** [comment]
- Progress: Possibly completed, needs to be reviewed
- Blockers: N/A
- Availability: Available to work as needed
- ETA: 6/11/22
- Comments: Noted 2 different typefaces for footer (mobile vs web), contrast for white and terracotta do not pass accessibility checks.

**Comment by lrchang2** [comment]
@tsiedesign 
Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by KC243** [comment]
I will take over this issue and work on changing the button colors going forward.

**Comment by mxajPrice** [comment]
please update your issue with the following info  if you have not already
- Progress: "What is the current status of your project? What have you completed and what is left to do?"
- Blockers: "Difficulties or errors encountered."
- Availability: "How much time will you have this week to work on this issue?"
- ETA: "When do you expect this issue to be completed?"

**Comment by KC243** [comment]
Progress: Buttons have been changed to adhere to accessibility standards
Blockers: none
Availability:  issue done
ETA: completed. 

New Button/Accent Color Hex Code : EF6E6C
