### ISSUE TITLE
User Interview Script

### ISSUE THREAD

**Issue by joanna-pham** [hackforla/access-the-data#58]
### Overview
Creating a list of questions that will be asked during interviews. 

### Action Items
Ask open ended questions to keep conversation going and create opportunities for the person to tell their stories to give critical insights and ideas.
A few tips to keep in mind:
• Don’t try to ask all of these, prioritize based on your research goals.
• For each answer, be sure to ask “why” or “why not” to dig deeper. 

### Resources/Instructions
[Google Docs: Interview Questions](https://docs.google.com/document/d/1n4r-ZAOp9KqpePSeH0CR2Vfck6ulXqEFwSVnwMRXiKE/edit?usp=sharing)

**Comment by abryant35** [comment]
@joanna-pham Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #access-the-data channel.

Thank you! :)

**Comment by abryant35** [comment]
@joanna-pham Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #access-the-data channel.

Thank you! :)

**Comment by ExperimentsInHonesty** [comment]
@joanna-pham Please provide update or let us know if you cannot work on this issue so we can reassign it
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by abryant35** [comment]
Interview Script is complete. Closing issue
