### ISSUE TITLE
Create and send out Survey

### ISSUE THREAD

**Issue by jenny-gih** [hackforla/access-the-data#68]
### Overview
Create and send out survey to 1) find more information about potential users for access to data and 2) find potential users to interview

~#76~ 

### Action Items
- [x] Create survey - Complete
- [x] Have survey reviewed by team 9/20 week - Complete
- [x] Finalize survey - Complete
- [x] Send out survey - Pending
- [x] Create Survey Banner - Complete
- [x] Create recruitment survey message/flyer - In Review
- [ ] Send survey out and recruit participants
   - [x] Send out to LinkedIn network (using sarah's LinkedIn to post) 
      - [x] develop LinkedIn post blurb with Sarah
      - [x] post blurb with link to survey
      - [x] share with network and have all team members reshare
   - [ ] send out to EmpowerLA Newsletter
      - [x] develop blurb and image to be put into newsletter 
      - [x] put "role: org" on issue and have organization review
      - [ ] hand off to org for blurb and image approval and next steps on sharing it with newsletter 
- [ ] Close survey 

### Resources/Instructions
Final draft: [Access the Data Survey](https://docs.google.com/forms/d/1zZ1Bb8f0adDLHLvM3BXUtIlTp9Ih6lIfCGiJWzulIsc/edit?usp=sharing)
3 variations: [recruitment message to take survey](https://docs.google.com/document/d/1y-kgtY_ghtAa0qLftEvDkmtO_URV3yyRENF-FLFUlIE/edit?usp=sharing)
[guide for Google Form Design](https://github.com/hackforla/product-management/issues/23)

EmpowerLA Newsletter
blurb
image

**Comment by melissamurphy** [comment]
Maybe we can create a "balanced" question (see example in #7 of the article below) to quantify 5 interest levels for our findings (e.g. "Would you be interested in getting more involved in community efforts? a. Very interested b. Interested c. Neither interested nor uninterested d. Uninterested e. Very uninterested"). "Please explain why" could be the following question for more depth.

*Article on survey answer choices: https://www.surveymonkey.com/mp/survey-guidelines/

**Comment by jenny-gih** [comment]
Progress: completed screener survey and added Hack for LA + Access the Data banner
Blockers: Need Bonnie to review survey questions and decision log
Availability: 5 hours
ETA: by next week if reviewed
Pictures: see link in issue description

**Comment by lrchang2** [comment]
@jenny-gih Bonnie will share survey with Julien. She suggests cover picture be customized to Access the Data (aka don't use the picture from Hack for LA)

**Comment by ExperimentsInHonesty** [comment]
@lrchang2 I spoke to Julien. they will put a link for us into the newsletter.  We need to write the text and they can't tell us when the deadline is because right now its very unpredictable.

**Comment by jenny-gih** [comment]
@lrchang2 I've updated the banner in the survey. Let me know if you want any changes.

**Comment by abryant35** [comment]
@jenny-gih The updated banner looks great! We are going to push it out as is.

**Comment by ExperimentsInHonesty** [comment]
@jenny-gih Please provide the message as a google document with text, so that we can review it.

**Comment by jenny-gih** [comment]
> @jenny-gih Please provide the message as a google document with text, so that we can review it.

Great idea, I've put the variations in a word doc and updated the link above for your review. Thanks!

**Comment by ExperimentsInHonesty** [comment]
@jenny-gih I added a comment to the document.  The graphics are awesome looking,!  We will need language that provides context about the project to go into the Empower.la newsletter.

**Comment by ExperimentsInHonesty** [comment]
@jenny-gih I made one final edit, please review.  Sorry for the delay

**Comment by ExperimentsInHonesty** [comment]
@jenny-gih I added a response to completed surveys on the form

> Thank you for taking the survey. Please visit https://www.hackforla.org/projects/access-the-data to learn more about this project. accessthedata@gmail.com

**Comment by ExperimentsInHonesty** [comment]
Julien recommends adding examples of open data to the top of section2

**Comment by lrchang2** [comment]
@melissamurphy Please add update using this template

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by lrchang2** [comment]
ice boxing this issue, potentially may reuse as we recruit for more participants

**Comment by lrchang2** [comment]
sending out survey in EmpowerLA newsletter 12/20. 

blurb for newsletter: 
"
Hack for LA's Access the Data team is working in partnership with EmpowerLA to create an accessible data resource website within the LA community. 

We are looking for participants to share their experiences interacting with open source data, regardless of level of expertise. We want to understand how people are currently navigating the system to make changes in their community. Please help us fill out this survey to help us serve you better. 

The survey takes only 2 minutes to complete and will solely be used for our research. 

https://forms.gle/Bq8HCT7VXxabdyY27"

**Comment by lrchang2** [comment]
made a copy of screener survey to add extra question for Lucky Parking's UXR team. 

> "Or you could also add this question as the second question in Community Involvement Questions section
> If you indicated involvement in any LA local communities such as non-profit, volunteering, council, school organization, please indicate organization and title (optional)"

added Kiki - Salmonciara@gmail.com to survey

**Comment by ExperimentsInHonesty** [comment]
Lucy will summarize issue and identify exact next steps, assign appropriate role
