### ISSUE TITLE
Create competitive interview questions 

### ISSUE THREAD

**Issue by henrywang7** [hackforla/access-the-data#69]
### Overview
Create interview questions about competitor websites for user research. 

### Action Items
Set of Interview questions about competitor websites
A set user flow/goal to ask the interviewee to do for the websites

**Comment by henrywang7** [comment]
Progress: Created first draft of research questions/user tasks, will ask for feedback next ui/ux meeting
Blockers: Need more details on all the competitive sites we are planning on testing with
Availability: ~4 hours this week

https://docs.google.com/document/d/1wWXpXx-c5z2f_krySVTivJUDeVIFUvLE3DGNqbpUTXI/edit

**Comment by abryant35** [comment]
@mathhomework Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #access-the-data channel.

Thank you! :)

**Comment by mathhomework** [comment]
Progress: None.
Blockers: Unsure about whether this should be a priority considering this leads to interviewing which will take a fair amount of time. Meanwhile, we have 10 user interviews for user research that I think should be higher priority. The results of that will inform for tickets dependent on this one, at least for the first MVP iteration.
ETA: None.

**Comment by lrchang2** [comment]
closing issue, unnecessary research for what we've determine for website MVP
