### ISSUE TITLE
Provisional Storyboard for Website User

### ISSUE THREAD

**Issue by melissamurphy** [hackforla/access-the-data#74]
### Dependency 
Will be updated based on user research #62 

### Overview
A storyboard provides a visual of user experience and supplies a common reference for the entire team.

### Action Items

Define provisional User Persona types based on latest discussion across Access the Data site & workshop teams and stakeholders: 
- The person who knows nothing about data + has community causes they are passionate about (Persona 1)
- The person who has used data before, in their work with community activism (Persona 2)
- The prospective data user who is curious to know more about how data could apply to community causes (Persona 3)

All users share a minimum level of community involvement and interest in data, but we assume no minimum level of data literacy or even familiarity in our design. 

For each provisional User Persona type, cover these points in the storyboard:

- Set the user's environment
-  Note the user persona 
-  Identify the goal - what is the user looking to get done and how?
-  Depict the user's [pain points](https://docs.google.com/document/d/1eCXRhByy4qMJGd3PvWFbYFPJpEP1YcvR8rg7GRPzfCs/edit#) in the process
- Narrative - Follow their story through from beginning to middle to end

After storyboard authors have shared theirs amongst themselves,
- Have the team look at the storyboard together and discuss.

As new user needs come to light from research and the team iterates through new solutions, update the storyboard to keep the team vision aligned.
- [x] Define personas 
   - [x] The person who knows nothing about data + has community causes they are passionate about     
       - [x] Set the user's environment
       - [x] Note the user persona 
       - [x] Identify the goal - what is the user looking to get done and how?
       - [x] Depict the user's [pain points]
       - [x] Narrative - Follow their story through from beginning to middle to end
   - [x] The person who has used data before, in their work with community activism 
       - [x] Set the user's environment
       - [x] Note the user persona 
       - [x] Identify the goal - what is the user looking to get done and how?
       - [x] Depict the user's [pain points]
       - [x] Narrative - Follow their story through from beginning to middle to end
   - [x] The prospective data user who is curious to know more about how data could apply to community causes
       - [x] Set the user's environment
       - [x] Note the user persona 
       - [x] Identify the goal - what is the user looking to get done and how?
       - [x] Depict the user's [pain points]
       - [x] Narrative - Follow their story through from beginning to middle to end
- [x] Have the team look at the storyboard together and discuss.
- [ ] user research #62 
- [ ] update based on user research 

### Resources/Instructions
For more definition of a person's tendency towards activism, see the [Activism Orientation Scale](https://www.midss.org/sites/default/files/aosformattedforuse.pdf) from Corning's Social Cognition Lab for examples of the kind of statements that tally an individual's [orientation towards social action](https://www.midss.org/activism-orientation-scale-aos/).

**Storyboarding process and purposes served by storyboarding:**
Adobe's ["The What, Why, & When of Storyboarding in UX Design"](https://xd.adobe.com/ideas/process/user-research/storyboard-ux-design/) 
Smashing Magazine's ["The Role of Storyboarding in UX Design"](https://www.smashingmagazine.com/2017/10/storyboarding-ux-design/) 
 
**Workshop Survey Feedback**
[311 data notes](https://docs.google.com/document/d/12_RK820ygXpz_yR5ThmW1vbd6GMlopUsk0aIWdV4888/edit)
[User Personas issue with links to EmpowerLA workshop survey results](https://github.com/hackforla/access-the-data/issues/27)
[User Stories issue with links to workshop survey responses to Introduction to Community Data ](https://github.com/hackforla/access-the-data/issues/45)

**FigJam of User Stories based on above survey feedback:**
https://www.figma.com/file/nqls7mJsNB4w03wSfiVGLQ/Goals-and-Motivations-for-User-Map?node-id=0%3A1

**Data Literacy Persona Theory**
[Who Needs Literacy? Three Key Personas](https://www.ibbaka.com/ibbaka-talent-blog/who-needs-data-literacy)
[Data Literacy Personas in an Organization](https://aryng.com/blog/data-literacy-personas/)

**Comment by ElizabethWarninger** [comment]
WIP - [Figma Jam file of the start of the Storyboard for the second persona listed.](https://www.figma.com/file/dF0R94T9OHvqLjBQcVnzoU/Persona-Storyboarding?node-id=0%3A1)

**Comment by ElizabethWarninger** [comment]
@lrchang2 & @abryant35, what do you think about adding both the **Stakeholder** and **Potential Funders** as new personas? [Per the updated MVP V1 & V2. ](https://github.com/hackforla/access-the-data/wiki/Progress-of-Project). We can discuss if they should be added to our personas to understand their motivations/needs/goals/pain points and if a storyboard would be helpful as well. @melissamurphy & @miguel-hugo!

**Comment by lrchang2** [comment]
@ElizabethWarninger the needs for the stakeholder is to show "tangible progress on our project" and for potential funders, we can replace that with Bonnie, cause she may potentially use the website to present to funders. But the needs for the funders are the same as users who would want to know the purpose and potential of the project. 

since there is overlap, i don't think their needs warrant a persona for themselves.

**Comment by ElizabethWarninger** [comment]
@lrchang2, thanks for your response and clarifying and stating the needs of the stakeholder.

**Comment by melissamurphy** [comment]
Background research updated with outside theories of data literacy personas.

**Comment by melissamurphy** [comment]
@ExperimentsInHonesty There is no one checklist for this issue as we produced 3 distinct storyboards--each of which had to run through the steps (which was originally bulleted for this reason) by a distinct person. 
How might we note a set of requirements/steps that apply to 3 different team members and results?

**Comment by melissamurphy** [comment]
@kimberly-tellez @hannahsgr @ashleyxz  The Activism Orientation scale (from the Social Cognition lab at Cornell) I mentioned as a validated measure of activism is here https://www.midss.org/activism-orientation-scale-aos/ May provide some inspiration in defining our potential community activist users or some segment thereof.
