### ISSUE TITLE
UX Participant Recruitment

### ISSUE THREAD

**Issue by melissamurphy** [hackforla/access-the-data#78]
### Dependency
#99 

### Overview
Outline channels of recruitment for user research (user interviews, card sort, survey) and evaluate their feasibility and relevance to our project. Write a recruitment message and create a template to track and schedule respondents.

### Action Items
- [x] Confirm participant criteria 
- [x] Background reading on UX recruitment practices
- [x] Brainstorm (on figjam) possible avenues for recruitment
- [x] Test feasibility of avenues (cost, other restrictions)
- [ ] Address potential bias in recruitment 
- [x] Write recruitment message
- [x] Confirm a team email to send/receive responses 

### Resources/Instructions
Files
[FigJam for this issue - recruitment brainstorm](https://www.figma.com/file/pxuQI9pDi8Is8dv6e9t9rU/UX-Participant-Recruitment?node-id=0%3A1)
[Our Recruitment blurb (full)](https://docs.google.com/document/d/1U4mTdU5BqrQ74j6ThHDUPcNF29cA0NGNopIdSn3eLsY/edit)
[Spreadsheet-tracking recruitment](https://docs.google.com/spreadsheets/d/1ptRPv2bf1Y0VArY4UWrCjLkdux7NTvMtj6IZjNpXZbU/edit#gid=0)
#68 Recruitment Banner 

Hack for LA Examples
[Interview Recruitment email from GreenEarthOS](https://docs.google.com/document/d/1ExmPZdzTAvKPqcTMGlDvLS4k5IA3rmdESdX-AEDK3nc/edit#heading=h.ulehw08v81a7)

Best Practices
[How to Find Quality Participants for UX Research](https://blog.optimalworkshop.com/how-to-find-quality-participants-for-ux-research/)
[Basics of Recruiting Users](https://www.interaction-design.org/literature/article/the-basics-of-recruiting-users-for-usability-testing)

**Comment by mathhomework** [comment]
@lrchang2 @abryant35 Do we have a team email from which we could send/receive responses?

**Comment by lrchang2** [comment]
@mathhomework the email is: accessthedata@hackforla.org and the budget is $0.00 for recruitment

**Comment by melissamurphy** [comment]
Progress: Message was flagged as spam. Took link out of message and a number of rewrites, but no success yet.
Blockers: Unknown why our message is automatically flagged as spam. Will need to look into this further (and possibly find alternatives)
Availability: 3 more hours this week (outside of meeting times).
ETA: This week.

**Comment by ExperimentsInHonesty** [comment]
@melissamurphy who do you need to be involved to confirm email template?  If you are referring to another issue, please indicate the issue.

**Comment by melissamurphy** [comment]
**Progress**: 1 interviewee scheduled for this Thurs 11/18. Interviewee recruited from social media sharing from our team. I will conduct and second researcher @ashleyxz will be present for note-taking.
**Blockers**: Blocker 1 continues to be spam filtering. Meetup, Facebook, etc. have excluded our message from being sent due to spam filtering. Blocker 2 - Unavailable newsletter - Stakeholder had informed us we will not be able to use neighborhood newsletter for recruitment for several months. Blocker 3 is new target audience channels. We would like to reach the same target audience that the product will be marketed to upon launch, and through the same channels. What are some of these channels? Will NC's be targeted? @ExperimentsInHonesty @snooravi 
**Availability**: 1 hour for interview tomorrow and 1 interview to go over findings with @ashleyxz (who also is working with me on Content issue and content inventory)

**Comment by ExperimentsInHonesty** [comment]
@melissamurphy lets talk during meeting about how we can get around the spam filtering, but also how we think we got caught in it.

**Comment by lrchang2** [comment]
@melissamurphy Please add update using this template 

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by ExperimentsInHonesty** [comment]
Created a new issue #99 which will help in the activities.  Still need an update from assignee.

**Comment by ExperimentsInHonesty** [comment]
Who is the author of this file .  Its not in our current drive
https://docs.google.com/document/d/1U4mTdU5BqrQ74j6ThHDUPcNF29cA0NGNopIdSn3eLsY/edit
