### ISSUE TITLE
Create More Activities for the First Workshop

### ISSUE THREAD

**Issue by Jeremy-D** [hackforla/access-the-data#79]
### Overview
In order to engage participants in learning about 311 data, the workshops team has decided to create the first 311 data workshop with a focus around homelessness in Venice, CA. 

### Action Items
- [x]  Look up media articles about homelessness in Venice
- [x] Create data story about homelessness in Venice with 311 data and media resources
- [ ] Create activities that create an opportunity for participants to engage in data story telling about homelessness using 311 data site

### Resources/Instructions
[Document for activities](https://docs.google.com/document/d/1qj00bXGhrT90rTBkEQBgoRMSiKsf_XD9gIZsHrc41IA/edit)
[How to guide](https://docs.google.com/document/d/1c4HsQkk24zRFg_lrca5BCI88o8gNYbCiyD_mkjZE5Tg/edit#heading=h.cg24v97mvrx8)
[Workshop Outline](https://docs.google.com/document/d/1W1WLLVAN8izVGgm5CsUwEZ43xc_2upMeXR3Q8l9GNd4/edit)
[Q&A with 311 data team](https://docs.google.com/document/d/12_RK820ygXpz_yR5ThmW1vbd6GMlopUsk0aIWdV4888/edit#heading=h.w0wacw3hwl0k)

**Comment by ExperimentsInHonesty** [comment]
On Advice from two stakeholders (Bonnie and Julien) we will not be using homelessness data as our first workshop
