### ISSUE TITLE
Comparative Analysis of Websites (different from data sources) and MVP Feature Prioritization 

### ISSUE THREAD

**Issue by snooravi** [hackforla/access-the-data#8]
### Dependency 
Will update after each version of MVP 

### Overview
We need to have a comparative analysis for data literacy websites so that we can evaluate possible features to include in our website and decide on the MVP features for the website.

### Additional Details
Websites can be commercial or government.

In the comparative analysis, cells are color coded based on keyword: 
- "yes" = green
- "?" = yellow
- "no" = red

### Action Items
- [x] Collect resources
- [x] Add resources to copy of  Comparative Analysis (adding features as you find them)
    - [x] Add column for (MoSCoW) Prioritization
    - [x] Add "type of resource"
    - [x] Add column for "Where it would be located on website?"
- [x] MVP prioritization 
   - [ ] gather feedback from all stakeholders (website and workshops) and iterate on

### Resources/Instructions
Current draft: [Feature prioritization for MVP in Miro + gap analysis](https://miro.com/welcomeonboard/ODZxYW5jTFBIM2tyUTdHZzZsdFBnR3pqOXNiRzBwZXpsRkFkWlVxZUV1R3hrVWZGaXNZdnVpUk9FSnprTFBKYnwzMDc0NDU3MzYzMjcxODQzNDEy)
Current draft:  [comparative analysis for websites draft](https://docs.google.com/spreadsheets/d/1_cx15yObwAl3KZYJjDgqjXd7Njw2D05BfcSc1eGZDtU/edit?usp=sharing)
Find other inspiration from resource ecosystem comparative analysis [LA Data Resources](https://docs.google.com/spreadsheets/d/1JKMw4BT-i4gUC73lRXxI5g4yWOxhQ5OOAhG58Ch1LqY/edit#gid=0)

[Comparative and Competitive Analysis template](https://docs.google.com/spreadsheets/d/1_cx15yObwAl3KZYJjDgqjXd7Njw2D05BfcSc1eGZDtU/edit#gid=0)

[311 data workshop template](https://docs.google.com/document/d/1W1WLLVAN8izVGgm5CsUwEZ43xc_2upMeXR3Q8l9GNd4/edit)
[Open Community Survey Figma](https://www.figma.com/file/04T31AqsprIIkuBN4OfwOo/Open-Community-Survey-Designs?node-id=115%3A84)

**Comment by snooravi** [comment]
Template here: https://docs.google.com/spreadsheets/d/1ePxxsLpdC4MMvJICyMYljHawhs1j-hpFHZFOtB0fdDc/edit#gid=1259306930

**Comment by snooravi** [comment]
Progress can be found [here](https://docs.google.com/spreadsheets/d/1JKMw4BT-i4gUC73lRXxI5g4yWOxhQ5OOAhG58Ch1LqY/edit#gid=0)

**Comment by ExperimentsInHonesty** [comment]
The work on this so far will definitely be helpful: https://github.com/hackforla/access-the-data/issues/8#issuecomment-812903495
And it needs to be in the traditional format of our Comparative and Competitive analysis so that we can add more detail and prioritization.

**Comment by asselabilova** [comment]
comparative analysis for websites draft 

https://docs.google.com/spreadsheets/d/18ckXu8YsMP4HAsxbxW9Xdc99Bvnb7t2wEJD8yeJnPLk/edit?usp=sharing

**Comment by asselabilova** [comment]
https://www.figma.com/file/6xUSdpvbOMeAuZKRDMSJpy/Access-the-Data-Comp.-analysis?node-id=0%3A1

comparative analysis UI for websites draft

**Comment by asselabilova** [comment]
https://docs.google.com/spreadsheets/d/18ckXu8YsMP4HAsxbxW9Xdc99Bvnb7t2wEJD8yeJnPLk/edit?usp=sharing

Progress on comp. analysis for Website. 

I'm not sure if we started the comp. analysis for Workshop? Will we need a separate file for workshop analysis? Should we assign someone to work on workshop comp. analysis @snooravi? Since I will be focusing only on UX/UI for website. Thanks!

**Comment by ExperimentsInHonesty** [comment]
@asselabilova Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by asselabilova** [comment]
https://www.figma.com/file/UI9sFlZiFx6WFhqghf0xRh/Access-The-Data?node-id=1%3A2 - progress, started Information architecture 

https://docs.google.com/spreadsheets/d/18ckXu8YsMP4HAsxbxW9Xdc99Bvnb7t2wEJD8yeJnPLk/edit#gid=0 - progress, looking at features.

**Comment by snooravi** [comment]
@asselabilova to Offload this work to someone else during tomorrow's team meeting

**Comment by abryant35** [comment]
@jenny-gih Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #access-the-data channel.

**Comment by jenny-gih** [comment]
> @jenny-gih Please add update using this template (even if you have a pull request)
> 
> Progress: "What is the current status of your project? What have you completed and what is left to do?"
> Blockers: "Difficulties or errors encountered."
> Availability: "How much time will you have this week to work on this issue?"
> ETA: "When do you expect this issue to be completed?"
> Pictures: "Add any pictures of the visual changes made to the site so far."
> 
> If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #access-the-data channel.

Progress: completed comparative analysis and synthesized it into miro to prioritize features to consider for MVP
Blockers: Need the feature prioritization reviewed. Who can confirm this task is good to go?
Availability: 5-10 hours a week
ETA: by next week if reviewed
Pictures: see "Feature prioritization for MVP in Miro + gap analysis" link in resources in original post

**Comment by lrchang2** [comment]
@jenny-gih Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by jenny-gih** [comment]
> @jenny-gih Please add update using this template (even if you have a pull request)
> 
> Progress: "What is the current status of your project? What have you completed and what is left to do?"
> Blockers: "Difficulties or errors encountered."
> Availability: "How much time will you have this week to work on this issue?"
> ETA: "When do you expect this issue to be completed?"
> Pictures: "Add any pictures of the visual changes made to the site so far."
> 
> If you need help, be sure to either:
> 
> 1. ask for help at your next meeting
> 2. put a "Status: Help Wanted" label on your issue and pull request
> 3. put up a request for assistance on the #access-the-data channel.

Progress: reconciled and updated the comparative analysis sheet and prioritized features for MVP in Miro
Blockers: 1) need a catch up meeting with Lucy and Alyssa 2) Pending meeting with Jeremy D from Workshop team to get workshop features from them
Availability: 5-10 hours a week
ETA: by next week if reviewed
Pictures: see "comparative analysis for websites draft" and "Feature prioritization for MVP in Miro + gap analysis" links in resources in original post

**Comment by jenny-gih** [comment]
Progress: consolidated and/or removed duplicates in comparative analysis
Blockers: none, this is iterative
Availability: 5 hours a week
ETA: Next week
Pictures: see "comparative analysis for websites draft" and "Feature prioritization for MVP in Miro + gap analysis" links in resources in original post

**Comment by abryant35** [comment]
MVP version 1 has been completed. This issue will be moved to the ice box until it's time to work on version 2.

**Comment by melissamurphy** [comment]
Added LACounts to [spreadsheet](https://docs.google.com/spreadsheets/d/1_cx15yObwAl3KZYJjDgqjXd7Njw2D05BfcSc1eGZDtU/edit#gid=1259306930).  An example raised in today's PM + Leads meeting by @lrchang2 , LACounts Beta (no longer maintained) showed storytelling with data and specifically LA-area datasets.
