### ISSUE TITLE
UX Field Study

### ISSUE THREAD

**Issue by melissamurphy** [hackforla/access-the-data#80]
### Overview
We need to review the sites gathered during the [comparative analysis ](https://docs.google.com/spreadsheets/d/1_cx15yObwAl3KZYJjDgqjXd7Njw2D05BfcSc1eGZDtU/edit#gid=1172277014) to find opportunities to improve user experience of data literacy programs.

#### What is a field study
Especially suitable for big-picture insights at the start of the design process, a field study tracks a user's natural course of interaction with existing data sites.  Observations based on a user's spontaneous experience help define what users holistically notice, need, and want; the results will inform branding, personas, and early designs.

### Action Items

Pre-study
- [ ] List sites (see  [comparative analysis ](https://docs.google.com/spreadsheets/d/1_cx15yObwAl3KZYJjDgqjXd7Njw2D05BfcSc1eGZDtU/edit#gid=1172277014) )
  - [x] BetaNYC
  - [x] NDSE
  - [x] BallotNav
  - [ ] LA Mayor's 
  - [x] Data Literacy Project
  - [ ] EmpowerLA.org
  - [ ] Data LA
  - [ ] Coursera
  - [ ] LinkedIn Learning
  - [ ] Skill Share
  - [ ] ArcGIS
- [ ] identify goals for your field study (after background reading in below Resources)
- [ ] choose an active or passive model of field study

Conducting the Study
- [ ] Note participant's context of use 
- [ ] Introduction: introduce yourself, the purpose, and the procedure
- [ ] Obtain participant's expressed consent for recorded interview
- [ ] After 30 seconds with website, conduct impression test of branding and purpose (look away + describe their impression of the site) 
- [ ] Take notes on key moments during their interaction--also note time stamps for later reference
- [ ] Observe user's interaction with site: highlights/lowlights may appear as user's comments ("say"), actions ("do"--may differ from what's said), reactions ("feel"), opinions ("think")
- [ ] Optional: contextual inquiry to actively interview user about their experience, impressions, choices during their interaction with the sites

Concluding the Study
- [ ] Summarize the experience with the user after the interaction experience has ended, allowing for last thoughts and clarifying questions
- [ ] Finish with subject's completion of our screener survey questions 
- [ ] Make an immediate write-up of notes upon field study's end in order to capture observations as close to event as possible 
- [ ] Present insights to team

### Resources/Instructions
**Recordings**
[NDSC and Data Literacy Project field study recordings](https://drive.google.com/drive/u/0/folders/131mTeuIHLxBAA7ugEkta1DMlka9bBEJL)

**Documents of Findings**
[NDSC Field Study Notes by Andrew](https://docs.google.com/document/d/1eEsQQief-yiKC7z-xsqPYzYo4Nmih-zzJByRO5mckZY/edit)
[BallotNav Field Study Notes by Elizabeth](https://docs.google.com/document/d/1x3htDmgqSGv8I5_nu0YR24leK5E4iYbC64jhJ_M1Qjo/edit)
[Data Field Study Notes by Joanna](https://docs.google.com/document/d/1KTEvxstg75Z_ETUZJGmDBsQM3EByXMYpH2goUJxlLtA/edit?usp=sharing)

**3 Steps to Contextual Inquiry and 4 Guiding Principles**
[Putting UX in Context with Contextual Inquiries](https://xd.adobe.com/ideas/process/user-research/contextual-inquiry-ux/)

**Reasons for Field Study**
[When to Leave the Lab for the Field](https://www.nngroup.com/articles/field-studies/)

**Relation to Design**
[Translating User Research into UX Design](https://xd.adobe.com/ideas/process/user-research/translating-user-research-into-ux-design/)
[A Comprehensive Guide to UX Research Methods](https://blog.adobe.com/en/publish/2017/10/27/a-comprehensive-guide-to-ux-research-methods.html#gs.d2v7gi)

**Comment by ExperimentsInHonesty** [comment]
@joanna-pham  Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #access-the-data channel.

**Comment by joanna-pham** [comment]
Materials for the field study were previously added under **Recordings** and **Documents of Findings**. Moving issue to prioritized backlog - need to split studies into separate issues.
