### ISSUE TITLE
User Research Feedback Presentation for Julien 

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#82]
### Overview
We (research/design leads) need to create a 5 minute presentation about the research questions and personas for the user research for the stakeholder, Julien, to get feedback and consensus on the direction of the user research. 

### Action Items

- [x] Look at example stakeholder presentations 
- [x] Develop powerpoint presentation
- [x] Get feedback from Bonnie and PMs about presentation
- [x] Present to Julien on 10/15

### Resources/Instructions
[examples of stakeholder presentations](https://drive.google.com/drive/u/1/folders/1BxkOKD95yZN03yiSthhcLPpiZi0KKodD)
[Presentation Slide For Julien](https://docs.google.com/presentation/d/1qL1MBNrRB3XBPbRmYI66-ekxZOAK-V4aiJLOv7ON2Hs/edit?usp=sharing)

**Comment by lrchang2** [comment]
@joanna-pham @melissamurphy please link powerpoint within this issue

**Comment by abryant35** [comment]
@melissamurphy @joanna-pham Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #access-the-data channel.

**Comment by mathhomework** [comment]
Notes from the meeting:
https://docs.google.com/document/d/1HlWS5TNYHgLNo57g05dQEvQ7pKju-WidlHMBMkCbmQI/edit
