### ISSUE TITLE
Website Copy 

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#87]
### Dependency 
~- #102~
- #106 - need for origin story copy

### Overview
Based on information architecture, we need develop usable website copy that can be applied to the wireframes.  

### Additional Information
Brand Personality: Simple, Trustworthy, Empowering, and Friendly

Goals for Copy: 
1. people who visit the website have a clear understanding of what Access the Data is as a project and who it is our target audience
2. users know what service is provided (educational workshops around data literacy)
3. people clearly understand the value add of the service provided
4. if interested, how to move forward/participate (i.e. signups)

### Action Items

- [x] Define audience and tone
- [x] Write draft of all sections defined from the information architecture #36 
- [x] Get feedback from team, stakeholders, and organization
- [x] Edit based on feedback 
- [x] Give to designers to apply to wireframes
- [ ] Edit copy based on usability testing on wireframes

### Resources/Instructions
[website copy draft](https://docs.google.com/document/d/1nj2B2hVU-y-LKsyvaBWdjy8a2iqSZ7zyR6y4K7PkOLY/edit#heading=h.12i5r6arxqz2)
[hemingway editor](https://hemingwayapp.com/)
[control your vocab](https://abbycovert.com/ia-tools/control-your-vocabulary/)
[content frames](https://www.youtube.com/watch?v=cHDJv6eR5j0&feature=youtu.be)
[content frame template](https://www.figma.com/file/Nvv43yz7YC4iUGAmKuJvMM/Content-Frame-template?node-id=0%3A1)

**Comment by melissamurphy** [comment]
@lrchang2 @ashleyxz Now that we have a good amount of content, it's time to make a content inventory -- I can make a separate issue for this, @ashleyxz would you be interested in getting that going with me?

**Comment by ashleyxz** [comment]
Yes, count me in! @melissamurphy

**Comment by melissamurphy** [comment]
Worked on this for 4 hours this week so far. I can work on copy/content frames/content inventory for another 2 hours in our meetings or later this week (after Thursday).
Miguel had input into the IA of the copy (see comments in Google doc and Figma).
We can use the Site Map & brainstorm a Content Frame for the Content Inventory:
Site Map for Content: https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A7 Content Frame Figjam: https://www.figma.com/file/KUeTu7xHEOH1euciVx9XuJ/Content-Frame-for-Website-V1?node-id=0%3A1

**Comment by melissamurphy** [comment]
Will be working with @ashleyxz on the above today or tomorrow

**Comment by lrchang2** [comment]
@ashleyxz @melissamurphy 
Please add update using this template

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

**Comment by ashleyxz** [comment]
Progress: 
1) 1st user interview session (note taking), notes: https://docs.google.com/spreadsheets/d/12vylnca020OKdUc0fJECGhHW5Jgn5bZcC96nsHCAl4w/edit#gid=705693488

2) 1st user interview session (analysis)
https://miro.com/app/board/o9J_lhs1V4g=/

2) content inventory 
https://docs.google.com/spreadsheets/d/1rapDKXRvHAerkgR0VIg-xl9W59uMcesm/edit?rtpof=true#gid=727218828

Blockers: may need some help on the content inventory, not sure what else to be included at this stage

Availability: 2 hours on the research and 2 hours on content inventory

**Comment by melissamurphy** [comment]
@ashleyxz Great work! Could you move your google docs into our shared Access the Data research drive? https://drive.google.com/drive/u/0/folders/1Wr3qoQ56T9WefQ5yTbbSPvHSZt9RMW0k

It looks like you need to also grant us permission to view the Miro

**Comment by ashleyxz** [comment]
@melissamurphy Hey Melissa, how about this? 
https://miro.com/welcomeonboard/alVEU1BuQXB1bE1LNk9CQzI2Zms0a2hFVEtGOVhaY0ZuWWxkckE2V1JZUUR0THJZbm1qeWM4SXkyWnNDWllydXwzMDc0NDU3MzYyMzc3MzIxNDI5?invite_link_id=613211402360

**Comment by lrchang2** [comment]
@ashleyxz @melissamurphy Please add update using this template

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by ashleyxz** [comment]
Progress: 

Website Copy: v3 of website copy sent to Melissa for review (not including the About Us Page) https://docs.google.com/document/d/1AITqJN5elR6q78RfYakUnACuO83z7ehWA9C6BN4WxuI/edit?usp=sharing

User Research: mental modal (analysis) 
https://miro.com/welcomeonboard/alVEU1BuQXB1bE1LNk9CQzI2Zms0a2hFVEtGOVhaY0ZuWWxkckE2V1JZUUR0THJZbm1qeWM4SXkyWnNDWllydXwzMDc0NDU3MzYyMzc3MzIxNDI5?invite_link_id=137396603266

Blockers: No

**Comment by lrchang2** [comment]
[most updated version of the copy](https://docs.google.com/document/d/1b92A3mBuK65hRkWF_ouXRFi31tiFwY7koerVtio84xs/edit)

this copy will be applied to the wireframes for usability testing
