### ISSUE TITLE
Usability Testing for Low/Mid Fidelity Prototypes

### ISSUE THREAD

**Issue by ElizabethWarninger** [hackforla/access-the-data#88]
### Overview
Create a plan and conduct usability tests for both the mobile and desktop versions of the low/mid fidelity prototypes. 

### Dependencies

- #37
- #87 

### Action Items

- [x] Research best practices for usability testing

**Create a usability research plan detailing:**
- [x] Usability task flows based on the goals of MVP 1 
- [x] Determine the method of the usability test (structured, moderated, guerrilla, etc.)
- [x] Determine test metrics (i.e. task completion, or qualitative data)
- [x] Create a plan for recruitment of participants (likely HFLA slack community)
- [x] Decide on the number of participants
- [x] Determine the method of analysis for the usability tests
- [x] Get feedback from the team on the usability test plan 

**Collaborative team feedback**
- [ ] Brainstorm ideas for effective team feedback sessions
- [x] Conduct a feedback session with the team for the prototype
- [ ] Make changes to the prototype based on team feedback

**Conduct usability tests**
- [x] Send out a recruitment message based on the prior recruitment plan
- [x] Conduct Usability Tests

**Analyze and report findings**
- [ ] Analyze [findings](https://docs.google.com/spreadsheets/u/0/) based on prior determined methods ([Affinity Map FigJam](https://www.figma.com/file/doYnKXIUX9PC0XF7UcyU4P/Mid-fi-Wireframes-Usability-test-debrief-and-synthesis?node-id=0%3A1))
- [ ] Create report of findings

### Resources/Instructions
[Usability Testing 101 - NNG](https://www.nngroup.com/articles/usability-testing-101/)
[From Research Goals to Usability-Testing Scenarios: A 7-Step Method](https://www.nngroup.com/articles/ux-research-goals-to-scenarios/)
[How to run a feedback session](https://uxdesign.cc/design-reviews-how-to-run-feedback-sessions-with-designers-99e67e397a69)
[Planning a Usability Test](https://www.usability.gov/how-to-and-tools/methods/planning-usability-testing.html)
[How we conduct design reviews](https://www.abstract.com/blog/conduct-design-reviews)

### Files
[Figma Design file to Wireframes + Usability Testing Protocols](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A10)
[Figma Jam file for Wireframe Team Review Party](https://www.figma.com/file/Nl67hybgBCKkpMcjcb13B9/Wireframe-Design-Review-Party?node-id=0%3A1)
[Google Sheets: Observation Notes](https://docs.google.com/spreadsheets/d/1LSn9gwVv1VDBNDIgepzHkhBxr-W57RyVXv-jb8u6vDQ/edit?usp=sharing)
[Debrief FigJam - Affinity Map](https://www.figma.com/file/doYnKXIUX9PC0XF7UcyU4P/Mid-fi-Wireframes-Usability-test-debrief-and-synthesis?node-id=0%3A1)
[Slide deck of Results](https://docs.google.com/presentation/d/19W-Nn2ZNsa6oh14ud38xAsPmEQlPad7p-CxTPAd-W2w/edit#slide=id.gfd97b42aa4_0_139)

**Comment by melissamurphy** [comment]
Added [Affinity Map from Monday 11/1 group debrief FigJam](https://www.figma.com/file/doYnKXIUX9PC0XF7UcyU4P/Mid-fi-Wireframes-Usability-test-debrief-and-synthesis?node-id=0%3A1) to the issue description

**Comment by ExperimentsInHonesty** [comment]
@mathhomework @joanna-pham  Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 1) ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #access-the-data channel.

**Comment by joanna-pham** [comment]
Closing issue. Usability testing for mobile mid-fi wireframes has been completed. Issue has been updated with links to materials and results of testing.
