### ISSUE TITLE
Refining the "Data Literacy" Journey Designs

### ISSUE THREAD

**Issue by snooravi** [hackforla/access-the-data#90]
### Overview
As a part of the website, we are attempting to help orient the user as to where they are in their journey and next possible steps they can take. 

### Action Items

- [x] Review current [diagram](https://drive.google.com/file/d/1lMCtxNrLIyb6PJZ2GrzASGlLWJxlM3Ii/view) and visualization + critique 
- [x] Modify the [copy](https://docs.google.com/document/d/1EM1u0aECTVjalYmnRys7ZNHdiZlm1jeItqwkxYvuGpw/edit) of the diagram to align with the personas of the project
- [ ] Handoff to the UX Team

### Resources/Instructions
Persona's: 

- Community Activist: The person who knows nothing about data and has community causes they are passionate about
- General User: The prospective data user who is curious to know more about how data and could apply to community causes
- Data Amateur: The person who has used data before, in their work with community activism
- Potential for Expansion: Somebody who is politically aware but is looking (??) for the right opportunity to get politically involved

**Comment by MalakH21** [comment]
workshop team met and agreed  on this diagram + these personas
![image](https://user-images.githubusercontent.com/40288906/140846900-9d4b284a-62c0-4e84-8808-8c865dd78e6b.png)

**Comment by ExperimentsInHonesty** [comment]
@snooravi do you have an updated version of the image?

**Comment by lrchang2** [comment]
need to discuss this with UX team during team meeting

**Comment by lrchang2** [comment]
![image (2)](https://user-images.githubusercontent.com/10827101/144139186-9e6c8dbc-9e40-4171-bab7-19c02c282b0e.png)

**Comment by lrchang2** [comment]
edits to make on the image
- [ ] make persona background block go all the way down (use one color)
- [ ] "raise your voice hand sign" covers the word "persona" - stack as persona and community activist 
- [ ] for "get involved & network" put the & on the next line
- [ ] use same alignment for right titles for each step of journey

**Comment by snooravi** [comment]
https://docs.google.com/presentation/d/1pvd1c_z1spS_8tARF1LpKonCfdUTiNk6teiri2EI7xA/edit#slide=id.g103c389c4c0_0_0
<img width="963" alt="Screen Shot 2021-11-30 at 2 49 54 PM" src="https://user-images.githubusercontent.com/22307660/144140771-e5cc7859-1e00-4ea4-81db-74012aae7a72.png">

**Comment by lrchang2** [comment]
Persona 2: "Data Amateur" is changed to "Data Hacker"

**Comment by melissamurphy** [comment]
For consistency, let's keep Persona 2 "Data Amateur" in mind as originally conceived (a community activist who does have that domain knowledge, but is newer to data) and add "Data Hacker" (someone more familiar with data) in as an additional persona.

**Comment by ExperimentsInHonesty** [comment]
Next step on this issue is that Lucy will finish adding the task items

**Comment by lrchang2** [comment]
closing issue. 

Defined journey is handed off to the UX team. Designers have determined to put journey into a carousel format on the website. Developing, testing and approving of carousel designs are in #96.
