### ISSUE TITLE
Adding Context to 311

### ISSUE THREAD

**Issue by snooravi** [hackforla/access-the-data#91]
### Overview

The presentation and notes from [empowerla.org](https://empowerla.org/data/) data literacy initiative identifies several other import data sets.  This issue will examine how we might incorporate this information with 311, both for querying and reporting.

### Action Items

- [x] Service organizations (mapping table to be added to drive)
- [x] Demographic information
- [x] Land Use
- [x] Service Areas from empowerla
- [x] Street Networks
- [x] Notebooks to explain results
- [x] Checking this off in this issue, moving to chart deck development

### Resources/Instructions
data.lacity.org
open source portal (OSM)
geohub.lacity.org

**Comment by ExperimentsInHonesty** [comment]
@snooravi 
- when you say service organizations, do you mean district types? https://github.com/hackforla/data-science/issues/124

**Comment by lrchang2** [comment]
@mcmorgan27 
Please add update using this template

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by mcmorgan27** [comment]
Progress: 
  - Identified/collected/processed all contextual data except road networks
  - Analyzing results for specific problems/NCs
  - I'm adding temporal analysis to the 311 data
  - I will publish my work on my github and figure out where it should go
  - Willing to review my work if there's interest
 
Blockers:
 - No technical/data blockers
 - Would be nice to develop better "stories" for the data

Availability: I will spend the hours needed to finish this week.

ETA: 03/12/2021 - End of the week.

**Comment by snooravi** [comment]
Next steps: Upload jupyter notebooks. ettc

**Comment by snooravi** [comment]
@mcmorgan27 Please add 2-3 questions that anchor around graffiti as a use-case for us to develop story for workshop

**Comment by lrchang2** [comment]
@mcmorgan27 Please add update using this template

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by mcmorgan27** [comment]
Progress:  Completed.  Moving the last task to slide deck issue

I will verify this at the meeting tonight.

**Comment by mcmorgan27** [comment]
So I think we determined this could be closed.
