### ISSUE TITLE
Research Findings Summary Presentation

### ISSUE THREAD

**Issue by melissamurphy** [hackforla/access-the-data#92]
Dependency
- ~#88~

### Overview
We (research/design leads) need to create a 5 minute presentation about the research findings from field studies and usability testing for the stakeholder, Julien, to get feedback and consensus on the direction of the site. 

### Action Items

- [x] Look at example stakeholder presentations 
- [ ] Develop powerpoint presentation
- [ ] Get feedback from Bonnie and PMs about presentation
- [ ] Present to Julien on ???

### Resources/Instructions
[examples of stakeholder presentations](https://drive.google.com/drive/u/1/folders/1BxkOKD95yZN03yiSthhcLPpiZi0KKodD)
[Presentation Slide For Julien](https://docs.google.com/presentation/d/1qL1MBNrRB3XBPbRmYI66-ekxZOAK-V4aiJLOv7ON2Hs/edit?usp=sharing)

[research presentation](https://docs.google.com/presentation/d/1Pc-JvlKlBNiIZ20t_2im08FCJBCsL4fpizWUU2kYh-g/edit)

**Comment by lrchang2** [comment]
@ashleyxz Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.
