### ISSUE TITLE
Data Preprocessing for 311 Data 

### ISSUE THREAD

**Issue by snooravi** [hackforla/access-the-data#93]
### Overview
We need to develop a preprocessing function or class that will identify and solve for issues we are finding within the 311 dataset

### Action Items

- [x] Identify pre-processing steps (removing erroneous data, cleaning up council names, etc)
- [x] Wrap in a class or function

### Resources/Instructions
[Google Colab link](https://drive.google.com/file/d/1LvuuPDWPGC6g3WOLHOk806ocQbYAJ5qj/view?usp=sharing)

**Comment by snooravi** [comment]
Add questions we need chelsey to help us answer

**Comment by ExperimentsInHonesty** [comment]
@snooravi @ShikaZzz The 311 data team has already written a ton of scripts to clean the 311 data.  They spent a year writing those.  Let's not reinvent the wheel.  Do we really need the raw data, if so, we can arrange to get the cleaned data from the hackforla 311-data team.

**Comment by snooravi** [comment]
@ExperimentsInHonesty We just got the scripts from @chelseybeck yesterday. https://drive.google.com/file/d/1LvuuPDWPGC6g3WOLHOk806ocQbYAJ5qj/view?usp=sharing

**Comment by ExperimentsInHonesty** [comment]
@ShikaZzz once you identify what is in the Google Colab, please write a better description for it in the top section of this issue.

**Comment by snooravi** [comment]
@ShikaZzz can you add an update for this issue. and tag Chelsey if we need her help

**Comment by snooravi** [comment]
@mcmorgan27 to upload his file to the github and share with @ShikaZzz

**Comment by mcmorgan27** [comment]
I think I have stuff working in my repos https://github.com/researchsherpa/data-literacy.

@ShikaZzz - If your just looking for data there are multiple zip files in data/311.  Lot's of examples on how to read them.  Not sure if you're working in pandas or geopandas but there are examples of both.  The data was generated in 311-data-cleaning and 311-data-cleaning-part2 (mostly).  ENV.md explains how I create my env and environment.yml has the various packages I use.

I did have one issue cloning for my tests.  I ended up using git lfs clone <repo>.  It says it's deprecated but ...  I think my local gitconfig is hosed.

Let me know if you have any questions.

**Comment by ShikaZzz** [comment]
@mcmorgan27 thanks for the update! I didn't find how you dealt with invalid dates (e.g date is set to the previous year)  and the inconsistent NC names in 11-data-cleaning and 311-data-cleaning-part2. Is it not an issue for the 2021 data?

**Comment by mcmorgan27** [comment]
After our discussions this week this issue is complete and will be closed.
