### ISSUE TITLE
WEEKLY To Update Check

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/access-the-data#94]
### Overview
We need to make sure that volunteers are updating their issues in a timely way.

### Action Items
-  [x] Make a list of any items that have update label
-  [x] Review all in progress items that do not have update label
-  [x] Review items, add update reminder  to any issues that requires it
-  [ ] updating list with new link (optional)

### Resources/Instructions
[Issues with To Update ! label](https://github.com/hackforla/access-the-data/projects/1?card_filter_query=label%3A%22to+update+%21%22)
[All issues In Progress that don't have a update label](https://github.com/hackforla/access-the-data/projects/1?card_filter_query=-label%3A%22to+update+%21%22#column-12519286)
```
please update your issue with the following info  if you have not already
- Progress: "What is the current status of your project? What have you completed and what is left to do?"
- Blockers: "Difficulties or errors encountered."
- Availability: "How much time will you have this week to work on this issue?"
- ETA: "When do you expect this issue to be completed?"

If you need help:
1. Be sure to  annotate your issue with details on what you need and move it to the Questions/Review column so we can add it to the meeting agenda.  
2. Additionally feel free to reach out in the #access-the-data slack channel asking for help.
```

**Comment by ExperimentsInHonesty** [comment]
- #80 
- #68 
- #81 
- #85 
- #89 
- #83

**Comment by lrchang2** [comment]
- #95 
- #37

**Comment by lrchang2** [comment]
#104 
#95 
#106 
#96 
#83 
#102

**Comment by lrchang2** [comment]
- #104 
- #106

**Comment by lrchang2** [comment]
#109

**Comment by lrchang2** [comment]
- #119 
- #120 
- #52 
- #56 
- #109

**Comment by lrchang2** [comment]
- #104
- #120 
- #52 
- #56 
- #121 
- #102 
- #109

**Comment by lrchang2** [comment]
- #104 
- #127 
- #115 
- #106 
- #52
- #56 
- #109

**Comment by lrchang2** [comment]
- #127 
- #114 
- #106 
- #120 
- #96 
- #129 
- #56 
- #115

**Comment by lrchang2** [comment]
- #106
- #120 
- #56 
- #115 
- #109 
-

**Comment by lrchang2** [comment]
- #134 
- #127 
- #129 
- #56

**Comment by lrchang2** [comment]
- #134 
- #127 
- #114 
- #129 
- #115 
- #133

**Comment by lrchang2** [comment]
- #127 
- #52
- #56 
- #115 
-

**Comment by lrchang2** [comment]
- #144 
- #149 
- #147

**Comment by lrchang2** [comment]
- #147

**Comment by mxajPrice** [comment]
This is no longer needed as a separate issue.  This task is covered in the PM weekly agenda.
