### ISSUE TITLE
Create social media accounts

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/access-the-data#99]
### Overview
We need to have matching social media accounts to our domain name for outreach

### Action Items
- using the accessthedata@hackforla.org email account, setup social media accounts
- [x] Instagram
- [x] twitter
- for role based social accounts ask the following people to like the page you setup and then add the pm, the UX lead, any marketing people and bonnie as administrators with bonnie as the owner.
- [x] Facebook

### Resources/Instructions
Bonnie's facebook user https://www.facebook.com/ExperimentsInHonesty/
Lucy's facebook user https://www.facebook.com/lucy.chang.902
AJ's facebook user https://www.facebook.com/aceaj/

**Comment by lrchang2** [comment]
created twitter account and facebook page

**Comment by lrchang2** [comment]
- added Bonnie and Sequoia to Facebook as admins
- add current logo to all pages 
- Instagram account has been disabled - need to dispute

**Comment by lrchang2** [comment]
@ExperimentsInHonesty can you pop the "proof of domain name registration" here so I can dispute the instagram disabling?

**Comment by lrchang2** [comment]
Receipt for domain name: [accessthedata_billing.pdf](https://github.com/hackforla/access-the-data/files/8476682/accessthedata_billing.pdf)

**Comment by lrchang2** [comment]
sent Instagram dispute form with billing and emailed photo confirmation requested, currently waiting for response for next steps

**Comment by mxajPrice** [comment]
Access is on onepassword.  Lucy had issues getting into Instagram, the history can be found in the AccessTheData email.  All accounts are reserved for us.
